<?php
/***************************************************************************
								slogic_language.inc
							---------------------------
			created				: 04.01.2003
			edited				: -
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of slogic module

// start of main mavigation
$slogic_language['SLOGIC_MENU']		= 'Hauptmenu';
$slogic_language['SLOGIC_MAIN'] 	= 'Haupseite';
$slogic_language['SLOGIC_LOGOUT'] 	= 'Logout';
$slogic_language['SLOGIC_PROFILE'] 	= 'Profil &auml;ndern';
// end of main mavigation

// start of functions

// start of slogic_select_language.php
$slogic_language['SLOGIC_SELECT_LANGUAGE'] 	= 'Sprache ausw&auml;hlen';
// end of slogic_select_language.php

// start of slogic_profile.php
$slogic_language['SLOGIC_PROFILE_SUBMIT'] 	= 'Profil speichern';
$slogic_language['SLOGIC_RESET'] 			= 'Zur&uuml;cksetzen';
$slogic_language['SLOGIC_PASSWORD_MISMATCH']	= 'Die eingegebenen Passw&ouml;rter stimmen nicht &uuml;berein!';
$slogic_language['SLOGIC_PROFILE_UPDATED']	= 'Ihr Profil wurde erfolgreich ge&auml;ndert.';
// end of slogic_profile.php

// start of slogic_list_announcements.php
$slogic_language['SLOGIC_ANNOUNCEMENTS']	= 'Ank&uuml;ndigungen';
$slogic_language['SLOGIC_ANNOUNCEMENT']		= 'Ank&uuml;ndigung';
$slogic_language['SLOGIC_NO_ANNOUNCEMENTS'] = '<i>Keine Ank&uuml;ndigungen vorhanden.</i>';
// end of slogic_list_announcements.php

// start of slogic_show_announcement.php
$slogic_language['SLOGIC_WRONG_ANNOUNCEMENT'] 	= 'Sie haben nicht die n&ouml;tige Berechtigung diese Ank&uuml;ndigung zu lesen.';
$slogic_language['SLOGIC_INVALID_ANNOUNCEMENT'] = 'Sie versuchen eine nicht vorhandene Ank&uuml;ndigung zu lesen.';
// end of slogic_show_announcement.php

// end of functions

// *************************************************************** \\

// start of templates

// start of templates - pages
// start of slogic_login.tpl
$slogic_language['SLOGIC_LOGIN_TITLE'] = 'Support Logic - Login';
// end of slogic_login.tpl

// start of slogic_logout.tpl
$slogic_language['SLOGIC_LOGOUT_TITLE'] = 'Support Logic - Logout';
// end of slogic_logout.tpl

// start of slogic_register.tpl
$slogic_language['SLOGIC_REGISTER_TITLE'] = 'Support Logic - Account anlegen';
// end of slogic_register.tpl

// start of slogic_lost_password.tpl
$slogic_language['SLOGIC_LOST_PASSWORD_TITLE'] = 'Support Logic - Passwort zusenden';
// end of slogic_lost_password.tpl

// start of slogic_main.tpl
$slogic_language['SLOGIC_MAIN_TITLE'] = 'Support Logic - Hauptseite';
// end of slogic_main.tpl

// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_TITLE'] = 'Support Logic - Ihre Profileinstellungen';
// end of slogic_profile.tpl

// start of slogic_redirect.tpl
$slogic_language['SLOGIC_REDIRECT_TITLE'] 	= 'Support Logic - Automatische Weiterleitung';
$slogic_language['SLOGIC_REDIRECT_TOPIC'] 	= 'Bitte haben Sie einen Augenblick Geduld...';
$slogic_language['SLOGIC_REDIRECT_URL'] 	= 'Bitte klicken Sie hier, wenn Ihr Browser keine automatische Weiterleitung unterst&uuml;tzt.';
// end of slogic_redirect.tpl

// start of slogic_show_announcement.tpl
$slogic_language['SLOGIC_SHOW_ANNOUNCEMENT_TITLE'] = 'Support Logic - Ank&uuml;ndigung';
// end of slogic_show_announcement.tpl
// end of templates - pages

// start of templates - functions
// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_PASSWORD_INFO'] 	= 'Falls Sie ein neues Passwort eingeben funktioniert dieses beim n&auml;chsten Login.';
$slogic_language['SLOGIC_PROFILE_PASSWORD'] 	 	= 'Passwort';
$slogic_language['SLOGIC_PROFILE_PASSWORD_2'] 		= 'Passwort best&auml;tigen';
$slogic_language['SLOGIC_PROFILE_EMAIL'] 			= 'Email';
$slogic_language['SLOGIC_PROFILE_DOMAIN'] 			= 'Domain';
$slogic_language['SLOGIC_PROFILE_SERVER'] 			= 'Server';
$slogic_language['SLOGIC_PROFILE_ACT_USERNAME'] 	= 'Server-username';
$slogic_language['SLOGIC_PROFILE_LANGUAGE']			= 'Gespeicherte Sprache';
$slogic_language['SLOGIC_PROFILE_NOTIFICATION'] 	= 'Benachrichtigungen per email schicken';
// end of slogic_profile.tpl
// end of templates - functions

// end of templates
?>