// @version machine-pages-schema v2.0 (PostgreSQL)
//
// Drizzle schema for machine_pages table (62 records)
// Migrated from MySQL to PostgreSQL for Supabase

import { pgTable, serial, integer, varchar, text } from "drizzle-orm/pg-core";

export const machinePages = pgTable("machine_pages", {
  id: serial("id").primaryKey(),
  pkey: integer("pkey").notNull(),
  classKey: varchar("class_key", { length: 50 }).notNull(),
  fashionKey: varchar("fashion_key", { length: 4 }).notNull(),
  technicalKey: varchar("technical_key", { length: 4 }).notNull(),
  e2eKey: varchar("e2e_key", { length: 4 }).notNull(),
  code: varchar("code", { length: 15 }).notNull(),
  otId: integer("ot_id").notNull(),
  publish: varchar("publish", { length: 3 }).notNull(),
  style: varchar("style", { length: 30 }).notNull(),
  header: varchar("header", { length: 215 }).notNull(),
  description: text("description").notNull(),
  styleKey: varchar("style_key", { length: 25 }).notNull(),
  pageKey: varchar("page_key", { length: 20 }).notNull(),
  mrsp: varchar("mrsp", { length: 10 }).notNull(),
  speed: varchar("speed", { length: 10 }).notNull(),
  stitchRange: varchar("stitch_range", { length: 30 }).notNull(),
  stitchWidth: varchar("stitch_width", { length: 40 }).notNull(),
  seamType: varchar("seam_type", { length: 10 }).notNull(),
  feeds: varchar("feeds", { length: 50 }).notNull(),
  cutter: varchar("cutter", { length: 50 }).notNull(),
  threads: varchar("threads", { length: 50 }).notNull(),
  needles: varchar("needles", { length: 50 }).notNull(),
  numberOfThumbs: varchar("number_of_thumbs", { length: 2 }).notNull(),
  numberOfVideos: varchar("number_of_videos", { length: 2 }).notNull(),
  videoTagline1: varchar("video_tagline1", { length: 215 }).notNull(),
  videoTagline2: varchar("video_tagline2", { length: 215 }).notNull(),
  youtube1: varchar("youtube1", { length: 100 }).notNull(),
  youtube2: varchar("youtube2", { length: 100 }).notNull(),
  overview: text("overview").notNull(),
  how: text("how").notNull(),
  why: text("why").notNull(),
  whereUsed: text("where").notNull(),  // "where" is reserved in PG
  primaryApp: varchar("primary_app", { length: 200 }).notNull(),
  secondaryApp: varchar("secondary_app", { length: 200 }).notNull(),
  completeAppList: text("complete_app_list").notNull(),
  flickrSet: varchar("flickr_set", { length: 25 }).notNull(),
  contactStitch: varchar("contact_stitch", { length: 215 }).notNull(),
  needleStandard: varchar("needle_standard", { length: 215 }).notNull(),
  needleRange: varchar("needle_range", { length: 215 }).notNull(),
  needlePlate: varchar("needle_plate", { length: 215 }).notNull(),
  eccentrics: varchar("eccentrics", { length: 215 }).notNull(),
  upperLooper: varchar("upper_looper", { length: 215 }).notNull(),
  lowerLooper: varchar("lower_looper", { length: 215 }).notNull(),
  stitchType: varchar("stitch_type", { length: 215 }).notNull(),
  height: varchar("height", { length: 10 }).notNull(),
  width: varchar("width", { length: 10 }).notNull(),
  length: varchar("length", { length: 10 }).notNull(),
  weight: varchar("weight", { length: 20 }).notNull(),
  env: varchar("env", { length: 100 }).notNull(),
  noise: varchar("noise", { length: 10 }).notNull(),
  heat: varchar("heat", { length: 10 }).notNull(),
  installation: varchar("installation", { length: 215 }).notNull(),
  motorSpec: varchar("motor_spec", { length: 215 }).notNull(),
  fabrics: varchar("fabrics", { length: 215 }).notNull(),
  shippingSize: varchar("shipping_size", { length: 40 }).notNull(),
  shippingWeight: varchar("shipping_weight", { length: 10 }).notNull(),
  seoTitle: text("seo_title").notNull(),
  seoKeywords: text("seo_keywords").notNull(),
  seoSearchDescription: text("seo_search_description").notNull(),
  seoSearchKeywords: text("seo_search_keywords").notNull(),
  seoSearchTitle: text("seo_search_title").notNull(),
  seoBrand: text("seo_brand").notNull(),
  marketingUrl1: varchar("marketing_url1", { length: 100 }).notNull(),
  marketingUrl2: varchar("marketing_url2", { length: 100 }).notNull(),
  marketingUrl3: varchar("marketing_url3", { length: 100 }).notNull(),
  marketingUrl4: varchar("marketing_url4", { length: 100 }).notNull(),
  marketingUrl5: varchar("marketing_url5", { length: 100 }).notNull(),
  marketingIcon1: varchar("marketing_icon1", { length: 100 }).notNull(),
  marketingIcon2: varchar("marketing_icon2", { length: 100 }).notNull(),
  marketingIcon3: varchar("marketing_icon3", { length: 100 }).notNull(),
  marketingIcon4: varchar("marketing_icon4", { length: 100 }).notNull(),
  marketingIcon5: varchar("marketing_icon5", { length: 100 }).notNull(),
  marketingTagline1: varchar("marketing_tagline1", { length: 100 }).notNull(),
  marketingTagline2: varchar("marketing_tagline2", { length: 100 }).notNull(),
  marketingTagline3: varchar("marketing_tagline3", { length: 100 }).notNull(),
  marketingTagline4: varchar("marketing_tagline4", { length: 100 }).notNull(),
  marketingTagline5: varchar("marketing_tagline5", { length: 100 }).notNull(),
  price: integer("price").notNull(),
});

export type MachinePage = typeof machinePages.$inferSelect;
export type NewMachinePage = typeof machinePages.$inferInsert;
