<?php
/***************************************************************************
								slogic_language.inc
							---------------------------
			created				: 04.01.2003
			edited				: -
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of slogic module

// start of main mavigation
$slogic_language['SLOGIC_MENU']		= 'Hauptmenu';
$slogic_language['SLOGIC_MAIN'] 	= 'Haupseite';
$slogic_language['SLOGIC_LOGOUT'] 	= 'Logout';
$slogic_language['SLOGIC_PROFILE'] 	= 'Profil &auml;ndern';
$slogic_language['SLOGIC_LIST_QUICK_REPLIES'] = 'Gespeicherte Antworten';
// end of main mavigation

// start of list fields
$slogic_language['SLOGIC_USERNAME'] = 'Benutzer';
$slogic_language['SLOGIC_INFO'] = 'Info';
$slogic_language['SLOGIC_MESSAGE'] = 'Notiz';
$slogic_language['SLOGIC_EDIT'] = '&Auml;ndern';
$slogic_language['SLOGIC_DELETE'] = 'L&ouml;schen';
$slogic_language['SLOGIC_ALL'] = 'alle';
$slogic_language['SLOGIC_SUBMIT'] = 'Speichern';
//end of list fields

// start of functions

// start of slogic_select_language.php
$slogic_language['SLOGIC_SELECT_LANGUAGE'] 	= 'Sprache ausw&auml;hlen';
// end of slogic_select_language.php

// start of slogic_profile.php
$slogic_language['SLOGIC_PROFILE_SUBMIT'] 	= 'Profil speichern';
$slogic_language['SLOGIC_RESET'] 			= 'Zur&uuml;cksetzen';
$slogic_language['SLOGIC_PASSWORD_MISMATCH']	= 'Die eingegebenen Passw&ouml;rter stimmen nicht &uuml;berein!';
$slogic_language['SLOGIC_PROFILE_UPDATED']	= 'Ihr Profil wurde erfolgreich ge&auml;ndert.';
// end of slogic_profile.php

// start of slogic_show_user_profile.php
$slogic_language['SLOGIC_SHOW_USER_PROFILE_NONE']   = 'Benutzer existiert nicht.';
$slogic_language['SLOGIC_SHOW_USER_PROFILE']		= 'Profil anzeigen';
$slogic_language['SLOGIC_SHOW_USER_PROFILE_OF']		= 'Profil von Benutzer:';
$slogic_language['SLOGIC_EMAIL'] 					= 'Email:';
$slogic_language['SLOGIC_DOMAIN']					= 'Domain:';
$slogic_language['SLOGIC_ACT_SERVER']				= 'Server:';
$slogic_language['SLOGIC_ACT_USERNAME']				= 'Server-Username:';
$slogic_language['SLOGIC_GET_EMAIL']				= 'Erh&auml;lt Email-Benachrichtigungen:';
$slogic_language['SLOGIC_LANGUAGE']					= 'Voreingestellte Sprache:';
// end of slogic_show_user_profile.php

// start of slogic_list_announcements.php
$slogic_language['SLOGIC_ANNOUNCEMENTS']	= 'Ank&uuml;ndigungen';
$slogic_language['SLOGIC_ANNOUNCEMENT']		= 'Ank&uuml;ndigung';
$slogic_language['SLOGIC_NO_ANNOUNCEMENTS'] = '<i>Keine Ank&uuml;ndigungen vorhanden.</i>';
// end of slogic_list_announcements.php

// start of slogic_show_announcement.php
$slogic_language['SLOGIC_WRONG_ANNOUNCEMENT'] 	= 'Sie haben nicht die n&ouml;tige Berechtigung diese Ank&uuml;ndigung zu lesen.';
$slogic_language['SLOGIC_INVALID_ANNOUNCEMENT'] = 'Sie versuchen eine nicht vorhandene Ank&uuml;ndigung zu lesen.';
// end of slogic_show_announcement.php

// start of slogic_edit_quick_reply.php
$slogic_language['SLOGIC_QUICK_REPLY_EDITED'] 	= 'Die gespeicherte Anwtort wurde ge&auml;ndert.';
$slogic_language['SLOGIC_QUICK_REPLY_EDITED_INVALID'] = 'Illegale Funktion.';
// end of slogic_edit_quick_reply.php

// end of functions

// *************************************************************** \\

// start of templates

// start of templates - pages
// start of slogic_login.tpl
$slogic_language['SLOGIC_LOGIN_TITLE'] = 'Support Logic - Login';
// end of slogic_login.tpl

// start of slogic_logout.tpl
$slogic_language['SLOGIC_LOGOUT_TITLE'] = 'Support Logic - Logout';
// end of slogic_logout.tpl

// start of slogic_main.tpl
$slogic_language['SLOGIC_MAIN_TITLE'] = 'Support Logic - Hauptseite';
// end of slogic_main.tpl

// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_TITLE'] = 'Support Logic - Ihre Profileinstellungen';
// end of slogic_profile.tpl

// start of slogic_show_user_profile.tpl
$slogic_language['SLOGIC_SHOW_USER_PROFILE_TITLE'] = 'Support Logic - Profileinstellungen Ansehen';
// end of slogic_show_user_profile.tpl

// start of slogic_redirect.tpl
$slogic_language['SLOGIC_REDIRECT_TITLE'] 	= 'Support Logic - Automatische Weiterleitung';
$slogic_language['SLOGIC_REDIRECT_TOPIC'] 	= 'Bitte haben Sie einen Augenblick Geduld...';
$slogic_language['SLOGIC_REDIRECT_URL'] 	= 'Bitte klicken Sie hier, wenn Ihr Browser keine automatische Weiterleitung unterst&uuml;tzt.';
// end of slogic_redirect.tpl

// start of slogic_show_announcement.tpl
$slogic_language['SLOGIC_SHOW_ANNOUNCEMENT_TITLE'] = 'Support Logic - Ank&uuml;ndigung';
// end of slogic_show_announcement.tpl

// start of slogic_list_quick_replies.tpl
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_TITLE'] = 'Support Logic - Gespeicherte Antworten';
// end of slogic_list_quick_replies.tpl

// start of slogic_edit_quick_reply.tpl
$slogic_language['SLOGIC_EDIT_QUICK_REPLY_TITLE'] = 'Support Logic - Gespeicherte Antwort &auml;ndern';
// end of slogic_edit_quick_reply.tpl

// end of templates - pages

// start of templates - functions
// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_PASSWORD_INFO'] 	= 'Falls Sie ein neues Passwort eingeben funktioniert dieses beim n&auml;chsten Login.';
$slogic_language['SLOGIC_PROFILE_PASSWORD'] 	 	= 'Passwort';
$slogic_language['SLOGIC_PROFILE_PASSWORD_2'] 		= 'Passwort best&auml;tigen';
$slogic_language['SLOGIC_PROFILE_EMAIL'] 			= 'Email';
$slogic_language['SLOGIC_PROFILE_SIGNATURE']		= 'Signatur';
$slogic_language['SLOGIC_PROFILE_DOMAIN'] 			= 'Domain';
$slogic_language['SLOGIC_PROFILE_SERVER'] 			= 'Server';
$slogic_language['SLOGIC_PROFILE_ACT_USERNAME'] 	= 'Server-username';
$slogic_language['SLOGIC_PROFILE_LANGUAGE']			= 'Gespeicherte Sprache';
$slogic_language['SLOGIC_PROFILE_NOTIFICATION'] 	= 'Benachrichtigungen per email schicken';
$slogic_language['SLOGIC_PROFILE_SUBSCRIBE'] 		= 'Kategorien ausw&auml;hlen';
// end of slogic_profile.tpl

// start of slogic_list_quick_replies.tpl
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_NO_REPLIES'] = '<i>Keine gespeicherten Antworten vorhanden.</i>';
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_DELETE_ALL'] = 'Alle l&ouml;schen';
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_DELETED'] = 'Gespeicherte Antwort(en) wurden erfolgreich gel&ouml;scht.';
// end of slogic_list_quick_replies.tpl

// start of slogic_edit_quick_reply.tpl
$slogic_language['SLOGIC_EDIT_QUICK_REPLY'] = 'Gespeicherte Antwort &auml;ndern';
// end of slogic_edit_quick_reply.tpl

// start of slogic_add_quick_reply.tpl
$slogic_language['SLOGIC_ADD_QUICK_REPLY'] = 'Gespeicherte Antwort hinzuf&uuml;gen';
$slogic_language['SLOGIC_QUICK_REPLY_ADDED'] = 'Gespeicherte Antwort hinzugef&uuml;gt';
$slogic_language['SLOGIC_QUICK_REPLY_ADDED_INVALID'] = 'Illegale Funktion.';
// end of slogic_add_quick_reply.tpl

// end of templates - functions

// end of templates
?>