<?

    //the Username & Password you use to login to your MailChimp account
    $username = 'merrow';
    $password = 'MSMC1111';
    
    // A List Id to run examples against. use lists() to view all
    $listId = 'Textile Plants Brazil - see lists() method';
    
    // A Campaign Id to run examples against. use campaigns() to view all
    $campaignId = $parsnip['campaign1'];

    //some email addresses used in the examples:
    $my_email = 'charlie@merrow.com';
    $boss_man_email = 'owen@merrow.com';
    
    //you shouldn't need to change this. It is defined for internal testing
    $apiUrl = 'http://api.mailchimp.com/1.1/';
