<? $partyid = $_GET['8787'];
$first = $_GET['33950019334xxlmmnot'];
$last = $_GET['908234klsdfzwe38hna9f7s'];

$whole = $partyid . $first . $last;

if ($whole!=null) {
setcookie("merid", "$whole", time()+3600*60);} 







// then we connect to the database as renter and access table: inventory 
#
mysql_connect("localhost", "merrowco_renter", "7679") or die(mysql_error());

#
mysql_select_db("merrowco_inventory") or die(mysql_error());



   // Get all the data from the "asin" table which is where our product info is kept
$result = mysql_query("SELECT * FROM agent_word WHERE agent_id='$whole'")
or die(mysql_error());


// then define juju as the result array
 $parsnip = mysql_fetch_array($result); 
 

 $thetable = $parsnip['table'];

if ( $thetable!=null) { 
setcookie("keymaster", "$thetable", time()+3600*60);}




if (isset($_COOKIE['keymaster'])) {

$button = $_COOKIE['keymaster']; }

else { $button == $whole; }


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Textile Plants</title>

<link rel="stylesheet" href="http://css.imerrow.com/css_major/cs_global_interactive_form.css" type="text/css" charset="utf-8">
<style type="text/css">
<!--
.style1 {
	color: #000000;
	font-weight: bold;
}
-->
</style>

<link rel="stylesheet" type="text/css" media="screen" href="http://css.imerrow.com/css_major/calendar-system.css">

<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar.js"></script>
<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar-en.js"></script>
<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar-setup.js"></script>
 
</head>

<body>

<div class="topbar"></div> <div class="title"> <a href="#">View Site</a> </div>
<div class="mapimage">
<a href="#"><img src="http://images.imerrow.com/images/mapicon.jpg" alt="" name="map" width="30" height="30" /></a></a></div>

<? #
$cranberry = $_COOKIE['merid']; 

mysql_select_db("merrowco_inventory") or die(mysql_error());


if ($whole!=null) {

   // Get all the data from the "asin" table which is where our product info is kept
$result1 = mysql_query("SELECT * FROM agent_word WHERE agent_id='$whole'")
or die(mysql_error()); }

else { 

  // Get all the data from the "asin" table which is where our product info is kept
$result1 = mysql_query("SELECT * FROM agent_word WHERE agent_id='$cranberry'")
or die(mysql_error());

}


// then define juju as the result array
 $tunafish = mysql_fetch_array($result1); 
 $banana = $tunafish['party_id'];
 
 
  // Get all the data from the "asin" table which is where our product info is kept
$result2 = mysql_query("SELECT * FROM agent_revenue WHERE party_id='$banana'")
or die(mysql_error()); 

// then define juju as the result array
 $marlinfish = mysql_fetch_array($result2); 


 if ($_GET['frommap'] == 2) { } else {?>



<div class="welcome">Welcome <? echo $tunafish['name']; ?></div> <div class="firstparagraph"><div class="revenue"> Our Scoreboard: </div><div class="totals"><span class="style1">Period 1 =</span> $<? echo $marlinfish['2008']; ?>.00  ||  <span class="style1">Period Total =</span> $<? echo $marlinfish['2009']; ?>.00</div> </div>
</div>




<?php

}



/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table
$opts['hn'] = 'localhost';
$opts['un'] = 'merrowco_mg2';
$opts['pw'] = 'gl0balgl0bal';
$opts['db'] = 'merrowco_hydedata';
if ($thetable!=null) {

$opts['tb'] =  $thetable ;}

else { 

$opts['tb'] =  $button ;}

// Name of field which is the unique key
$opts['key'] = 'id';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'string';

// Sorting field(s)
$opts['sort_field'] = array('id');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 50;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'ACPF';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'G';
$opts['url'] = array('images' => 'db_images/'); 

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => true,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'] . '-UTF8';

/* Table-level filter capability. If set, it is included in the WHERE clause
   of any generated SELECT statement in SQL query. This gives you ability to
   work only with subset of data from table.

$opts['filters'] = "column1 like '%11%' AND column2<17";
$opts['filters'] = "section_id = 9";
$opts['filters'] = "PMEtable0.sessions_count > 200";
*/

/* Field definitions
   
Fields will be displayed left to right on the screen in the order in which they
appear in generated list. Here are some most used field options documented.

['name'] is the title used for column headings, etc.;
['maxlen'] maximum length to display add/edit/search input boxes
['trimlen'] maximum length of string content to display in row listing
['width'] is an optional display width specification for the column
          e.g.  ['width'] = '100px';
['mask'] a string that is used by sprintf() to format field output
['sort'] true or false; means the users may sort the display on this column
['strip_tags'] true or false; whether to strip tags from content
['nowrap'] true or false; whether this field should get a NOWRAP
['select'] T - text, N - numeric, D - drop-down, M - multiple selection
['options'] optional parameter to control whether a field is displayed
  L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
            Another flags are:
            R - indicates that a field is read only
            W - indicates that a field is a password field
            H - indicates that a field is to be hidden and marked as hidden
['URL'] is used to make a field 'clickable' in the display
        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
['URLtarget']  HTML target link specification (for example: _blank)
['textarea']['rows'] and/or ['textarea']['cols']
  specifies a textarea is to be used to give multi-line input
  e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
['values'] restricts user input to the specified constants,
           e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
['values']['table'] and ['values']['column'] restricts user input
  to the values found in the specified column of another table
['values']['description'] = 'desc_column'
  The optional ['values']['description'] field allows the value(s) displayed
  to the user to be different to those in the ['values']['column'] field.
  This is useful for giving more meaning to column values. Multiple
  descriptions fields are also possible. Check documentation for this.
*/



$opts['fdd']['id'] = array(
  'name'     => 'ID',
  'select'   => 'T',
  'options'  => 'AVCPDR', // auto increment
  'maxlen'   => 10,
  'default'  => '0',
  'options' => 'APC',
  'sort'     => true
);

$opts['fdd']['mgs_ManufacturerPartNumber'] = array(
  'name'     => 'Manufacturer Part Number',
  'select'   => 'T',
  'maxlen'   => 10,

  'sort'     => true
);
$opts['fdd']['mgs_sku'] = array(
  'name'     => 'Merrow Global Store SKU',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APVC',
  'sort'     => true
);

$opts['fdd']['mgs_amazon_GritRating'] = array(
  'name'     => 'Amazon Grit Rating',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);



  /*  
$opts['fdd']['mgs_amazon_GritRating']['default'] = '';
$opts['fdd']['mgs_amazon_GritRating']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_GritRating']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_GritRating']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_GritRating']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_GritRating']['values']['filters'] = 'value_type = "mgs_amazon_GritRating"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_GritRating']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_GritRating']['name'] = 'Amazon Grit Rating'; //title name in column view
*/


$opts['fdd']['mgs_features_grit#'] = array(
  'name'     => 'MGS Grit',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
/*
$opts['fdd']['mgs_features_grit#']['default'] = '';
$opts['fdd']['mgs_features_grit#']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_grit#']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_grit#']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_grit#']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_grit#']['values']['filters'] = 'value_type = "mgs_features_grit#"'; //matches fields in field_data table
$opts['fdd']['mgs_features_grit#']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_grit#']['name'] = 'Hyde Grit Number'; //title name in column view

*/

$opts['fdd']['mgs_image1'] = array(
  'name'     => 'Image 1',
  'select'   => 'T',
  'maxlen'   => 40,
  'sort'     => true
);
$opts['fdd']['mgs_image2'] = array(
  'name'     => 'Image 2',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_image3'] = array(
  'name'     => 'Image 3',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_image4'] = array(
  'name'     => 'Image 4',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_image5'] = array(
  'name'     => 'Image 5',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_image6'] = array(
  'name'     => 'Image 6',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_image7'] = array(
  'name'     => 'Image 7',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_image8'] = array(
  'name'     => 'Image 8',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image1'] = array(
  'name'     => 'Amazon Image 1',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APVC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image2'] = array(
  'name'     => 'Amazon Image 2',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image3'] = array(
  'name'     => 'Amazon Image 3',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image4'] = array(
  'name'     => 'Amazon Image 4',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image5'] = array(
  'name'     => 'Amazon Image 5',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image6'] = array(
  'name'     => 'Amazon Image 6',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image7'] = array(
  'name'     => 'Amazon Image 7',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image8'] = array(
  'name'     => 'Amazon Image 8',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_image'] = array(
  'name'     => 'Amazon Image',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_parentSKU'] = array(
  'name'     => 'Parent SKU',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_Relationshiptype'] = array(
  'name'     => 'Relationship Type',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);

/*
$opts['fdd']['mgs_amazon_Relationshiptype']['default'] = '';
$opts['fdd']['mgs_amazon_Relationshiptype']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_Relationshiptype']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_Relationshiptype']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_Relationshiptype']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_Relationshiptype']['values']['filters'] = 'value_type = "mgs_amazon_Relationshiptype"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_Relationshiptype']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_Relationshiptype']['name'] = 'Relationship Type'; //title name in column view

*/

   $opts['fdd']['mgs_amazon_targetaudience'] = array(
  'name'     => 'Target Audience',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
/*
$opts['fdd']['mgs_amazon_targetaudience']['default'] = '';
$opts['fdd']['mgs_amazon_targetaudience']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_targetaudience']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_targetaudience']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_targetaudience']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_targetaudience']['values']['filters'] = 'value_type = "mgs_amazon_targetaudience"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_targetaudience']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_targetaudience']['name'] = 'Target Audience'; //title name in column view

*/
$opts['fdd']['mgs_amazon_usedfor1'] = array(
  'name'     => 'Used For 1',
  'select'   => 'T',
  'maxlen'   => 50,
  'sort'     => true
);
$opts['fdd']['mgs_amazon_usedfor2'] = array(
  'name'     => 'Used For 2',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_usedfor3'] = array(
  'name'     => 'Used For 3',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_usedfor4'] = array(
  'name'     => 'Used For 4',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_usedfor5'] = array(
  'name'     => 'Used For 5',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);

/*

$opts['fdd']['mgs_amazon_usedfor1']['default'] = '';
$opts['fdd']['mgs_amazon_usedfor1']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_usedfor1']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_usedfor1']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_usedfor1']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_usedfor1']['values']['filters'] = 'value_type = "mgs_amazon_usedfor"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_usedfor1']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_usedfor1']['name'] = 'Used For 1'; //title name in column view

$opts['fdd']['mgs_amazon_usedfor2']['default'] = '';
$opts['fdd']['mgs_amazon_usedfor2']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_usedfor2']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_usedfor2']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_usedfor2']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_usedfor2']['values']['filters'] = 'value_type = "mgs_amazon_usedfor"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_usedfor2']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_usedfor2']['name'] = 'Used For 2'; //title name in column view

$opts['fdd']['mgs_amazon_usedfor3']['default'] = '';
$opts['fdd']['mgs_amazon_usedfor3']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_usedfor3']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_usedfor3']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_usedfor3']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_usedfor3']['values']['filters'] = 'value_type = "mgs_amazon_usedfor"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_usedfor3']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_usedfor3']['name'] = 'Used For 3'; //title name in column view

$opts['fdd']['mgs_amazon_usedfor4']['default'] = '';
$opts['fdd']['mgs_amazon_usedfor4']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_usedfor4']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_usedfor4']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_usedfor4']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_usedfor4']['values']['filters'] = 'value_type = "mgs_amazon_usedfor"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_usedfor4']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_usedfor4']['name'] = 'Used For 4'; //title name in column view

$opts['fdd']['mgs_amazon_usedfor5']['default'] = '';
$opts['fdd']['mgs_amazon_usedfor5']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_usedfor5']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_usedfor5']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_usedfor5']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_usedfor5']['values']['filters'] = 'value_type = "mgs_amazon_usedfor"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_usedfor5']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_usedfor5']['name'] = 'Used For 5'; //title name in column view

*/
   $opts['fdd']['mgs_amazon_update-delete'] = array(
  'name'     => 'Update/Delete',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
/*
$opts['fdd']['mgs_amazon_update-delete']['default'] = '';
$opts['fdd']['mgs_amazon_update-delete']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_amazon_update-delete']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_amazon_update-delete']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_amazon_update-delete']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_amazon_update-delete']['values']['filters'] = 'value_type = "mgs_amazon_update-delete"'; //matches fields in field_data table
$opts['fdd']['mgs_amazon_update-delete']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_amazon_update-delete']['name'] = 'Update or Delete'; //title name in column view

*/

$opts['fdd']['mgs_applications'] = array(
  'name'     => 'Applications',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_asin'] = array(
  'name'     => 'ASIN',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_bullet1'] = array(
  'name'     => 'Amazon Bullet 1',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_bullet2'] = array(
  'name'     => 'Amazon Bullet 2',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_bullet3'] = array(
  'name'     => 'Amazon Bullet 3',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_bullet4'] = array(
  'name'     => 'Amazon Bullet 4',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_bullet5'] = array(
  'name'     => 'Amazon Bullet 5',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_description'] = array(
  'name'     => 'Description',
  'select'   => 'T',
  'maxlen'   => 65535,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'options' => 'AVPC',
  'sort'     => true
);
$opts['fdd']['mgs_description_hydetools'] = array(
  'name'     => 'Hyde Store Description',
  'select'   => 'T',
  'maxlen'   => 65535,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'options' => 'APC',
  'sort'     => true
);



$opts['fdd']['mgs_features_blade_pliability'] = array(
  'name'     => 'Blade Pliability',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_blade_type'] = array(
  'name'     => 'Blade Type',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_blade_width'] = array(
  'name'     => 'Blade Width',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_brush_size'] = array(
  'name'     => 'Brush Size',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_float_type'] = array(
  'name'     => 'Float Type',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_gauge'] = array(
  'name'     => 'Gauge',
  'select'   => 'T',
  'maxlen'   => 2,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_handle_type'] = array(
  'name'     => 'Handle Type',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_knife_type'] = array(
  'name'     => 'Knife Type',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_mill_blade_type'] = array(
  'name'     => 'Mill Blade Type',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_model_series'] = array(
  'name'     => 'Model Series',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_notch_type'] = array(
  'name'     => 'Notch Type',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_pole_length'] = array(
  'name'     => 'Pole Length',
  'select'   => 'T',
  'maxlen'   => 2,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_psi'] = array(
  'name'     => 'PSI',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_roller_type'] = array(
  'name'     => 'Roller Type',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_spray_shield_size'] = array(
  'name'     => 'Spray Shield Size',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_tool_type'] = array(
  'name'     => 'Tool Type',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_trowel_shape'] = array(
  'name'     => 'Trowel Shape',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_features_trowel_size'] = array(
  'name'     => 'Trowel Size',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);


$opts['fdd']['mgs_for_sale'] = array(
  'name'     => 'For Sale',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);

/*

$opts['fdd']['mgs_features_blade_pliability']['default'] = '';
$opts['fdd']['mgs_features_blade_pliability']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_blade_pliability']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_blade_pliability']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_blade_pliability']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_blade_pliability']['values']['filters'] = 'value_type = "mgs_features_blade_pliability"'; //matches fields in field_data table
$opts['fdd']['mgs_features_blade_pliability']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_blade_pliability']['name'] = 'Blade Pliability'; //title name in column view


$opts['fdd']['mgs_features_blade_width']['default'] = '';
$opts['fdd']['mgs_features_blade_width']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_blade_width']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_blade_width']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_blade_width']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_blade_width']['values']['filters'] = 'value_type = "mgs_features_blade_width"'; //matches fields in field_data table
$opts['fdd']['mgs_features_blade_width']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_blade_width']['name'] = 'Blade Width'; //title name in column view


$opts['fdd']['mgs_features_blade_type']['default'] = '';
$opts['fdd']['mgs_features_blade_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_blade_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_blade_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_blade_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_blade_type']['values']['filters'] = 'value_type = "mgs_features_blade_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_blade_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_blade_type']['name'] = 'Blade Type'; //title name in column view


$opts['fdd']['mgs_features_brush_size']['default'] = '';
$opts['fdd']['mgs_features_brush_size']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_brush_size']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_brush_size']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_brush_size']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_brush_size']['values']['filters'] = 'value_type = "mgs_features_brush_size"'; //matches fields in field_data table
$opts['fdd']['mgs_features_brush_size']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_brush_size']['name'] = 'Brush Size'; //title name in column view


$opts['fdd']['mgs_features_float_type']['default'] = '';
$opts['fdd']['mgs_features_float_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_float_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_float_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_float_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_float_type']['values']['filters'] = 'value_type = "mgs_features_float_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_float_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_float_type']['name'] = 'Float Type'; //title name in column view


$opts['fdd']['mgs_features_gauge']['default'] = '';
$opts['fdd']['mgs_features_gauge']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_gauge']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_gauge']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_gauge']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_gauge']['values']['filters'] = 'value_type = "mgs_features_gauge"'; //matches fields in field_data table
$opts['fdd']['mgs_features_gauge']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_gauge']['name'] = 'The Guage'; //title name in column view


$opts['fdd']['mgs_features_handle_type']['default'] = '';
$opts['fdd']['mgs_features_handle_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_handle_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_handle_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_handle_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_handle_type']['values']['filters'] = 'value_type = "mgs_features_handle_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_handle_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_handle_type']['name'] = 'Handle Type'; //title name in column view


$opts['fdd']['mgs_features_knife_type']['default'] = '';
$opts['fdd']['mgs_features_knife_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_knife_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_knife_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_knife_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_knife_type']['values']['filters'] = 'value_type = "mgs_features_knife_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_knife_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_knife_type']['name'] = 'Knife Type'; //title name in column view



$opts['fdd']['mgs_features_mill_blade_type']['default'] = '';
$opts['fdd']['mgs_features_mill_blade_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_mill_blade_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_mill_blade_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_mill_blade_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_mill_blade_type']['values']['filters'] = 'value_type = "mgs_features_mill_blade_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_mill_blade_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_mill_blade_type']['name'] = 'Mill Blade Type'; //title name in column view


$opts['fdd']['mgs_features_model_series']['default'] = '';
$opts['fdd']['mgs_features_model_series']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_model_series']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_model_series']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_model_series']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_model_series']['values']['filters'] = 'value_type = "mgs_features_model_series"'; //matches fields in field_data table
$opts['fdd']['mgs_features_model_series']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_model_series']['name'] = 'Model Series'; //title name in column view


$opts['fdd']['mgs_features_notch_type']['default'] = '';
$opts['fdd']['mgs_features_notch_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_notch_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_notch_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_notch_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_notch_type']['values']['filters'] = 'value_type = "mgs_features_notch_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_notch_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_notch_type']['name'] = 'Notch Type'; //title name in column view


$opts['fdd']['mgs_features_pole_length']['default'] = '';
$opts['fdd']['mgs_features_pole_length']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_pole_length']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_pole_length']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_pole_length']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_pole_length']['values']['filters'] = 'value_type = "mgs_features_pole_length"'; //matches fields in field_data table
$opts['fdd']['mgs_features_pole_length']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_pole_length']['name'] = 'Pole Length'; //title name in column view


$opts['fdd']['mgs_features_psi']['default'] = '';
$opts['fdd']['mgs_features_psi']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_psi']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_psi']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_psi']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_psi']['values']['filters'] = 'value_type = "mgs_features_psi"'; //matches fields in field_data table
$opts['fdd']['mgs_features_psi']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_psi']['name'] = 'PSI'; //title name in column view


$opts['fdd']['mgs_features_roller_type']['default'] = '';
$opts['fdd']['mgs_features_roller_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_roller_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_roller_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_roller_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_roller_type']['values']['filters'] = 'value_type = "mgs_features_roller_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_roller_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_roller_type']['name'] = 'Roller Type'; //title name in column view


$opts['fdd']['mgs_features_spray_shield_size']['default'] = '';
$opts['fdd']['mgs_features_spray_shield_size']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_spray_shield_size']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_spray_shield_size']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_spray_shield_size']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_spray_shield_size']['values']['filters'] = 'value_type = "mgs_features_spray_shield_size"'; //matches fields in field_data table
$opts['fdd']['mgs_features_spray_shield_size']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_spray_shield_size']['name'] = 'Spray Shield Size'; //title name in column view


$opts['fdd']['mgs_features_tool_type']['default'] = '';
$opts['fdd']['mgs_features_tool_type']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_tool_type']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_tool_type']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_tool_type']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_tool_type']['values']['filters'] = 'value_type = "mgs_features_tool_type"'; //matches fields in field_data table
$opts['fdd']['mgs_features_tool_type']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_tool_type']['name'] = 'Tool Type'; //title name in column view


$opts['fdd']['mgs_features_trowel_shape']['default'] = '';
$opts['fdd']['mgs_features_trowel_shape']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_trowel_shape']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_trowel_shape']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_trowel_shape']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_trowel_shape']['values']['filters'] = 'value_type = "mgs_features_trowel_shape"'; //matches fields in field_data table
$opts['fdd']['mgs_features_trowel_shape']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_trowel_shape']['name'] = 'Trowel Shape'; //title name in column view


$opts['fdd']['mgs_features_trowel_size']['default'] = '';
$opts['fdd']['mgs_features_trowel_size']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_features_trowel_size']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_features_trowel_size']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_features_trowel_size']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_features_trowel_size']['values']['filters'] = 'value_type = "mgs_features_trowel_size"'; //matches fields in field_data table
$opts['fdd']['mgs_features_trowel_size']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_features_trowel_size']['name'] = 'Trowel Size'; //title name in column view

*/

$opts['fdd']['mgs_google_link'] = array(
  'name'     => 'Google Link',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_height'] = array(
  'name'     => 'Height',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_length'] = array(
  'name'     => 'Length',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);

$opts['fdd']['mgs_MerchantCatalogNumber'] = array(
  'name'     => 'Merchant Catalog Number',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_MSRP'] = array(
  'name'     => 'MSRP',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);

$opts['fdd']['mgs_NumberOfItemsInPackage'] = array(
  'name'     => 'Package Quantity',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);

/*
$opts['fdd']['mgs_NumberOfItemsInPackage']['default'] = '';
$opts['fdd']['mgs_NumberOfItemsInPackage']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_NumberOfItemsInPackage']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_NumberOfItemsInPackage']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_NumberOfItemsInPackage']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_NumberOfItemsInPackage']['values']['filters'] = 'value_type = "mgs_NumberOfItemsInPackage"'; //matches fields in field_data table
$opts['fdd']['mgs_NumberOfItemsInPackage']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_NumberOfItemsInPackage']['name'] = 'Units in Package'; //title name in column view
*/

$opts['fdd']['mgs_price_amazon'] = array(
  'name'     => 'Amazon Price',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_ProductName'] = array(
  'name'     => 'Amazon Product Name',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_products_associated'] = array(
  'name'     => 'Associated Products',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_products_cross_sell'] = array(
  'name'     => 'Cross Sell Products',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_products_upsell'] = array(
  'name'     => 'Upsell Products',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_quantity'] = array(
  'name'     => 'Stock Level',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_searchterms'] = array(
  'name'     => 'Search Terms',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_sku_amazon'] = array(
  'name'     => 'Amazon SKU',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_sku_superior'] = array(
  'name'     => 'Superior SKU',
  'select'   => 'T',
  'maxlen'   => 30,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_StandardProductID'] = array(
  'name'     => 'Amazon Standard Product ID',
  'select'   => 'T',
  'maxlen'   => 16,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_title'] = array(
  'name'     => 'Product Title',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_url_key'] = array(
  'name'     => 'URL key',
  'select'   => 'T',
  'maxlen'   => 150,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_weight'] = array(
  'name'     => 'Shipping Weight',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_width'] = array(
  'name'     => 'Product Width',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['cat_id'] = array(
  'name'     => 'Category ID',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_google_cat'] = array(
  'name'     => 'Google Category',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_end_point'] = array(
  'name'     => 'Category End Point',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_itemtype'] = array(
  'name'     => 'Amazon Item Type',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_webstore_cat'] = array(
  'name'     => 'Webstore Category',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_shopzilla_cat'] = array(
  'name'     => 'Shopzilla Cat',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_1'] = array(
  'name'     => 'Category 1',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_2'] = array(
  'name'     => 'Category 2',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_3'] = array(
  'name'     => 'Category 3',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_4'] = array(
  'name'     => 'Category 4',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_5'] = array(
  'name'     => 'Category 5',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_6'] = array(
  'name'     => 'Category 6',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_category_7'] = array(
  'name'     => 'Category 7',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_price_retail_store'] = array(
  'name'     => 'Webstore Price',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_price_googlebase'] = array(
  'name'     => 'Google Base Price',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_price_shopzilla'] = array(
  'name'     => 'Shopzilla Price',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_price_ebay'] = array(
  'name'     => 'Ebay Price',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_Manufacturer'] = array(
  'name'     => 'Manufacturer',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_condition'] = array(
  'name'     => 'Condition',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
  
  $opts['fdd']['mgs_leadtime_to_ship'] = array(
  'name'     => 'Lead Time to Ship',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
/*
$opts['fdd']['mgs_leadtime_to_ship']['default'] = '';
$opts['fdd']['mgs_leadtime_to_ship']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_leadtime_to_ship']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_leadtime_to_ship']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_leadtime_to_ship']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_leadtime_to_ship']['values']['filters'] = 'value_type = "mgs_leadtime_to_ship"'; //matches fields in field_data table
$opts['fdd']['mgs_leadtime_to_ship']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_leadtime_to_ship']['name'] = 'Leadtime to Ship'; //title name in column view
*/
$opts['fdd']['mgs_shipping_address'] = array(
  'name'     => 'Shipping Address',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_shipping_zip'] = array(
  'name'     => 'Shipping Zip Code',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_shipping_state'] = array(
  'name'     => 'Shipping State',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_shipping_country'] = array(
  'name'     => 'Shipping Country',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_taxID'] = array(
  'name'     => 'Tax ID',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_weightUnitOfMeasure'] = array(
  'name'     => 'Weight Unit Of Measure',
  'select'   => 'T',
  'maxlen'   => 2,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_dimensionUnitOfMeasure'] = array(
  'name'     => 'Dimension Unit Of Measure',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_producttaxcode'] = array(
  'name'     => 'Amazon Product TaxCode',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_amazon_registered_parameter'] = array(
  'name'     => 'Amazon Registered Parameter',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['mgs_currency'] = array(
  'name'     => 'Currency',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
/*
$opts['fdd']['mgs_for_sale']['default'] = '';
$opts['fdd']['mgs_for_sale']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['mgs_for_sale']['values']['table']  = 'fixed_values'; //the table name
$opts['fdd']['mgs_for_sale']['values']['column'] = 'value_data'; //this is the value qvailable in pull down
$opts['fdd']['mgs_for_sale']['values']['description'] = 'value_data'; // values recorded in database
$opts['fdd']['mgs_for_sale']['values']['filters'] = 'value_type = "mgs_for_sale"'; //matches fields in field_data table
$opts['fdd']['mgs_for_sale']['values']['orderby'] = 'value_data'; //sorts values by value_data
$opts['fdd']['mgs_for_sale']['name'] = 'Product For Sale'; //title name in column view
*/

/*

$opts['fdd']['sku'] = array(
  'name'     => 'Master MGC Sku',
  'select'   => 'T',
  'maxlen'   => 20,
  
  
  'sort'     => true
);
$opts['fdd']['sku']['values']['filters'] = 'brand like "%hyde%"'; 

$opts['fdd']['price']['values']['db']     = 'merrowco_hydedata'; // optional
$opts['fdd']['price']['values']['table']  = 'prices'; //the table name
$opts['fdd']['price']['values']['column'] = 'price_msrp'; //this is the value qvailable in pull down
$opts['fdd']['price']['values']['description'] = 'price_msrp'; // values recorded in database 
$opts['fdd']['price']['values']['filters'] = ''; 
$opts['fdd']['price']['name'] = 'TEST PRICING'; //title name in column view

$opts['fdd']['mgc_amazon'] = array(
  'name'     => 'MGC Amzn',
  'select'   => 'T',
  'maxlen'   => 20,
  
  'sort'     => true
);



$opts['fdd']['id'] = array(
  'name'     => 'ID',
  'select'   => 'T',
  'maxlen'   => 10,
  'default'  => '0',
  'options' => 'V',
  'sort'     => true
);
$opts['fdd']['supline_sku'] = array(
  'name'     => 'Supline sku',
  'select'   => 'T',
  'maxlen'   => 20,
  
  'sort'     => true
);
$opts['fdd']['superior_suffix'] = array(
  'name'     => 'Superior suffix',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['new_man_sku'] = array(
  'name'     => 'Manufactureres SKU',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['name'] = array(
  'name'     => 'Product Name',
  'select'   => 'T',
  'maxlen'   => 200,
 
  'sort'     => true
);
$opts['fdd']['description'] = array(
  'name'     => 'New description',
  'select'   => 'T',
  'maxlen'   => 65535,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['old_name'] = array(
  'name'     => 'Name',
  'select'   => 'T',
  'maxlen'   => 300,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['old_description'] = array(
  'name'     => 'Description',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['brand'] = array(
  'name'     => 'Brand',
  'select'   => 'T',
  'maxlen'   => 100,
  'sort'     => true
);
$opts['fdd']['trunc_make'] = array(
  'name'     => 'Trunc make',
  'select'   => 'T',
  'maxlen'   => 100,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['make'] = array(
  'name'     => 'Make',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['producer'] = array(
  'name'     => 'Producer',
  'select'   => 'T',
  'maxlen'   => 40,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['trunc_cat'] = array(
  'name'     => 'Trunc cat',
  'select'   => 'T',
  'maxlen'   => 5,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['category'] = array(
  'name'     => 'Category',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['sup_cat'] = array(
  'name'     => 'Sup cat',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['gb_cat'] = array(
  'name'     => 'Gb cat',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['cat_map'] = array(
  'name'     => 'Cat map',
  'select'   => 'T',
  'maxlen'   => 200,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['amazon_icg'] = array(
  'name'     => 'Amazon icg',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['amazon_category'] = array(
  'name'     => 'Amazon category',
  'select'   => 'T',
  'maxlen'   => 50,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['pkg_quantity'] = array(
  'name'     => 'Pkg quantity',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['new_price'] = array(
  'name'     => 'Posted MSRP Price',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
/* $opts['fdd']['price'] = array(
  'name'     => 'Price',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
*/
/*
$opts['fdd']['net'] = array(
  'name'     => 'Net',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['list'] = array(
  'name'     => 'Posted List Price',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['ups_net'] = array(
  'name'     => 'Ups net',
  'select'   => 'T',
  'maxlen'   => 10,
  'sort'     => true
);
$opts['fdd']['ups_list'] = array(
  'name'     => 'Ups list',
  'select'   => 'T',
  'maxlen'   => 10,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['sup_net'] = array(
  'name'     => 'Sup net',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['sup_list'] = array(
  'name'     => 'Sup list',
  'select'   => 'T',
  'maxlen'   => 20,
  'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['image'] = array(
  'name'     => 'Image',
  'select'   => 'T',
  'maxlen'   => 500,
  'sort'     => true
);


$opts['fdd']['man_sku'] = array(
  'name'     => 'Man sku',
  'select'   => 'T',
  'maxlen'   => 20,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['attribute_set'] = array(
  'name'     => 'Attribute set',
  'select'   => 'T',
  'maxlen'   => 50,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['short_description'] = array(
  'name'     => 'Short description',
  'select'   => 'T',
  'maxlen'   => 65535,
  'textarea' => array(
    'rows' => 5,
    'cols' => 50),
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['amazon_product_type'] = array(
  'name'     => 'Amazon product type',
  'select'   => 'T',
  'maxlen'   => 20,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['item_weight_unit_of_measure'] = array(
  'name'     => 'Item weight unit of measure',
  'select'   => 'T',
  'maxlen'   => 2,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['item_weight'] = array(
  'name'     => 'Item weight',
  'select'   => 'T',
  'maxlen'   => 4,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['shipping_weight_unit_of_measure'] = array(
  'name'     => 'Shipping weight unit of measure',
  'select'   => 'T',
  'maxlen'   => 2,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['shipping_weight'] = array(
  'name'     => 'Shipping weight',
  'select'   => 'T',
  'maxlen'   => 4,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['lead_time_to_ship'] = array(
  'name'     => 'Lead time to ship',
  'select'   => 'T',
  'maxlen'   => 2,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['currency'] = array(
  'name'     => 'Currency',
  'select'   => 'T',
  'maxlen'   => 4,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['quantity'] = array(
  'name'     => 'Quantity',
  'select'   => 'T',
  'maxlen'   => 10,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['registered_parameter'] = array(
  'name'     => 'Registered parameter',
  'select'   => 'T',
  'maxlen'   => 30,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['condition'] = array(
  'name'     => 'Condition',
  'select'   => 'T',
  'maxlen'   => 10,
  'default'  => 'new',
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['gb_link'] = array(
  'name'     => 'Gb link',
  'select'   => 'T',
  'maxlen'   => 300,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['payment_type'] = array(
  'name'     => 'Payment type',
  'select'   => 'T',
  'maxlen'   => 100,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['update_delete'] = array(
  'name'     => 'Update delete',
  'select'   => 'T',
  'maxlen'   => 50,
    'options' => 'APC',
  'sort'     => true
);
$opts['fdd']['for_sale'] = array(
  'name'     => 'For sale',
  'select'   => 'T',
  'maxlen'   => 10,
  'default'  => 'YES',
  'sort'     => true
);

*/
					 
					 

// Now important call to phpMyEdit
require_once 'phpMyEdit-mce-cal.class.php';
new phpMyEdit_mce_cal($opts);




?>


</body>
</html>
