<?php
/*
**	@desc:	PHP ajax login form using jQuery
**	@author:	programmer@chazzuka.com
**	@url:		http://www.chazzuka.com/blog
**	@date:	15 August 2008
**	@license:	Free!, but i'll be glad if i my name listed in the credits'
*/

// @ error reporting setting  (  modify as needed )


//@ explicity start session  ( remove if needless )
session_start();

//@ if logoff
if(!empty($_GET['logoff'])) { $_SESSION = array(); }

//@ is authorized?
if(empty($_SESSION['exp_user']) || @$_SESSION['exp_user']['expires'] < time()) {
	header("location:widget_merrow_agent_login.php");	//@ redirect 
} else {
	$_SESSION['exp_user']['expires'] = time()+(3600*60);	//@ renew 45 minutes
}	
?>  
  
  

   
 <?php
if ($_GET['lang']!=null) {
$scrub = $_GET['lang'];  }

$nifty = $_COOKIE["lang"];


if ( $scrub!=null) { 
$lang = $_GET['lang']; }
elseif ($scrub = null) {
$lang = '$nifty'; }
  

if ( $scrub!=null) { 
setcookie("lang", "$scrub", time()+3600);


} else { } ?>


<?php include ("ip_lang_database.php") ?>
   <? 
  
// Get all the data from the "asin" table which is where our product info is kept
$result = mysql_query("SELECT * FROM customer_forms WHERE customer_service_agent='not-assigned'")
or die(mysql_error());
?>


<?
// then define the result array
 $ruju = mysql_fetch_array($result); 
 $num_rows = mysql_num_rows($result);

 
?>

<?php

// then we connect to the database as renter and access table: inventory 
#
mysql_connect("localhost", "merrowco_renter", "7679") or die(mysql_error());

#
mysql_select_db("merrowco_inventory") or die(mysql_error());

?>


<? 

$name = $_SESSION['exp_user']['username'];



//verify login credentials
$result12 = mysql_query("SELECT * FROM login_auth_agent WHERE username='$name'")
or die(mysql_error());

$verify = mysql_fetch_array($result12);

if ($verify['merrow']!=null) {  ?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Textile Plants</title>

<link rel="stylesheet" href="http://css.imerrow.com/css_major/cs_agent_interactive_form.css" type="text/css" charset="utf-8">
<style type="text/css">
<!--
.style1 {
	color: #000000;
	font-weight: bold;
}
-->
</style>

<link rel="stylesheet" type="text/css" media="screen" href="http://css.imerrow.com/css_major/calendar-system.css">

<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar.js"></script>
<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar-en.js"></script>
<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar-setup.js"></script>
 
</head>

<body>

<div class="topbar"></div> <div class="title"> <a href="http://merrow.com/test_maps_1.php">View Map</a> </div>
<div class="mapimage">
<a href="http://merrow.com/test_maps_1.php"><img src="http://images.imerrow.com/images/mapicon.jpg" alt="" name="map" width="30" height="30" /></a></a></div>

<? #
$cranberry = $_COOKIE['merid']; 

mysql_select_db("merrowco_inventory") or die(mysql_error());


if ($whole!=null) {

   // Get all the data from the "asin" table which is where our product info is kept
$result1 = mysql_query("SELECT * FROM agent_word WHERE agent_id='$whole'")
or die(mysql_error()); }

else { 

  // Get all the data from the "asin" table which is where our product info is kept
$result1 = mysql_query("SELECT * FROM agent_word WHERE agent_id='$cranberry'")
or die(mysql_error());

}


// then define juju as the result array
 $tunafish = mysql_fetch_array($result1); 
 $banana = $tunafish['party_id'];
 
 
  // Get all the data from the "asin" table which is where our product info is kept
$result2 = mysql_query("SELECT * FROM agent_revenue WHERE party_id='$banana'")
or die(mysql_error()); 

// then define juju as the result array
 $marlinfish = mysql_fetch_array($result2); 


 if ($_GET['frommap'] == 2) { } else {?>



<div class="welcome">Welcome <? echo $tunafish['name']; ?></div> 





<?php

}

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table
$opts['hn'] = 'localhost';
$opts['un'] = 'merrowco_creeper';
$opts['pw'] = 'merr0w';
$opts['db'] = 'merrowco_rollingthunder';
$opts['tb'] = 'sandbox_management';

// Name of field which is the unique key
$opts['key'] = 'id';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('id');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 15;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'ACPVDF';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'G';
$opts['url'] = array('images' => 'db_images/'); 

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => true,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'] . '-UTF8';

/* Table-level filter capability. If set, it is included in the WHERE clause
   of any generated SELECT statement in SQL query. This gives you ability to
   work only with subset of data from table.

$opts['filters'] = "column1 like '%11%' AND column2<17";
$opts['filters'] = "section_id = 9";
$opts['filters'] = "PMEtable0.sessions_count > 200";
*/

/* Field definitions
   
Fields will be displayed left to right on the screen in the order in which they
appear in generated list. Here are some most used field options documented.

['name'] is the title used for column headings, etc.;
['maxlen'] maximum length to display add/edit/search input boxes
['trimlen'] maximum length of string content to display in row listing
['width'] is an optional display width specification for the column
          e.g.  ['width'] = '100px';
['mask'] a string that is used by sprintf() to format field output
['sort'] true or false; means the users may sort the display on this column
['strip_tags'] true or false; whether to strip tags from content
['nowrap'] true or false; whether this field should get a NOWRAP
['select'] T - text, N - numeric, D - drop-down, M - multiple selection
['options'] optional parameter to control whether a field is displayed
  L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
            Another flags are:
            R - indicates that a field is read only
            W - indicates that a field is a password field
            H - indicates that a field is to be hidden and marked as hidden
['URL'] is used to make a field 'clickable' in the display
        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
['URLtarget']  HTML target link specification (for example: _blank)
['textarea']['rows'] and/or ['textarea']['cols']
  specifies a textarea is to be used to give multi-line input
  e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
['values'] restricts user input to the specified constants,
           e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
['values']['table'] and ['values']['column'] restricts user input
  to the values found in the specified column of another table
['values']['description'] = 'desc_column'
  The optional ['values']['description'] field allows the value(s) displayed
  to the user to be different to those in the ['values']['column'] field.
  This is useful for giving more meaning to column values. Multiple
  descriptions fields are also possible. Check documentation for this.
*/

$opts['fdd']['id'] = array(
  'name'     => 'ID',
  'select'   => 'T',
  'maxlen'   => 11,
  'sort'     => true
);
$opts['fdd']['parent'] = array(
  'name'     => 'Parent',
  'select'   => 'T',
  'maxlen'   => 100,
  'sort'     => true
);
$opts['fdd']['application'] = array(
  'name'     => 'Application',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['left_box1'] = array(
  'name'     => 'Left box1',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['left_box_sub1'] = array(
  'name'     => 'Left box sub1',
  'select'   => 'T',
  'maxlen'   => 20,
  'sort'     => true
);
$opts['fdd']['left_box2'] = array(
  'name'     => 'Left box2',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['left_box3'] = array(
  'name'     => 'Left box3',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['right_box1'] = array(
  'name'     => 'Right box1',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['right_box2'] = array(
  'name'     => 'Right box2',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['right_box3'] = array(
  'name'     => 'Right box3',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['right_box4'] = array(
  'name'     => 'Right box4',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['right_box5'] = array(
  'name'     => 'Right box5',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['center_line1'] = array(
  'name'     => 'Center line1',
  'select'   => 'T',
  'maxlen'   => 100,
  'sort'     => true
);
$opts['fdd']['center_line2'] = array(
  'name'     => 'Center line2',
  'select'   => 'T',
  'maxlen'   => 100,
  'sort'     => true
);
$opts['fdd']['center_line3'] = array(
  'name'     => 'Center line3',
  'select'   => 'T',
  'maxlen'   => 100,
  'sort'     => true
);

// Now important call to phpMyEdit
require_once 'phpMyEdit-mce-cal.class.php';
new phpMyEdit_mce_cal($opts);




 } ?>


</body>
</html>
