<? 



$partyid = $_GET['8787'];
$first = $_GET['33950019334xxlmmnot'];
$last = $_GET['908234klsdfzwe38hna9f7s'];

$whole = $partyid . $first . $last;

if ($whole!=null) {
setcookie("merid", "$whole", time()+3600*60);} 







// then we connect to the database as renter and access table: inventory 
#
mysql_connect("localhost", "merrowco_renter", "7679") or die(mysql_error());

#
mysql_select_db("merrowco_inventory") or die(mysql_error());



   // Get all the data from the "asin" table which is where our product info is kept
$result = mysql_query("SELECT * FROM agent_word WHERE agent_id='$whole'")
or die(mysql_error());


// then define juju as the result array
 $parsnip = mysql_fetch_array($result); 
 

 $thetable = $parsnip['table'];

if ( $thetable!=null) { 
setcookie("keymaster", "$thetable", time()+3600*60);}




if (isset($_COOKIE['keymaster'])) {

$button = $_COOKIE['keymaster']; }

else { $button == $whole; }


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Textile Plants</title>

<link rel="stylesheet" href="http://css.imerrow.com/css_major/cs_global_interactive_form.css" type="text/css" charset="utf-8">
<style type="text/css">
<!--
.style1 {
	color: #000000;
	font-weight: bold;
}
-->
</style>

<link rel="stylesheet" type="text/css" media="screen" href="http://css.imerrow.com/css_major/calendar-system.css">

<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar.js"></script>
<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar-en.js"></script>
<script type="text/javascript" src="http://merrow.com/cephei/scripts/calendar-setup.js"></script>
 
</head>

<body>

<div class="topbar"></div> <div class="title"> <a href="http://merrow.com/test_maps_1.php">View Map</a> </div>
<div class="mapimage">
<a href="http://merrow.com/test_maps_1.php"><img src="http://images.imerrow.com/images/mapicon.jpg" alt="" name="map" width="30" height="30" /></a></a></div>

<? #
$cranberry = $_COOKIE['merid']; 

mysql_select_db("merrowco_inventory") or die(mysql_error());


if ($whole!=null) {

   // Get all the data from the "asin" table which is where our product info is kept
$result1 = mysql_query("SELECT * FROM agent_word WHERE agent_id='$whole'")
or die(mysql_error()); }

else { 

  // Get all the data from the "asin" table which is where our product info is kept
$result1 = mysql_query("SELECT * FROM agent_word WHERE agent_id='$cranberry'")
or die(mysql_error());

}


// then define juju as the result array
 $tunafish = mysql_fetch_array($result1); 
 $banana = $tunafish['party_id'];
 
 
  // Get all the data from the "asin" table which is where our product info is kept
$result2 = mysql_query("SELECT * FROM agent_revenue WHERE party_id='$banana'")
or die(mysql_error()); 

// then define juju as the result array
 $marlinfish = mysql_fetch_array($result2); 


 if ($_GET['frommap'] == 2) { } else {?>



<div class="welcome">Welcome <? echo $tunafish['name']; ?></div> <div class="firstparagraph"><div class="revenue"> Revenue Scoreboard: </div><div class="totals"><span class="style1">2008 =</span> $<? echo $marlinfish['2008']; ?>.00  ||  <span class="style1">2009 =</span> $<? echo $marlinfish['2009']; ?>.00</div> </div>
</div>




<?php

}



/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table
$opts['hn'] = 'localhost';
$opts['un'] = 'merrowco';
$opts['pw'] = 'kingmaker';
$opts['db'] = 'merrowco_inventory';
if ($thetable!=null) {

$opts['tb'] =  $thetable ;}

else { 

$opts['tb'] =  $button ;}

// Name of field which is the unique key
$opts['key'] = 'id';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'string';

// Sorting field(s)
$opts['sort_field'] = array('status');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 12;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'ACDF';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'G';
$opts['url'] = array('images' => 'db_images/'); 

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => true,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'] . '-UTF8';

/* Table-level filter capability. If set, it is included in the WHERE clause
   of any generated SELECT statement in SQL query. This gives you ability to
   work only with subset of data from table.

$opts['filters'] = "column1 like '%11%' AND column2<17";
$opts['filters'] = "section_id = 9";
$opts['filters'] = "PMEtable0.sessions_count > 200";
*/

/* Field definitions
   
Fields will be displayed left to right on the screen in the order in which they
appear in generated list. Here are some most used field options documented.

['name'] is the title used for column headings, etc.;
['maxlen'] maximum length to display add/edit/search input boxes
['trimlen'] maximum length of string content to display in row listing
['width'] is an optional display width specification for the column
          e.g.  ['width'] = '100px';
['mask'] a string that is used by sprintf() to format field output
['sort'] true or false; means the users may sort the display on this column
['strip_tags'] true or false; whether to strip tags from content
['nowrap'] true or false; whether this field should get a NOWRAP
['select'] T - text, N - numeric, D - drop-down, M - multiple selection
['options'] optional parameter to control whether a field is displayed
  L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
            Another flags are:
            R - indicates that a field is read only
            W - indicates that a field is a password field
            H - indicates that a field is to be hidden and marked as hidden
['URL'] is used to make a field 'clickable' in the display
        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
['URLtarget']  HTML target link specification (for example: _blank)
['textarea']['rows'] and/or ['textarea']['cols']
  specifies a textarea is to be used to give multi-line input
  e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
['values'] restricts user input to the specified constants,
           e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
['values']['table'] and ['values']['column'] restricts user input
  to the values found in the specified column of another table
['values']['description'] = 'desc_column'
  The optional ['values']['description'] field allows the value(s) displayed
  to the user to be different to those in the ['values']['column'] field.
  This is useful for giving more meaning to column values. Multiple
  descriptions fields are also possible. Check documentation for this.
*/

$opts['cgi']['append']['PME_sys_fl'] = 1;


$opts['fdd']['id'] = array(
  'name'     => 'ID',
  'select'   => 'T',
  'maxlen'   => 4,
  'default'  => '0',
   'options' => 'V',
  'sort'     => true
);
$opts['fdd']['name'] = array(
		'name'    => 'Account Name',
		 'select'   => 'T',
		 'maxlen'   => 200,
		 'URL'     => 'http://merrow.com/textile_plants.php?PME_sys_fl=1&PME_sys_fm=0&PME_sys_operation=PME_op_Change&PME_sys_qf6_id=yes&PME_sys_rec=$key',
  		 'sort'     => true
);

$opts['fdd']['store'] = array(
  'name'     => 'Store',
  'select'   => 'T',
  'maxlen'   => 3,
   'options' => 'V',
  'sort'     => true
);
$opts['fdd']['date_contacted'] = array(
 'name'     => 'Last Date Contacted',
 'select'   => 'T',
 'options'  => 'ACPVD',
 'required' => true,
 'calendar' => array(
   'ifFormat'    => '%Y/%m/%d', // defaults to the ['strftimemask']
   'firstDay'    => 1,          // 0 = Sunday, 1 = Monday
   'singleClick' => true,       // single or double click to close
   'weekNumbers' => true,       // Show week numbers
   'showsTime'   => false,      // Show time as well as date
   'timeFormat'  => '24',       // 12 or 24 hour clock
   'label'       => 'choose date',      // button label (used by phpMyEdit)
   'date'        => '2009-12-19 10:00' // Initial date/time for popup
                                       // (see notes below)
 )
);
$opts['fdd']['short_notes'] = array(
  'name'     => 'Short Notes',
  'select'   => 'T',
  'maxlen'   => 500,
 'trimlen'   => '35',
   'sort'     => true
);
$opts['fdd']['short_notes']['textarea']['rows'] = 8;
$opts['fdd']['short_notes']['textarea']['cols'] = 70;

$opts['fdd']['long_notes'] = array(
  'name'     => 'Account Description',
  'select'   => 'T',
  'maxlen'   => 500,
 'trimlen'   => '350',
  'options' => 'VAC',
 'sort'     => true
);
$opts['fdd']['long_notes']['textarea']['rows'] = 8;
$opts['fdd']['long_notes']['textarea']['cols'] = 70;


$opts['fdd']['account_type'] = array(
  'name'     => 'Account Type',
  'select'   => 'T',
  'maxlen'   => 3,
   'options' => 'V',
  'sort'     => true
);
$opts['fdd']['store_db_name'] = array(
  'name'     => 'Store db name',
  'select'   => 'T',
  'maxlen'   => 30,
   'options' => 'V',
  'sort'     => true
);
$opts['fdd']['show_map'] = array(
  'name'     => 'Show map',
  'select'   => 'T',
  'maxlen'   => 5,
   'options' => 'V',
  'sort'     => true

);
/** $opts['fdd']['date_contacted'] = array(
  'name'     => 'Date Contacted',
  'help'     => 'Format is YYYY-MM-DD',
  'select'   => 'T',
  'maxlen'   => 10,
  'datemask' => 'Y-m-d',
  'sort'     => true
); 
$opts['fdd']['date_contacted']['js']['required'] = true;
$opts['fdd']['date_contacted']['js']['regexp'] = '/^[1-2]{1}[0-9]{3}-[0-1]{1}[0-9]{1}-[0-3]{1}[0-9]{1}$/';
$opts['fdd']['date_contacted']['js']['hint'] = 'An entry is required for the contact Date YYYY-MM-DD';

*/ 

/** $opts['fdd']['join_fabric'] = array(
  'name'     => 'End to End Seaming',
  'select'   => 'D',
  'maxlen'   => 5,
   'options' => 'AFCV',
      'values'   => array('yes','no'),
  'sort'     => true

);
*/


$opts['fdd']['party_id'] = array(
  'name'     => 'Party ID',
  'select'   => 'T',
  'maxlen'   => 200,
     'options' => 'V',
  'sort'     => true
);


 
$opts['fdd']['contact_name'] = array(
  'name'     => 'Contact Name',
  'select'   => 'T',
  'maxlen'   => 200,
  'URL'     => 'http://merrow.com/textile_plants.php?PME_sys_fl=1&PME_sys_fm=0&PME_sys_operation=PME_op_Change&PME_sys_qf6_id=yes&PME_sys_rec=$key',
   'options' => 'ACFV',
  'sort'     => true
);
$opts['fdd']['address'] = array(
  'name'     => 'Address',
  'select'   => 'T',
  'maxlen'   => 200,
   'options' => 'AV',
  'sort'     => true
);
$opts['fdd']['city'] = array(
  'name'     => 'City',
  'select'   => 'T',
  'maxlen'   => 200,
   'options' => 'AFVC',
  'sort'     => true
);
$opts['fdd']['state'] = array(
  'name'     => 'State',
  'select'   => 'T',
  'maxlen'   => 200,
     'options' => 'AFVC',
  'sort'     => true
);
$opts['fdd']['zip'] = array(
  'name'     => 'Zip',
  'select'   => 'T',
  'maxlen'   => 200,
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['Country'] = array(
  'name'     => 'Country',
  'select'   => 'T',
  'maxlen'   => 200,
     'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['email'] = array(
  'name'     => 'Email',
  'select'   => 'T',
  'URL'      => 'mailto:$value',
  'maxlen'   => 200,
    'options' => 'AFVC',
  'sort'     => true
);
$opts['fdd']['phone'] = array(
  'name'     => 'Phone',
  'select'   => 'T',
  'maxlen'   => 40,
    'options' => 'AFVC',
  'sort'     => true
);
$opts['fdd']['fax'] = array(
  'name'     => 'Fax',
  'select'   => 'T',
  'maxlen'   => 40,
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['lat'] = array(
  'name'     => 'Latitude',
  'select'   => 'T',
  'maxlen'   => 30,
     'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['lng'] = array(
  'name'     => 'Longitude',
  'select'   => 'T',
  'maxlen'   => 30,
     'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['address'] = array(
  'name'     => 'Full address',
  'select'   => 'T',
  'maxlen'   => 200,
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['content_key1'] = array(
  'name'     => 'Content key1',
  'select'   => 'T',
  'maxlen'   => 200,
   'options' => 'V',
  'sort'     => true
);
$opts['fdd']['content_key2'] = array(
  'name'     => 'Content key2',
  'select'   => 'T',
  'maxlen'   => 200,
   'options' => 'V',
  'sort'     => true
);


$opts['fdd']['source'] = array(
  'name'     => 'Source',
  'select'   => 'D',
  'maxlen'   => 30,
   'values'   => array('OT','Agent','Web','Customer Forms'),
    'options' => 'CAV',
  'sort'     => true
 

);

$opts['fdd']['rails'] = array(
  'name'     => 'How many Railways do they have',
  'select'   => 'T',
  'maxlen'   => 3,
    'values'   => array('0','1-5','6-10','11-20','21-50','50+'),
   'options' => 'AC',
  'sort'     => true
);

$opts['fdd']['other_brands1'] = array(
  'name'     => 'Other Brands 1',
  'select'   => 'T',
  'maxlen'   => 3,
   'values'   => array('none','Pegasus', 'Juki', 'Siruba', 'Yamata', 'Union Special', 'REVO', 'GURU', 'Elcu', 'Metalplast', 'Liberty', 'Inderle'),
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['other_brands2'] = array(
  'name'     => 'Other Brands 2',
  'select'   => 'T',
  'maxlen'   => 3,
    'values'   => array('none','Pegasus', 'Juki', 'Siruba', 'Yamata', 'Union Special', 'REVO', 'GURU', 'Elcu', 'Metalplast', 'Liberty', 'Inderle'),
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['other_brands3'] = array(
  'name'     => 'Other Brands 3',
  'select'   => 'T',
  'maxlen'   => 3,
   'values'   => array('none','Pegasus', 'Juki', 'Siruba', 'Yamata', 'Union Special', 'REVO', 'GURU', 'Elcu', 'Metalplast', 'Liberty', 'Inderle'),
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['comp_machines'] = array(
  'name'     => 'Other Brands (not in list)',
  'select'   => 'T',
  'maxlen'   => 200,
   'options' => 'C',
  'sort'     => true
);
$opts['fdd']['total_machines'] = array(
  'name'     => 'Total Number of All types of Sewing Machines',
  'select'   => 'T',
  'maxlen'   => 3,
   'values'   => array('1-5','6-10','11-20','21-50','50+'),
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['number_of_machines'] = array(
  'name'     => 'Number of Merrow Machines',
  'select'   => 'D',
  'maxlen'   => 5,
   'options' => 'AVC',
      'values'   => array('1-5','6-10','11-20','21-50','50+'),
  'sort'     => true
);
$opts['fdd']['processes'] = array(
  'name'     => 'Other Sewing Processes',
  'select'   => 'T',
  'maxlen'   => 3,
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['square_footage'] = array(
  'name'     => 'Square Footage of Facility',
   'values'   => array('100sq Meters','1000sq Meters','5000sq Meters','10000sq Meters','10000+sq Meters'),
  'select'   => 'T',
  'maxlen'   => 3,
   'options' => 'AC',
  'sort'     => true
);

$opts['fdd']['years'] = array(
  'name'     => 'Years in business',
  'select'   => 'T',
  'maxlen'   => 3,
   'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['join_mailing'] = array(
  'name'     => 'Join Mailing List',
  'select'   => 'D',
  'maxlen'   => 5,
   'options' => 'VAC',
      'values'   => array('yes','no'),
  'sort'     => true

);
$opts['fdd']['aa70'] = array(
  'name'     => '70 Class Machines',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['aa70_model'] = array(
  'name'     => '70 Model',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['mg'] = array(
  'name'     => 'MG Class Machines',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['mg_model'] = array(
  'name'     => 'MG Model',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['crochet'] = array(
  'name'     => 'Crochet Class Machines',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);
$opts['fdd']['crochet_model'] = array(
  'name'     => 'crochet Model',
  'select'   => 'T',
  'maxlen'   => 30,
  'sort'     => true
);
$opts['fdd']['other'] = array(
  'name'     => 'other Class Machines',
  'select'   => 'T',
  'maxlen'   => 3,
    'options' => 'AC',
  'sort'     => true
);
$opts['fdd']['discount'] = array(
  'name'     => 'discount',
  'select'   => 'T',
  'maxlen'   => 3,
  'sort'     => true
);


// Now important call to phpMyEdit
require_once 'phpMyEdit-mce-cal.class.php';
new phpMyEdit_mce_cal($opts);




?>


</body>
</html>
