<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
		"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	
 <link rel="stylesheet" href="http://css.imerrow.com/css_major/agent_interactive_form.css" type="text/css" charset="utf-8">
 <title>enterprise database</title>
 </head>
 <style>
 input.pme-add {
			color: black;
	font-weight: bold;
	font-size: 14px;
	background-color: orange;
	position: relative;
	top: 10px;
	left: 60px;
	visibility: visible;
}
	table.pme-main 	     { border-collapse: collapse; border-spacing: 0px; width: 960px;
	margin-top: 20px;
	border-width: 1px;
	border-color: #004d9c;
}
input.pme-next {
		position: relative;
	visibility: visible;
	left: 60px;
}
input.pme-last {
		position: relative;
	visibility: visible;
	left: 60px;
}
input.pme-first {
			position: relative;
	visibility: visible;
}
input.pme-prev {
			position: relative;
	visibility: visible;
}

input.pme-goto {
			position: relative;
	visibility: visible;
		left: 60px;
}

select.pme-goto {
		position: relative;
	visibility: visible;
		left: 60px;
}
input.pme-view {
		position: relative;
	visibility: visible;
		right: 50px;
}
</style>

</head>
<body>
<h3>merrow enterprise accounts</h3>
<div class="list_top">
  <div class="spacer"> <a href="http://merrow.com/widget_enterprise_targetsdb.php" target="mammy">Enterprise Targets</a> </div>
      <div class="spacer"> <a href="http://merrow.com/widget_enterprise_machinesdb.php" target="mammy">Machines by Facility</a> </div>
      <div class="spacer">   <a href="http://merrow.com/widget_enterprise_namesdb.php" target="mammy">Contacts by Facility</a> </div>
      <div class="spacer">    <a href="http://merrow.com/widget_enterprise_fabricdb.php" target="mammy">Fabrics by Faciltity</a> </div>
       <div class="spacer">   <a href="http://merrow.com/widget_enterprise_applicationdb.php" target="mammy">Applications  by Faciltity</a> </div>
         </div><div class="stop_the_bleed"></div>
<?php

/*
 * IMPORTANT NOTE: This generated file contains only a subset of huge amount
 * of options that can be used with phpMyEdit. To get information about all
 * features offered by phpMyEdit, check official documentation. It is available
 * online and also for download on phpMyEdit project management page:
 *
 * http://platon.sk/projects/main_page.php?project_id=5
 *
 * This file was generated by:
 *
 *                    phpMyEdit version: 5.7.1
 *       phpMyEdit.class.php core class: 1.204
 *            phpMyEditSetup.php script: 1.50
 *              generating setup script: 1.50
 */

// MySQL host name, user name, password, database, and table
$opts['hn'] = 'localhost';
$opts['un'] = 'merrowco_mailman';
$opts['pw'] = '7679';
$opts['db'] = 'merrowco_cephei';
$opts['tb'] = 'enterprise';

// Name of field which is the unique key
$opts['key'] = 'id';

// Type of key field (int/real/string/date etc.)
$opts['key_type'] = 'int';

// Sorting field(s)
$opts['sort_field'] = array('id');

// Number of records to display on the screen
// Value of -1 lists all records in a table
$opts['inc'] = 15;

// Options you wish to give the users
// A - add,  C - change, P - copy, V - view, D - delete,
// F - filter, I - initial sort suppressed
$opts['options'] = 'ACPVDF';

// Number of lines to display on multiple selection filters
$opts['multiple'] = '4';

// Navigation style: B - buttons (default), T - text links, G - graphic links
// Buttons position: U - up, D - down (default)
$opts['navigation'] = 'DB';

// Display special page elements
$opts['display'] = array(
	'form'  => true,
	'query' => true,
	'sort'  => true,
	'time'  => true,
	'tabs'  => true
);

// Set default prefixes for variables
$opts['js']['prefix']               = 'PME_js_';
$opts['dhtml']['prefix']            = 'PME_dhtml_';
$opts['cgi']['prefix']['operation'] = 'PME_op_';
$opts['cgi']['prefix']['sys']       = 'PME_sys_';
$opts['cgi']['prefix']['data']      = 'PME_data_';

/* Get the user's default language and use it if possible or you can
   specify particular one you want to use. Refer to official documentation
   for list of available languages. */
$opts['language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'] . '-UTF8';

/* Table-level filter capability. If set, it is included in the WHERE clause
   of any generated SELECT statement in SQL query. This gives you ability to
   work only with subset of data from table.

$opts['filters'] = "column1 like '%11%' AND column2<17";
$opts['filters'] = "section_id = 9";
$opts['filters'] = "PMEtable0.sessions_count > 200";
*/

/* Field definitions
   
Fields will be displayed left to right on the screen in the order in which they
appear in generated list. Here are some most used field options documented.

['name'] is the title used for column headings, etc.;
['maxlen'] maximum length to display add/edit/search input boxes
['trimlen'] maximum length of string content to display in row listing
['width'] is an optional display width specification for the column
          e.g.  ['width'] = '100px';
['mask'] a string that is used by sprintf() to format field output
['sort'] true or false; means the users may sort the display on this column
['strip_tags'] true or false; whether to strip tags from content
['nowrap'] true or false; whether this field should get a NOWRAP
['select'] T - text, N - numeric, D - drop-down, M - multiple selection
['options'] optional parameter to control whether a field is displayed
  L - list, F - filter, A - add, C - change, P - copy, D - delete, V - view
            Another flags are:
            R - indicates that a field is read only
            W - indicates that a field is a password field
            H - indicates that a field is to be hidden and marked as hidden
['URL'] is used to make a field 'clickable' in the display
        e.g.: 'mailto:$value', 'http://$value' or '$page?stuff';
['URLtarget']  HTML target link specification (for example: _blank)
['textarea']['rows'] and/or ['textarea']['cols']
  specifies a textarea is to be used to give multi-line input
  e.g. ['textarea']['rows'] = 5; ['textarea']['cols'] = 10
['values'] restricts user input to the specified constants,
           e.g. ['values'] = array('A','B','C') or ['values'] = range(1,99)
['values']['table'] and ['values']['column'] restricts user input
  to the values found in the specified column of another table
['values']['description'] = 'desc_column'
  The optional ['values']['description'] field allows the value(s) displayed
  to the user to be different to those in the ['values']['column'] field.
  This is useful for giving more meaning to column values. Multiple
  descriptions fields are also possible. Check documentation for this.
*/

$opts['fdd']['id'] = array(
  'name'     => 'ID',
  'select'   => 'T',
  'options'  => 'AVCPDR', // auto increment
  'maxlen'   => 200,
  'default'  => '0',
  'sort'     => true
);
$opts['fdd']['ot_id'] = array(
  'name'     => 'Party ID',
  'select'   => 'T',
  'maxlen'   => 10,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);

$opts['fdd']['corporate_name'] = array(
  'name'     => 'Corporate name',
  'select'   => 'T',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['branch_name'] = array(
  'name'     => 'Branch name',
  'select'   => 'T',
  'maxlen'   => 200,
  'sort'     => true
);

$opts['fdd']['plant_manager'] = array(
  'name'     => 'Plant manager',
  'select'   => 'T',
'options'  => 'CLAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['technician1'] = array(
  'name'     => 'Technician1',
  'select'   => 'T',
'options'  => 'CLAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['technician_ot1'] = array(
  'name'     => 'Technician1 ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['technician2'] = array(
  'name'     => 'Technician2',
  'select'   => 'T',
'options'  => 'CAVL',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['technician_ot2'] = array(
  'name'     => 'Technician2 ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['technician3'] = array(
  'name'     => 'Technician3',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['technician_ot3'] = array(
  'name'     => 'Technician3 ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['technician4'] = array(
  'name'     => 'Technician4',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['technician_ot4'] = array(
  'name'     => 'Technician4 ID',
  'select'   => 'T',
'options'  => 'CAV',
'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['technician5'] = array(
  'name'     => 'Technician5',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['technician_ot5'] = array(
  'name'     => 'Technician5 ID',
  'select'   => 'T',
'options'  => 'CLAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name4'] = array(
  'name'     => 'Other employees name4',
  'select'   => 'T',
'options'  => 'CAVL',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name_ot4'] = array(
  'name'     => 'Other Employee 4 OT_ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['other_employees_position4'] = array(
  'name'     => 'Other employees position4',
  'select'   => 'T',
'options'  => 'CAVL',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name5'] = array(
  'name'     => 'Other employees name5',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name_ot5'] = array(
  'name'     => 'Other Employee 5 OT_ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['other_employees_position5'] = array(
  'name'     => 'Other employees position5',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name6'] = array(
  'name'     => 'Other employees name6',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name_ot6'] = array(
  'name'     => 'Other Employee 6 OT_ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['other_employees_position6'] = array(
  'name'     => 'Other employees position6',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);

$opts['fdd']['other_employees_name7'] = array(
  'name'     => 'Other employees name7',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name_ot7'] = array(
  'name'     => 'Other Employee 7 OT_ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['other_employees_position7'] = array(
  'name'     => 'Other employees position7',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name8'] = array(
  'name'     => 'Other employees name8',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['other_employees_name_ot8'] = array(
  'name'     => 'Other Employee 8 OT_ID',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'URL'      => 'https://192.168.2.105:8443/crmsfa/control/viewAccount?partyId=$value',
  'sort'     => true
);
$opts['fdd']['other_employees_position8'] = array(
  'name'     => 'Other employees position8',
  'select'   => 'T',
'options'  => 'CAV',
  'maxlen'   => 200,
  'sort'     => true
);
$opts['fdd']['issues'] = array(
  'name'     => 'Issues',
  'select'   => 'T',
'options'  => 'CLAV',
  'maxlen'   => 200,
  'sort'     => true
);

$opts['fdd']['merrow_csr'] = array(
  'name'     => 'Merrow csr',
  'select'   => 'T',
'options'  => 'CAVL',
  'maxlen'   => 200,
  'sort'     => true
);

// Now important call to phpMyEdit
require_once 'phpMyEdit.class.php';
new phpMyEdit($opts);

?>


</body>
</html>
