<?php
/***************************************************************************
								slogic_language.inc
							---------------------------
			created				: 04.01.2003
			edited				: 03.07.2003
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of slogic module

// start of main mavigation
$slogic_language['SLOGIC_MENU']		= 'Main Menu';
$slogic_language['SLOGIC_MAIN'] 	= 'Main';
$slogic_language['SLOGIC_LOGOUT'] 	= 'Logout';
$slogic_language['SLOGIC_PROFILE'] 	= 'Edit Profile';
// end of main mavigation

// start of functions

// start of slogic_select_language.php
$slogic_language['SLOGIC_SELECT_LANGUAGE'] 	= 'Set language';
// end of slogic_select_language.php

// start of slogic_profile.php
$slogic_language['SLOGIC_PROFILE_SUBMIT'] 	= 'Save Profile';
$slogic_language['SLOGIC_RESET'] 			= 'Reset';
$slogic_language['SLOGIC_PASSWORD_MISMATCH']	= 'Your passwords don\'t match!';
$slogic_language['SLOGIC_PROFILE_UPDATED']	= 'Your profile was successfully updated!';
// end of slogic_profile.php

// start of slogic_list_announcements.php
$slogic_language['SLOGIC_ANNOUNCEMENTS']	= 'Announcements';
$slogic_language['SLOGIC_ANNOUNCEMENT']		= 'Announcement';
$slogic_language['SLOGIC_NO_ANNOUNCEMENTS'] = '<i>No announcements available.</i>';
// end of slogic_list_announcements.php

// start of slogic_show_announcement.php
$slogic_language['SLOGIC_WRONG_ANNOUNCEMENT'] 	= 'You are not allowed to view this announcement!';
$slogic_language['SLOGIC_INVALID_ANNOUNCEMENT'] = 'You selected an invalid announcement.';
// end of slogic_show_announcement.php

// end of functions

// *************************************************************** \\

// start of templates

// start of templates - pages
// start of slogic_login.tpl
$slogic_language['SLOGIC_LOGIN_TITLE'] = 'Support Logic - Login Page';
// end of slogic_login.tpl

// start of slogic_logout.tpl
$slogic_language['SLOGIC_LOGOUT_TITLE'] = 'Support Logic - Logout Page';
// end of slogic_logout.tpl

// start of slogic_register.tpl
$slogic_language['SLOGIC_REGISTER_TITLE'] = 'Support Logic - Account Registration Page';
// end of slogic_register.tpl

// start of slogic_lost_password.tpl
$slogic_language['SLOGIC_LOST_PASSWORD_TITLE'] = 'Support Logic - Lost Password Page';
// end of slogic_lost_password.tpl

// start of slogic_main.tpl
$slogic_language['SLOGIC_MAIN_TITLE'] = 'Support Logic - Main Page';
// end of slogic_main.tpl

// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_TITLE'] = 'Support Logic - Your Profile';
// end of slogic_profile.tpl

// start of slogic_redirect.tpl
$slogic_language['SLOGIC_REDIRECT_TITLE'] 	= 'Support Logic - Redirect Page';
$slogic_language['SLOGIC_REDIRECT_TOPIC'] 	= 'Please wait...';
$slogic_language['SLOGIC_REDIRECT_URL'] 	= 'Please click here if your browser doesn\'t support automatic redirection.';
// end of slogic_redirect.tpl

// start of slogic_show_announcement.tpl
$slogic_language['SLOGIC_SHOW_ANNOUNCEMENT_TITLE'] = 'Support Logic - Announcement';
// end of slogic_show_announcement.tpl
// end of templates - pages

// start of templates - functions
// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_PASSWORD_INFO'] 	= 'Password changes will work next time you try to login.';
$slogic_language['SLOGIC_PROFILE_PASSWORD'] 	 	= 'Password';
$slogic_language['SLOGIC_PROFILE_PASSWORD_2'] 		= 'Re-enter Password';
$slogic_language['SLOGIC_PROFILE_EMAIL'] 			= 'Email';
$slogic_language['SLOGIC_PROFILE_DOMAIN'] 			= 'Domain';
$slogic_language['SLOGIC_PROFILE_SERVER'] 			= 'Server';
$slogic_language['SLOGIC_PROFILE_ACT_USERNAME'] 	= 'Account username';
$slogic_language['SLOGIC_PROFILE_LANGUAGE']			= 'Preset Language';
$slogic_language['SLOGIC_PROFILE_NOTIFICATION'] 	= 'Notify me by email';
// end of slogic_profile.tpl
// end of templates - functions

// end of templates
?>