<?php
/***************************************************************************
								modules_language.inc
							----------------------------
			created				: 11.04.2003
			edited				: -
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of modules module

// start of main mavigation
$modules_language['MODULES_MENU'] = 'Module Menu';
$modules_language['MODULES_LIST_MODULES'] = 'Module anzeigen';
// end of main mavigation

// start of order titles
// end of order titles

// start of functions

// end of functions

// start of templates - pages
// start of modules_list_modules.tpl
$modules_language['MODULES_LIST_MODULES_TITLE'] = 'Support Logic - Module anzeigen';
// end of modules_list_modules.tpl

// end of templates - pages

// start of templates - functions
$modules_language['MODULES_LIST_ADMIN'] = 'Vorhandene Admin-Module';
$modules_language['MODULES_LIST_STAFF'] = 'Vorhandene Mitarbeiter-Module';
$modules_language['MODULES_LIST_USER'] = 'Vorhandene Benutzer-Module';
$modules_language['MODULES_NAMES'] = 'Modulname:';
$modules_language['MODULES_NO_FUNCTIONS'] = 'No. an vorhandenen Funktionen';
// end of templates - functions
?>