<?php
/***************************************************************************
								search_language.inc
							---------------------------
			created				: 13.02.2003
			edited				: -
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of search module

// start of main mavigation
$search_language['SEARCH_MENU']		= 'Suche Menu';
$search_language['SEARCH_TICKETS'] 	= 'Tickets durchsuchen';
$search_language['SEARCH_USERS'] 	= 'Benutzer suchen';
// end of main mavigation

// start of functions

// start of seach_tickets.php
$search_language['SEARCH_REDIRECT'] = 'Bitte haben Sie einen Moment Geduld.<br>Ihre Suche wird bearbeitet und Sie werden automatisch weitergeleitet.';
$search_language['SEARCH_TICKETS_RESULTS'] = 'Suchergebnisse in Tickets:';
$search_language['SEARCH_NOTES_RESULTS'] = 'Suchergebnisse in Notizen:';
// end of seach_tickets.php

// start of seach_users.php
$search_language['SEARCH_USERS_RESULTS'] = 'Gefundene Benutzer:';
// end of seach_users.php

// end of functions

// *************************************************************** \\

// start of templates

// start of templates - pages
// start of search_tickets.tpl
$search_language['SEARCH_TICKETS_TITLE'] = 'Support Logic - Tickets dursuchen';
// end of slogic_tickets.tpl

// start of search_users.tpl
$search_language['SEARCH_USERS_TITLE'] = 'Support Logic - Benutzer suchen';
// end of slogic_users.tpl

// end of templates - pages

// start of templates - functions
// start of search_tickets.tpl
$search_language['SEARCH_FOR'] 			= 'Suchen nach:';
$search_language['SEARCH_IN'] 			= 'Suchen in:';
$search_language['SEARCH_IN_TICKETS'] 	= 'Tickets durchsuchen';
$search_language['SEARCH_IN_NOTES'] 	= 'Notizen durchsuchen';
$search_language['SEARCH_SUBMIT'] 		= 'Suche!';
// end of search_tickets.tpl
// end of templates - functions

// end of templates
?>