<?php
/***************************************************************************
								slogic_language.inc
							---------------------------
			created				: 04.01.2003
			edited				: 11.07.2003
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of slogic module

// start of main mavigation
$slogic_language['SLOGIC_MENU']		= 'Main Menu';
$slogic_language['SLOGIC_MAIN'] 	= 'Main';
$slogic_language['SLOGIC_LOGOUT'] 	= 'Logout';
$slogic_language['SLOGIC_PROFILE'] 	= 'Edit Profile';
$slogic_language['SLOGIC_LIST_QUICK_REPLIES'] = 'Quick Replies';
// end of main mavigation

// start of list fields
$slogic_language['SLOGIC_USERNAME'] = 'User';
$slogic_language['SLOGIC_INFO'] = 'Info';
$slogic_language['SLOGIC_MESSAGE'] = 'Note';
$slogic_language['SLOGIC_EDIT'] = 'Edit';
$slogic_language['SLOGIC_DELETE'] = 'Delete';
$slogic_language['SLOGIC_ALL'] = 'all';
$slogic_language['SLOGIC_SUBMIT'] = 'Send';
//end of list fields

// start of functions

// start of slogic_select_language.php
$slogic_language['SLOGIC_SELECT_LANGUAGE'] 	= 'Set language';
// end of slogic_select_language.php

// start of slogic_profile.php
$slogic_language['SLOGIC_PROFILE_SUBMIT'] 	= 'Save Profile';
$slogic_language['SLOGIC_RESET'] 			= 'Reset';
$slogic_language['SLOGIC_PASSWORD_MISMATCH']	= 'Your passwords don\'t match!';
$slogic_language['SLOGIC_PROFILE_UPDATED']	= 'Your profile was successfully updated!';
// end of slogic_profile.php

// start of slogic_show_user_profile.php
$slogic_language['SLOGIC_SHOW_USER_PROFILE_NONE']   = 'Username Unknown.';
$slogic_language['SLOGIC_SHOW_USER_PROFILE']		= 'View User Profile';
$slogic_language['SLOGIC_SHOW_USER_PROFILE_OF']		= 'Profile of User:';
$slogic_language['SLOGIC_EMAIL'] 					= 'Email:';
$slogic_language['SLOGIC_DOMAIN']					= 'Domain:';
$slogic_language['SLOGIC_ACT_SERVER']				= 'Server:';
$slogic_language['SLOGIC_ACT_USERNAME']				= 'Server Username:';
$slogic_language['SLOGIC_GET_EMAIL']				= 'Receives Emails:';
$slogic_language['SLOGIC_LANGUAGE']					= 'Preset Language:';
// end of slogic_show_user_profile.php

// start of slogic_list_announcements.php
$slogic_language['SLOGIC_ANNOUNCEMENTS']	= 'Announcements';
$slogic_language['SLOGIC_ANNOUNCEMENT']		= 'Announcement';
$slogic_language['SLOGIC_NO_ANNOUNCEMENTS'] = '<i>No announcements available.</i>';
// end of slogic_list_announcements.php

// start of slogic_show_announcement.php
$slogic_language['SLOGIC_WRONG_ANNOUNCEMENT'] 	= 'You are not allowed to view this announcement!';
$slogic_language['SLOGIC_INVALID_ANNOUNCEMENT'] = 'You selected an invalid announcement.';
// end of slogic_show_announcement.php

// start of slogic_edit_quick_reply.php
$slogic_language['SLOGIC_QUICK_REPLY_EDITED'] 	= 'Quick reply edited.';
$slogic_language['SLOGIC_QUICK_REPLY_EDITED_INVALID'] = 'Invalid action.';
// end of slogic_edit_quick_reply.php

// end of functions

// *************************************************************** \\

// start of templates

// start of templates - pages
// start of slogic_login.tpl
$slogic_language['SLOGIC_LOGIN_TITLE'] = 'Support Logic - Login Page';
// end of slogic_login.tpl

// start of slogic_logout.tpl
$slogic_language['SLOGIC_LOGOUT_TITLE'] = 'Support Logic - Logout Page';
// end of slogic_logout.tpl

// start of slogic_main.tpl
$slogic_language['SLOGIC_MAIN_TITLE'] = 'Support Logic - Main Page';
// end of slogic_main.tpl

// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_TITLE'] = 'Support Logic - Your Profile';
// end of slogic_profile.tpl

// start of slogic_show_user_profile.tpl
$slogic_language['SLOGIC_SHOW_USER_PROFILE_TITLE'] = 'Support Logic - View User Profile';
// end of slogic_show_user_profile.tpl

// start of slogic_redirect.tpl
$slogic_language['SLOGIC_REDIRECT_TITLE'] 	= 'Support Logic - Redirect Page';
$slogic_language['SLOGIC_REDIRECT_TOPIC'] 	= 'Please wait...';
$slogic_language['SLOGIC_REDIRECT_URL'] 	= 'Please click here if your browser doesn\'t support automatic redirection.';
// end of slogic_redirect.tpl

// start of slogic_show_announcement.tpl
$slogic_language['SLOGIC_SHOW_ANNOUNCEMENT_TITLE'] = 'Support Logic - Announcement';
// end of slogic_show_announcement.tpl

// start of slogic_list_quick_replies.tpl
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_TITLE'] = 'Support Logic - Quick Replies';
// end of slogic_list_quick_replies.tpl

// start of slogic_edit_quick_reply.tpl
$slogic_language['SLOGIC_EDIT_QUICK_REPLY_TITLE'] = 'Support Logic - Edit Quick Reply';
// end of slogic_edit_quick_reply.tpl

// end of templates - pages

// start of templates - functions
// start of slogic_profile.tpl
$slogic_language['SLOGIC_PROFILE_PASSWORD_INFO'] 	= 'Password changes will take effect next time you try to login.';
$slogic_language['SLOGIC_PROFILE_PASSWORD'] 	 	= 'Password';
$slogic_language['SLOGIC_PROFILE_PASSWORD_2'] 		= 'Re-enter Password';
$slogic_language['SLOGIC_PROFILE_EMAIL'] 			= 'Email';
$slogic_language['SLOGIC_PROFILE_SIGNATURE']		= 'Signature';
$slogic_language['SLOGIC_PROFILE_DOMAIN'] 			= 'Domain';
$slogic_language['SLOGIC_PROFILE_SERVER'] 			= 'Server';
$slogic_language['SLOGIC_PROFILE_ACT_USERNAME'] 	= 'Account username';
$slogic_language['SLOGIC_PROFILE_LANGUAGE']			= 'Preset Language';
$slogic_language['SLOGIC_PROFILE_NOTIFICATION'] 	= 'Notify me by email';
$slogic_language['SLOGIC_PROFILE_SUBSCRIBE'] 		= 'Select categories to subscribe to';
// end of slogic_profile.tpl

// start of slogic_list_quick_replies.tpl
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_NO_REPLIES'] = '<i>No quick replies created so far.</i>';
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_DELETE_ALL'] = 'Delete all';
$slogic_language['SLOGIC_LIST_QUICK_REPLIES_DELETED'] = 'Quick reply(s) deleted.';
// end of slogic_list_quick_replies.tpl

// start of slogic_edit_quick_reply.tpl
$slogic_language['SLOGIC_EDIT_QUICK_REPLY'] = 'Edit quick reply';
// end of slogic_edit_quick_reply.tpl

// start of slogic_add_quick_reply.tpl
$slogic_language['SLOGIC_ADD_QUICK_REPLY'] = 'Add quick reply';
$slogic_language['SLOGIC_QUICK_REPLY_ADDED'] = 'Quick reply added';
$slogic_language['SLOGIC_QUICK_REPLY_ADDED_INVALID'] = 'Invalid action.';
// end of slogic_add_quick_reply.tpl

// end of templates - functions

// end of templates
?>