{
	"items" : [
		{
			"SPI" :           "27",
			"Machine" :       "MG-3DW-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/16\"",
			"Fabric+Type" :   "cotton",
			"nano3" :         "http://merrow.com/cephei/images/nano/300393.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300392.jpg",
			"App" :           [
				"sling",
				"karate belt",
				"strap",
				"brace"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300391.jpg",
			"GROUP" :         "500118",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300390",
			"type" :          "Item",
			"label" :         "500118",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300390.jpg"
		},
		{
			"Machine" :       "22-FJ",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"App" :           [
				"sweater",
				"blanket",
				"hat",
				"mittens"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300353.jpg",
			"GROUP" :         "500107",
			"REFERENCE" :     "300352",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500107",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300352.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "denim",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300170.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300169.jpg",
			"GROUP" :         "500055",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300168",
			"type" :          "Item",
			"label" :         "500055",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300168.jpg"
		},
		{
			"Machine" :       "MG-3Q-3",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300377.jpg",
			"App" :           [
				"sweater",
				"blanket",
				"hat"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300376.jpg",
			"GROUP" :         "500114",
			"REFERENCE" :     "300375",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500114",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300375.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "ramie and vinyl",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300208.jpg",
			"GROUP" :         "500066",
			"REFERENCE" :     "300207",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500066",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300207.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "MG-3DR",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300280.jpg",
			"App" :           [
				"blanket",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300279.jpg",
			"GROUP" :         "500087",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300278",
			"type" :          "Item",
			"label" :         "500087",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300278.jpg"
		},
		{
			"SPI" :           "20",
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "1/8\"",
			"Fabric+Type" :   "rayon",
			"nano3" :         "http://merrow.com/cephei/images/nano/300206.jpg",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300205.jpg",
			"App" :           [
				"shirt",
				"sweater",
				"dress"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300204.jpg",
			"GROUP" :         "500065",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300203",
			"type" :          "Item",
			"label" :         "500065",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300203.jpg"
		},
		{
			"SPI" :           "17",
			"Machine" :       "MG-3DW-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "wool yarn",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300277.jpg",
			"App" :           [
				"sweater",
				"sock",
				"hat"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300276.jpg",
			"GROUP" :         "500086",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300275",
			"type" :          "Item",
			"label" :         "500086",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300275.jpg"
		},
		{
			"SPI" :           "13",
			"Machine" :       "M-3DWL",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/8\"",
			"Fabric+Type" :   "nylon",
			"nano4" :         "http://merrow.com/cephei/images/nano/300202.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300201.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300200.jpg",
			"Fabric" :        "woven",
			"App" :           [
				"lingerie",
				"pantie",
				"hoisery"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300199.jpg",
			"GROUP" :         "500064",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300198",
			"type" :          "Item",
			"label" :         "500064",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300198.jpg"
		},
		{
			"SPI" :           "25",
			"Machine" :       "MG-3DW-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "polyester",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300396.jpg",
			"App" :           [
				"placemat",
				"curtain"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300395.jpg",
			"GROUP" :         "500119",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300394",
			"type" :          "Item",
			"label" :         "500119",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300394.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "22-FJT-3",
			"Class" :         "crochet/shell",
			"Stitch+Width" :  "1/2\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"App" :           [
				"sweater",
				"blanket",
				"hat",
				"mittens"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300355.jpg",
			"GROUP" :         "500108",
			"REFERENCE" :     "300354",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500108",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300354.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "70-1D-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300380.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300379.jpg",
			"GROUP" :         "500115",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300378",
			"type" :          "Item",
			"label" :         "500115",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300378.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-2D-7",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300173.jpg",
			"GROUP" :         "500056",
			"REFERENCE" :     "300172",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500056",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300172.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "72-D3BR",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/2\"",
			"Fabric+Type" :   "wool",
			"Fabric" :        "knit",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300155.jpg",
			"GROUP" :         "500067",
			"REFERENCE" :     "300154",
			"Fabric+Weight" : "heavy",
			"type" :          "Item",
			"label" :         "500067",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300154.jpg"
		},
		{
			"SPI" :           "17",
			"Machine" :       "M-4D-45",
			"Class" :         "overlock",
			"Stitch+Width" :  "5/32\"",
			"Fabric+Type" :   "lycra",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300329.jpg",
			"App" :           [
				"hoisery",
				"dress sock"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300328.jpg",
			"GROUP" :         "500100",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300327",
			"type" :          "Item",
			"label" :         "500100",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300327.jpg"
		},
		{
			"SPI" :           "24",
			"Machine" :       "MG-3DW-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "nylon",
			"Fabric" :        "knit",
			"App" :           [
				"mittens",
				"hat"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300408.jpg",
			"GROUP" :         "500122",
			"REFERENCE" :     "300407",
			"Fabric+Weight" : "heavy",
			"type" :          "Item",
			"label" :         "500122",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300407.jpg"
		},
		{
			"Machine" :       "A-3QQ-3",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300351.jpg",
			"App" :           [
				"shirt",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300350.jpg",
			"GROUP" :         "500106",
			"REFERENCE" :     "300349",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500106",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300349.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton with acrylic coating",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300025.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300024.jpg",
			"GROUP" :         "500008",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300023",
			"type" :          "Item",
			"label" :         "500008",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300023.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-1D-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300167.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300166.jpg",
			"GROUP" :         "500054",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300165",
			"type" :          "Item",
			"label" :         "500054",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300165.jpg"
		},
		{
			"REFERENCE" :     "300294",
			"Fabric" :        "knit",
			"type" :          "Item",
			"Fabric+Weight" : "light",
			"label" :         "500092",
			"Stitch+Width" :  "5/16\"",
			"SPI" :           "13",
			"App" :           [
				"sweater",
				"dress sock",
				"scarf"
			],
			"Class" :         "crochet/shell",
			"Fabric+Type" :   "cotton",
			"Machine" :       "35-FJT",
			"nano5" :         "http://merrow.com/cephei/images/nano/300299.jpg",
			"nano4" :         "http://merrow.com/cephei/images/nano/300298.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300297.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300296.jpg",
			"nano1" :         "http://merrow.com/cephei/images/nano/300295.jpg",
			"GROUP" :         "500092",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300294.jpg"
		},
		{
			"SPI" :           "16",
			"Machine" :       "MG-3DR-2",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/16\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300267.jpg",
			"App" :           "sweater",
			"nano1" :         "http://merrow.com/cephei/images/nano/300266.jpg",
			"GROUP" :         "500083",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300265",
			"type" :          "Item",
			"label" :         "500083",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300265.jpg"
		},
		{
			"SPI" :           "8, 15",
			"Machine" :       "70-ABBY",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "polyester",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300144.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300143.jpg",
			"GROUP" :         "500047",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300142",
			"type" :          "Item",
			"label" :         "500047",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300142.jpg"
		},
		{
			"Machine" :       "MG-3QQ-3",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"nano3" :         "http://merrow.com/cephei/images/nano/300264.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300263.jpg",
			"App" :           [
				"sweater",
				"mitten",
				"hat",
				"blanket"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300262.jpg",
			"GROUP" :         "500082",
			"REFERENCE" :     "300261",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500082",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300261.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "70-1D-7",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300164.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300163.jpg",
			"GROUP" :         "500053",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300162",
			"type" :          "Item",
			"label" :         "500053",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300162.jpg"
		},
		{
			"REFERENCE" :     "300421",
			"Fabric" :        "knit",
			"type" :          "Item",
			"Fabric+Weight" : "light",
			"label" :         "500105",
			"Stitch+Width" :  "1/4\"",
			"SPI" :           "7",
			"App" :           [
				"sweater",
				"sock"
			],
			"Class" :         "crochet/shell",
			"Fabric+Type" :   "cotton",
			"Machine" :       "35-FJT",
			"nano5" :         "http://merrow.com/cephei/images/nano/300348.jpg",
			"nano4" :         "http://merrow.com/cephei/images/nano/300347.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300424.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300423.jpg",
			"nano1" :         "http://merrow.com/cephei/images/nano/300422.jpg",
			"GROUP" :         "500105",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300421.jpg"
		},
		{
			"REFERENCE" :     "300397",
			"Fabric" :        "woven",
			"type" :          "Item",
			"Fabric+Weight" : "medium",
			"label" :         "500120",
			"Stitch+Width" :  "1/8\"",
			"SPI" :           "28",
			"App" :           "sock",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Machine" :       "A-3Q-3, A-3DW",
			"nano5" :         "http://merrow.com/cephei/images/nano/300402.jpg",
			"nano4" :         "http://merrow.com/cephei/images/nano/300401.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300400.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300399.jpg",
			"nano1" :         "http://merrow.com/cephei/images/nano/300398.jpg",
			"GROUP" :         "500120",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300397.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "72-D3B",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton laminate",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300007.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300006.jpg",
			"GROUP" :         "500002",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300005",
			"type" :          "Item",
			"label" :         "500002",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300005.jpg"
		},
		{
			"Machine" :       "MG-3Q",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300318.jpg",
			"App" :           [
				"blanket",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300317.jpg",
			"GROUP" :         "500096",
			"REFERENCE" :     "300316",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500096",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300316.jpg"
		},
		{
			"SPI" :           "15",
			"Machine" :       "M-2DH-1",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/16\"",
			"Fabric+Type" :   "nylon",
			"nano4" :         "http://merrow.com/cephei/images/nano/300340.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300339.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300338.jpg",
			"Fabric" :        "knit",
			"App" :           [
				"pantie",
				"hoisery"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300337.jpg",
			"GROUP" :         "500103",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300336",
			"type" :          "Item",
			"label" :         "500103",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300336.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "70-D3B",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "polyester",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300141.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300140.jpg",
			"GROUP" :         "500046",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300139",
			"type" :          "Item",
			"label" :         "500046",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300139.jpg"
		},
		{
			"SPI" :           "16",
			"Machine" :       "M-3DWL",
			"Class" :         "overlock",
			"Stitch+Width" :  "5/32\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300335.jpg",
			"App" :           [
				"lingerie",
				"pantie",
				"hoisery"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300334.jpg",
			"GROUP" :         "500102",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300333",
			"type" :          "Item",
			"label" :         "500102",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300333.jpg"
		},
		{
			"SPI" :           "10",
			"Machine" :       "M-4DW-103",
			"Class" :         "overlock",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "wool",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300211.jpg",
			"App" :           [
				"sweater",
				"mittens",
				"hat"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300210.jpg",
			"GROUP" :         "500068",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300209",
			"type" :          "Item",
			"label" :         "500068",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300209.jpg"
		},
		{
			"SPI" :           "24",
			"Machine" :       "MG-3U",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/16\"",
			"Fabric+Type" :   "cotton with plastic coating",
			"nano3" :         "http://merrow.com/cephei/images/nano/300253.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300252.jpg",
			"App" :           "emblem",
			"nano1" :         "http://merrow.com/cephei/images/nano/300251.jpg",
			"GROUP" :         "500079",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300250",
			"type" :          "Item",
			"label" :         "500079",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300250.jpg"
		},
		{
			"SPI" :           "14",
			"Machine" :       "MG-4DW-100",
			"Class" :         "overlock",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300214.jpg",
			"App" :           "placemat",
			"nano1" :         "http://merrow.com/cephei/images/nano/300213.jpg",
			"GROUP" :         "500069",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300212",
			"type" :          "Item",
			"label" :         "500069",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300212.jpg"
		},
		{
			"SPI" :           "3",
			"Machine" :       "18-A",
			"Class" :         "crochet",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300225.jpg",
			"App" :           [
				"blanket",
				"pillow",
				"hat",
				"scarf",
				"sweater",
				"vest"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300224.jpg",
			"GROUP" :         "500072",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300223",
			"type" :          "Item",
			"label" :         "500072",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300223.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "MG-3DW-3",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton yarn",
			"nano4" :         "http://merrow.com/cephei/images/nano/300310.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300309.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300308.jpg",
			"Fabric" :        "knit",
			"App" :           [
				"sweater",
				"hat",
				"scarf"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300307.jpg",
			"GROUP" :         "500094",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300306",
			"type" :          "Item",
			"label" :         "500094",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300306.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "rayon",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300010.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300009.jpg",
			"GROUP" :         "500003",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300008",
			"type" :          "Item",
			"label" :         "500003",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300008.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/2\"",
			"Fabric+Type" :   "cotton with acrylic coating",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300022.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300021.jpg",
			"GROUP" :         "500007",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300020",
			"type" :          "Item",
			"label" :         "500007",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300020.jpg"
		},
		{
			"SPI" :           "5",
			"Machine" :       "18-S",
			"Class" :         "crochet",
			"Stitch+Width" :  "7/16\"",
			"Fabric+Type" :   "synthetic",
			"nano4" :         "http://merrow.com/cephei/images/nano/300222.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300221.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300220.jpg",
			"Fabric" :        "knit",
			"App" :           [
				"blanket",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300219.jpg",
			"GROUP" :         "500071",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300218",
			"type" :          "Item",
			"label" :         "500071",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300218.jpg"
		},
		{
			"SPI" :           "13",
			"Machine" :       "M-4DW-100",
			"Class" :         "overlock",
			"Stitch+Width" :  "7/32\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300332.jpg",
			"App" :           [
				"shirt",
				"sheet",
				"napkin"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300331.jpg",
			"GROUP" :         "500101",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300330",
			"type" :          "Item",
			"label" :         "500101",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300330.jpg"
		},
		{
			"REFERENCE" :     "300300",
			"Fabric" :        "knit",
			"type" :          "Item",
			"Fabric+Weight" : "medium",
			"label" :         "500093",
			"Stitch+Width" :  "3/16\"",
			"SPI" :           "11",
			"App" :           [
				"blanket",
				"pillow",
				"hat",
				"scarf",
				"sweater"
			],
			"Class" :         "crochet/shell",
			"Fabric+Type" :   "synthetic",
			"Machine" :       "35-FJ",
			"nano5" :         "http://merrow.com/cephei/images/nano/300305.jpg",
			"nano4" :         "http://merrow.com/cephei/images/nano/300304.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300303.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300302.jpg",
			"nano1" :         "http://merrow.com/cephei/images/nano/300301.jpg",
			"GROUP" :         "500093",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300300.jpg"
		},
		{
			"REFERENCE" :     "300341",
			"Fabric" :        "knit",
			"type" :          "Item",
			"Fabric+Weight" : "light",
			"label" :         "500104",
			"Stitch+Width" :  "7/16\", 1/4\"",
			"SPI" :           "9,11",
			"App" :           [
				"bathing suit",
				"athletic apparel"
			],
			"Class" :         "double-crochet",
			"Fabric+Type" :   "cotton",
			"Machine" :       "18-E, MG-3DW-7",
			"nano5" :         "http://merrow.com/cephei/images/nano/300346.jpg",
			"nano4" :         "http://merrow.com/cephei/images/nano/300345.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300344.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300343.jpg",
			"nano1" :         "http://merrow.com/cephei/images/nano/300342.jpg",
			"GROUP" :         "500104",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300341.jpg"
		},
		{
			"Machine" :       "MG-3QQ-3",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"App" :           [
				"sweater",
				"sock"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300434.jpg",
			"GROUP" :         "500129",
			"REFERENCE" :     "300433",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500129",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300433.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton with acrylic coating",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300019.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300018.jpg",
			"GROUP" :         "500006",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300017",
			"type" :          "Item",
			"label" :         "500006",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300017.jpg"
		},
		{
			"SPI" :           "5",
			"Machine" :       "18-E",
			"Class" :         "crochet",
			"Stitch+Width" :  "1/2\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300228.jpg",
			"App" :           [
				"blanket",
				"sweater",
				"jacket",
				"hat",
				"vest"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300227.jpg",
			"GROUP" :         "500073",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300226",
			"type" :          "Item",
			"label" :         "500073",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300226.jpg"
		},
		{
			"SPI" :           "22",
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "3/32\"",
			"Fabric+Type" :   "metalic ribbon",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300432.jpg",
			"App" :           [
				"ribbon",
				"shirt",
				"dress"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300431.jpg",
			"GROUP" :         "500128",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300430",
			"type" :          "Item",
			"label" :         "500128",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300430.jpg"
		},
		{
			"Machine" :       "MG-3Q",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300374.jpg",
			"App" :           "placemat",
			"nano1" :         "http://merrow.com/cephei/images/nano/300373.jpg",
			"GROUP" :         "500113",
			"REFERENCE" :     "300372",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500113",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300372.jpg"
		},
		{
			"SPI" :           "13",
			"Machine" :       "MG-3DW-4",
			"Class" :         "overlock",
			"Stitch+Width" :  "7/32\"",
			"Fabric+Type" :   "cotton yarn",
			"nano4" :         "http://merrow.com/cephei/images/nano/300315.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300314.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300313.jpg",
			"Fabric" :        "knit",
			"App" :           [
				"sweater",
				"hat",
				"scarf"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300312.jpg",
			"GROUP" :         "500095",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300311",
			"type" :          "Item",
			"label" :         "500095",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300311.jpg"
		},
		{
			"SPI" :           "20",
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "3/32\"",
			"Fabric+Type" :   "nylon/spandex",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300429.jpg",
			"App" :           [
				"shirt",
				"dress"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300428.jpg",
			"GROUP" :         "500127",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300427",
			"type" :          "Item",
			"label" :         "500127",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300427.jpg"
		},
		{
			"Machine" :       "MG-3QQ-3",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"App" :           [
				"sweater",
				"hat",
				"scarf"
			],
			"GROUP" :         "500112",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300371",
			"type" :          "Item",
			"label" :         "500112",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300371.jpg"
		},
		{
			"REFERENCE" :     "300229",
			"Fabric" :        "woven",
			"type" :          "Item",
			"Fabric+Weight" : "medium",
			"label" :         "500074",
			"Stitch+Width" :  "7/16\"",
			"SPI" :           "7",
			"App" :           [
				"sweater",
				"scarf"
			],
			"Class" :         "crochet/shell",
			"Fabric+Type" :   "synthetic",
			"Machine" :       "22-FJ",
			"nano5" :         "http://merrow.com/cephei/images/nano/300234.jpg",
			"nano4" :         "http://merrow.com/cephei/images/nano/300233.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300232.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300231.jpg",
			"nano1" :         "http://merrow.com/cephei/images/nano/300230.jpg",
			"GROUP" :         "500074",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300229.jpg"
		},
		{
			"SPI" :           "6",
			"Machine" :       "70-ABB-4",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300055.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300054.jpg",
			"GROUP" :         "500017",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300053",
			"type" :          "Item",
			"label" :         "500017",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300053.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "70-ABB-1",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton",
			"nano4" :         "http://merrow.com/cephei/images/nano/300052.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300051.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300050.jpg",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300049.jpg",
			"GROUP" :         "500016",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300048",
			"type" :          "Item",
			"label" :         "500016",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300048.jpg"
		},
		{
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "3/32\"",
			"Fabric+Type" :   "nylon",
			"nano3" :         "http://merrow.com/cephei/images/nano/300441.jpg",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300440.jpg",
			"App" :           [
				"shirt",
				"dress"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300439.jpg",
			"GROUP" :         "500131",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300438",
			"type" :          "Item",
			"label" :         "500131",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300438.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "70-1D-2 (CUSTOM)",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/32\"",
			"Fabric+Type" :   "dry laid fiberweb",
			"Fabric" :        "nonwoven",
			"App" :           "hairnet",
			"GROUP" :         "500099",
			"REFERENCE" :     "300326",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500099",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300326.jpg"
		},
		{
			"SPI" :           "24",
			"Machine" :       "MG-3U",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/16\"",
			"Fabric+Type" :   "denim",
			"nano3" :         "http://merrow.com/cephei/images/nano/300257.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300256.jpg",
			"App" :           "emblem",
			"nano1" :         "http://merrow.com/cephei/images/nano/300255.jpg",
			"GROUP" :         "500080",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300254",
			"type" :          "Item",
			"label" :         "500080",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300254.jpg"
		},
		{
			"SPI" :           "4",
			"Machine" :       "18-A",
			"Class" :         "crochet",
			"Stitch+Width" :  "9/16\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "knit",
			"App" :           [
				"blanket",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300426.jpg",
			"GROUP" :         "500126",
			"REFERENCE" :     "300425",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500126",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300425.jpg"
		},
		{
			"SPI" :           "6",
			"Machine" :       "70-Y3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300044.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300043.jpg",
			"GROUP" :         "500014",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300042",
			"type" :          "Item",
			"label" :         "500014",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300042.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton with acrylic coating",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300032.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300031.jpg",
			"GROUP" :         "500010",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300030",
			"type" :          "Item",
			"label" :         "500010",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300030.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2 (HP)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "9/16\"",
			"Fabric+Type" :   "wool",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300063.jpg",
			"GROUP" :         "500021",
			"REFERENCE" :     "300062",
			"Fabric+Weight" : "heavy",
			"type" :          "Item",
			"label" :         "500021",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300062.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "M-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "nylon",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300129.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300128.jpg",
			"GROUP" :         "500042",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300127",
			"type" :          "Item",
			"label" :         "500042",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300127.jpg"
		},
		{
			"SPI" :           "6",
			"Machine" :       "70-Y3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300058.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300057.jpg",
			"GROUP" :         "500018",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300056",
			"type" :          "Item",
			"label" :         "500018",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300056.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "15-CA-1",
			"Class" :         "crochet",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "synthetic",
			"nano3" :         "http://merrow.com/cephei/images/nano/300217.jpg",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300216.jpg",
			"App" :           [
				"blanket",
				"sweater",
				"jacket",
				"hat",
				"vest"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300215.jpg",
			"GROUP" :         "500070",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300385",
			"type" :          "Item",
			"label" :         "500070",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300385.jpg"
		},
		{
			"SPI" :           "14",
			"Machine" :       "MG-3DW-2",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300260.jpg",
			"App" :           "shirt",
			"nano1" :         "http://merrow.com/cephei/images/nano/300259.jpg",
			"GROUP" :         "500081",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300258",
			"type" :          "Item",
			"label" :         "500081",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300258.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-ABB-4",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "wool",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300041.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300040.jpg",
			"GROUP" :         "500013",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300039",
			"type" :          "Item",
			"label" :         "500013",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300039.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "70-ABB (SST)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "polyester",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300147.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300146.jpg",
			"GROUP" :         "500048",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300145",
			"type" :          "Item",
			"label" :         "500048",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300145.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "M-2D",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton/polyester blend",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300069.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300068.jpg",
			"GROUP" :         "500023",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300067",
			"type" :          "Item",
			"label" :         "500023",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300067.jpg"
		},
		{
			"SPI" :           "4",
			"Machine" :       "M-1-4E (BT)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300080.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300079.jpg",
			"GROUP" :         "500027",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300078",
			"type" :          "Item",
			"label" :         "500027",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300078.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "lycra",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300123.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300122.jpg",
			"GROUP" :         "500040",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300121",
			"type" :          "Item",
			"label" :         "500040",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300121.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "M-2DR-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "rayon",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300016.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300015.jpg",
			"GROUP" :         "500005",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300014",
			"type" :          "Item",
			"label" :         "500005",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300014.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "MG-3D-2",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300270.jpg",
			"App" :           [
				"blanket",
				"sweater",
				"jacket",
				"hat",
				"vest"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300269.jpg",
			"GROUP" :         "500084",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300268",
			"type" :          "Item",
			"label" :         "500084",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300268.jpg"
		},
		{
			"SPI" :           "64",
			"Machine" :       "M-4DW-45",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/8\"",
			"Fabric+Type" :   "nylon",
			"nano4" :         "http://merrow.com/cephei/images/nano/300192.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300191.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300190.jpg",
			"Fabric" :        "woven",
			"App" :           [
				"dress sock",
				"pantyhose"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300189.jpg",
			"GROUP" :         "500062",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300188",
			"type" :          "Item",
			"label" :         "500062",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300188.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-D3B (GAP)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "11/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300077.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300076.jpg",
			"GROUP" :         "500026",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300075",
			"type" :          "Item",
			"label" :         "500026",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300075.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "M-2DR-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "linen",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300013.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300012.jpg",
			"GROUP" :         "500004",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300011",
			"type" :          "Item",
			"label" :         "500004",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300011.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300047.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300046.jpg",
			"GROUP" :         "500015",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300045",
			"type" :          "Item",
			"label" :         "500015",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300045.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "M-2D-7",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "lycra",
			"Fabric" :        "knit",
			"App" :           "buttseaming",
			"GROUP" :         "500020",
			"REFERENCE" :     "300061",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500020",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300061.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-1D-7",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300060.jpg",
			"GROUP" :         "500019",
			"REFERENCE" :     "300059",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500019",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300059.jpg"
		},
		{
			"SPI" :           "5",
			"Machine" :       "M-1",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton/polyester blend",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300086.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300085.jpg",
			"GROUP" :         "500029",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300084",
			"type" :          "Item",
			"label" :         "500029",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300084.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-1D-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300178.jpg",
			"GROUP" :         "500058",
			"REFERENCE" :     "300177",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500058",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300177.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "nylon",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300132.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300131.jpg",
			"GROUP" :         "500043",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300130",
			"type" :          "Item",
			"label" :         "500043",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300130.jpg"
		},
		{
			"Machine" :       "MG-3Q",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"App" :           [
				"sock",
				"blanket",
				"hat",
				"scarf",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300325.jpg",
			"GROUP" :         "500098",
			"REFERENCE" :     "300324",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500098",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300324.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "1/8\"",
			"Fabric+Type" :   "polyester",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300437.jpg",
			"App" :           [
				"ribbon",
				"tablecloth",
				"napkin"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300436.jpg",
			"GROUP" :         "500130",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300435",
			"type" :          "Item",
			"label" :         "500130",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300435.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "nylon",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300126.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300125.jpg",
			"GROUP" :         "500041",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300124",
			"type" :          "Item",
			"label" :         "500041",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300124.jpg"
		},
		{
			"SPI" :           "13",
			"Machine" :       "M-3DWL",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/8\"",
			"Fabric+Type" :   "nylon",
			"nano4" :         "http://merrow.com/cephei/images/nano/300197.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300196.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300195.jpg",
			"Fabric" :        "woven",
			"App" :           [
				"lingerie",
				"pantie",
				"hoisery"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300194.jpg",
			"GROUP" :         "500063",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300193",
			"type" :          "Item",
			"label" :         "500063",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300193.jpg"
		},
		{
			"SPI" :           "16",
			"Machine" :       "MG-3DW-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "wool yarn",
			"nano3" :         "http://merrow.com/cephei/images/nano/300274.jpg",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300273.jpg",
			"App" :           [
				"rug",
				"flooring"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300272.jpg",
			"GROUP" :         "500085",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300271",
			"type" :          "Item",
			"label" :         "500085",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300271.jpg"
		},
		{
			"SPI" :           "15",
			"Machine" :       "70-ABB-1",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton with acrylic coating",
			"nano3" :         "http://merrow.com/cephei/images/nano/300150.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300149.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300171.jpg",
			"GROUP" :         "500049",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300148",
			"type" :          "Item",
			"label" :         "500049",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300148.jpg"
		},
		{
			"Machine" :       "MG-4Q-67",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300323.jpg",
			"App" :           [
				"shirt",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300322.jpg",
			"GROUP" :         "500097",
			"REFERENCE" :     "300321",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500097",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300321.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-ADN-1",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300083.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300082.jpg",
			"GROUP" :         "500028",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300081",
			"type" :          "Item",
			"label" :         "500028",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300081.jpg"
		},
		{
			"SPI" :           "8, 15",
			"Machine" :       "70-Y3B",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "polyester",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300138.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300137.jpg",
			"GROUP" :         "500045",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300136",
			"type" :          "Item",
			"label" :         "500045",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300136.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "nylon",
			"nano4" :         "http://merrow.com/cephei/images/nano/300120.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300119.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300118.jpg",
			"Fabric" :        "knit",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300117.jpg",
			"GROUP" :         "500039",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300116",
			"type" :          "Item",
			"label" :         "500039",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300116.jpg"
		},
		{
			"SPI" :           "6",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton with acrylic coating",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300028.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300027.jpg",
			"GROUP" :         "500009",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300026",
			"type" :          "Item",
			"label" :         "500009",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300026.jpg"
		},
		{
			"SPI" :           "21",
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "3/32\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300246.jpg",
			"App" :           [
				"pillow",
				"seat cushion",
				"placemat"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300245.jpg",
			"GROUP" :         "500077",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300244",
			"type" :          "Item",
			"label" :         "500077",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300244.jpg"
		},
		{
			"SPI" :           "14",
			"Machine" :       "M-3D",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300283.jpg",
			"App" :           [
				"blanket",
				"sweater",
				"jacket",
				"hat",
				"vest"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300282.jpg",
			"GROUP" :         "500088",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300281",
			"type" :          "Item",
			"label" :         "500088",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300281.jpg"
		},
		{
			"SPI" :           "21",
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "1/8\"",
			"Fabric+Type" :   "cotton",
			"nano4" :         "http://merrow.com/cephei/images/nano/300416.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300415.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300414.jpg",
			"Fabric" :        "knit",
			"App" :           [
				"shirt",
				"sweater",
				"dress"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300413.jpg",
			"GROUP" :         "500124",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300412",
			"type" :          "Item",
			"label" :         "500124",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300412.jpg"
		},
		{
			"Machine" :       "MG-3Q",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300370.jpg",
			"App" :           [
				"sweater",
				"shirt",
				"scarf"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300369.jpg",
			"GROUP" :         "500111",
			"REFERENCE" :     "300368",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500111",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300368.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300104.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300103.jpg",
			"GROUP" :         "500035",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300102",
			"type" :          "Item",
			"label" :         "500035",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300102.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "MG-3DW-7K",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton",
			"nano3" :         "http://merrow.com/cephei/images/nano/300293.jpg",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300292.jpg",
			"App" :           [
				"blanket",
				"pillow",
				"hat",
				"scarf",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300291.jpg",
			"GROUP" :         "500091",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300290",
			"type" :          "Item",
			"label" :         "500091",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300290.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2 (HP)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "wool",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300098.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300097.jpg",
			"GROUP" :         "500033",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300096",
			"type" :          "Item",
			"label" :         "500033",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300096.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "vinyl",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300135.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300134.jpg",
			"GROUP" :         "500044",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300133",
			"type" :          "Item",
			"label" :         "500044",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300133.jpg"
		},
		{
			"SPI" :           "16",
			"Machine" :       "MG-3DE-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "polyester",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300411.jpg",
			"App" :           [
				"tablecloth",
				"car cover",
				"boat cover"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300410.jpg",
			"GROUP" :         "500123",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300409",
			"type" :          "Item",
			"label" :         "500123",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300409.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "15-CA-1",
			"Class" :         "crochet",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "wool",
			"nano3" :         "http://merrow.com/cephei/images/nano/300389.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300388.jpg",
			"App" :           [
				"sweater",
				"blanket",
				"hat"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300387.jpg",
			"GROUP" :         "500117",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300386",
			"type" :          "Item",
			"label" :         "500117",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300386.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "70-1D-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300176.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300175.jpg",
			"GROUP" :         "500057",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300174",
			"type" :          "Item",
			"label" :         "500057",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300174.jpg"
		},
		{
			"SPI" :           "6",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/2\"",
			"Fabric+Type" :   "PVC",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300153.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300152.jpg",
			"GROUP" :         "500050",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300151",
			"type" :          "Item",
			"label" :         "500050",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300151.jpg"
		},
		{
			"Machine" :       "MG-4Q-67",
			"Class" :         "shell",
			"Fabric+Type" :   "cotton",
			"nano3" :         "http://merrow.com/cephei/images/nano/300384.jpg",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300383.jpg",
			"App" :           [
				"kimono",
				"sweater",
				"shirt",
				"scarf",
				"blanket"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300382.jpg",
			"GROUP" :         "500116",
			"REFERENCE" :     "300381",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500116",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300381.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B (GAP)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "11/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300074.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300073.jpg",
			"GROUP" :         "500025",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300072",
			"type" :          "Item",
			"label" :         "500025",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300072.jpg"
		},
		{
			"SPI" :           "23",
			"Machine" :       "70-ADN-1",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "wool",
			"nano3" :         "http://merrow.com/cephei/images/nano/300004.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300003.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300002.jpg",
			"GROUP" :         "500001",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300001",
			"type" :          "Item",
			"label" :         "500001",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300001.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton with acrylic coating",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300035.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300034.jpg",
			"GROUP" :         "500011",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300033",
			"type" :          "Item",
			"label" :         "500011",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300033.jpg"
		},
		{
			"SPI" :           "17",
			"Machine" :       "MG-3D-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300286.jpg",
			"App" :           [
				"FEMA blanket",
				"blanket",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300285.jpg",
			"GROUP" :         "500089",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300284",
			"type" :          "Item",
			"label" :         "500089",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300284.jpg"
		},
		{
			"SPI" :           "36",
			"Machine" :       "MG-2DNR-1",
			"Class" :         "pearl",
			"Stitch+Width" :  "3/32\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300249.jpg",
			"App" :           [
				"shirt",
				"sweater",
				"dress"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300248.jpg",
			"GROUP" :         "500078",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300247",
			"type" :          "Item",
			"label" :         "500078",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300247.jpg"
		},
		{
			"Machine" :       "A-3QQ-3",
			"Class" :         "shell",
			"nano5" :         "http://merrow.com/cephei/images/nano/300361.jpg",
			"Fabric+Type" :   "cotton",
			"nano4" :         "http://merrow.com/cephei/images/nano/300360.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300359.jpg",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300358.jpg",
			"App" :           [
				"sock",
				"blanket",
				"hat",
				"scarf",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300357.jpg",
			"GROUP" :         "500109",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300356",
			"type" :          "Item",
			"label" :         "500109",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300356.jpg"
		},
		{
			"Machine" :       "A-3Q-3",
			"Class" :         "shell",
			"Fabric+Type" :   "nylon",
			"nano3" :         "http://merrow.com/cephei/images/nano/300406.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300405.jpg",
			"App" :           [
				"napkin",
				"table cloth"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300404.jpg",
			"GROUP" :         "500121",
			"REFERENCE" :     "300403",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500121",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300403.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "72-D3B",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300038.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300037.jpg",
			"GROUP" :         "500012",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300036",
			"type" :          "Item",
			"label" :         "500012",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300036.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "MG-1D",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300101.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300100.jpg",
			"GROUP" :         "500034",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300099",
			"type" :          "Item",
			"label" :         "500034",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300099.jpg"
		},
		{
			"SPI" :           "10",
			"Machine" :       "MG-3DW-7",
			"Class" :         "overlock",
			"Stitch+Width" :  "3/16\"",
			"Fabric+Type" :   "vinyl",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300289.jpg",
			"App" :           [
				"awning",
				"window shade"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300288.jpg",
			"GROUP" :         "500090",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300287",
			"type" :          "Item",
			"label" :         "500090",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300287.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "70-2D-7",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300158.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300157.jpg",
			"GROUP" :         "500051",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300156",
			"type" :          "Item",
			"label" :         "500051",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300156.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "MG-3D-7K",
			"Class" :         "overlock",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "synthetic",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300243.jpg",
			"App" :           [
				"upholstry",
				"sweater"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300242.jpg",
			"GROUP" :         "500076",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300241",
			"type" :          "Item",
			"label" :         "500076",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300241.jpg"
		},
		{
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "wool",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300443.jpg",
			"GROUP" :         "500132",
			"REFERENCE" :     "300442",
			"Fabric+Weight" : "medium",
			"type" :          "Item",
			"label" :         "500132",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300442.jpg"
		},
		{
			"SPI" :           "10",
			"Machine" :       "M-3D-3",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300187.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300186.jpg",
			"GROUP" :         "500061",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300185",
			"type" :          "Item",
			"label" :         "500061",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300185.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "polypropylene",
			"Fabric" :        "nonwoven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300107.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300106.jpg",
			"GROUP" :         "500036",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300105",
			"type" :          "Item",
			"label" :         "500036",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300105.jpg"
		},
		{
			"REFERENCE" :     "300235",
			"Fabric" :        "woven",
			"type" :          "Item",
			"Fabric+Weight" : "medium",
			"label" :         "500075",
			"Stitch+Width" :  "3/8\"",
			"SPI" :           "6",
			"App" :           [
				"blanket",
				"sweater",
				"scarf",
				"hat"
			],
			"Class" :         "crochet/shell",
			"Fabric+Type" :   "synthetic",
			"Machine" :       "27-FJ",
			"nano5" :         "http://merrow.com/cephei/images/nano/300240.jpg",
			"nano4" :         "http://merrow.com/cephei/images/nano/300239.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300238.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300237.jpg",
			"nano1" :         "http://merrow.com/cephei/images/nano/300236.jpg",
			"GROUP" :         "500075",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300235.jpg"
		},
		{
			"SPI" :           "7",
			"Machine" :       "MG-2DR-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300095.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300094.jpg",
			"GROUP" :         "500032",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300093",
			"type" :          "Item",
			"label" :         "500032",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300093.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "72-D3BR",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "3/8\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300184.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300183.jpg",
			"GROUP" :         "500060",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300182",
			"type" :          "Item",
			"label" :         "500060",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300182.jpg"
		},
		{
			"SPI" :           "5",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "polypropylene",
			"Fabric" :        "nonwoven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300110.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300109.jpg",
			"GROUP" :         "500037",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300108",
			"type" :          "Item",
			"label" :         "500037",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300108.jpg"
		},
		{
			"SPI" :           "15",
			"Machine" :       "MG-1D",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/4\"",
			"Fabric+Type" :   "cotton/polyester blend",
			"Fabric" :        "knit",
			"nano2" :         "http://merrow.com/cephei/images/nano/300181.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300180.jpg",
			"GROUP" :         "500059",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300179",
			"type" :          "Item",
			"label" :         "500059",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300179.jpg"
		},
		{
			"SPI" :           "4",
			"Machine" :       "18-A",
			"Class" :         "crochet",
			"Stitch+Width" :  "9/32\"",
			"Fabric+Type" :   "cashmere",
			"nano3" :         "http://merrow.com/cephei/images/nano/300420.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300419.jpg",
			"App" :           [
				"blanket",
				"sweater",
				"jacket",
				"hat",
				"vest"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300418.jpg",
			"GROUP" :         "500125",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300417",
			"type" :          "Item",
			"label" :         "500125",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300417.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "72-D3BR",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "1/2\"",
			"Fabric+Type" :   "cotton",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300071.jpg",
			"GROUP" :         "500024",
			"REFERENCE" :     "300070",
			"Fabric+Weight" : "light",
			"type" :          "Item",
			"label" :         "500024",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300070.jpg"
		},
		{
			"SPI" :           "12",
			"Machine" :       "70-ABB-1",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "7/16\"",
			"Fabric+Type" :   "cotton laminate",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300066.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300065.jpg",
			"GROUP" :         "500022",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300064",
			"type" :          "Item",
			"label" :         "500022",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300064.jpg"
		},
		{
			"SPI" :           "8",
			"Machine" :       "70-D3B-2",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "filter material",
			"Fabric" :        "nonwoven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300161.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300160.jpg",
			"GROUP" :         "500052",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300159",
			"type" :          "Item",
			"label" :         "500052",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300159.jpg"
		},
		{
			"SPI" :           "9",
			"Machine" :       "70-D3B-2 (HP)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "wool",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300089.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300088.jpg",
			"GROUP" :         "500030",
			"Fabric+Weight" : "heavy",
			"REFERENCE" :     "300087",
			"type" :          "Item",
			"label" :         "500030",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300087.jpg"
		},
		{
			"SPI" :           "11",
			"Machine" :       "M-2D-7",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/16\"",
			"Fabric+Type" :   "cotton/polyester blend",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300092.jpg",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300091.jpg",
			"GROUP" :         "500031",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300090",
			"type" :          "Item",
			"label" :         "500031",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300090.jpg"
		},
		{
			"SPI" :           "10",
			"Machine" :       "70-D3B (GAP)",
			"Class" :         "butt-seam",
			"Stitch+Width" :  "5/8\"",
			"Fabric+Type" :   "cotton",
			"nano4" :         "http://merrow.com/cephei/images/nano/300115.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300114.jpg",
			"nano2" :         "http://merrow.com/cephei/images/nano/300113.jpg",
			"Fabric" :        "woven",
			"App" :           "buttseaming",
			"nano1" :         "http://merrow.com/cephei/images/nano/300112.jpg",
			"GROUP" :         "500038",
			"Fabric+Weight" : "medium",
			"REFERENCE" :     "300111",
			"type" :          "Item",
			"label" :         "500038",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300111.jpg"
		},
		{
			"Machine" :       "MG-3Q",
			"Class" :         "shell",
			"nano5" :         "http://merrow.com/cephei/images/nano/300367.jpg",
			"Fabric+Type" :   "silk",
			"nano4" :         "http://merrow.com/cephei/images/nano/300366.jpg",
			"nano3" :         "http://merrow.com/cephei/images/nano/300365.jpg",
			"Fabric" :        "woven",
			"nano2" :         "http://merrow.com/cephei/images/nano/300364.jpg",
			"App" :           [
				"blanket",
				"sweater",
				"scarf",
				"hat"
			],
			"nano1" :         "http://merrow.com/cephei/images/nano/300363.jpg",
			"GROUP" :         "500110",
			"Fabric+Weight" : "light",
			"REFERENCE" :     "300362",
			"type" :          "Item",
			"label" :         "500110",
			"imgUrl" :        "http://merrow.com/cephei/images/main/300362.jpg"
		}
	]
}