{
	"items" : [
		{
			"Description" :      "Size 4 Merrow curved needle with a scarf and tapered blade.  Recommended for use with medium to heavy fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 4SD needle.",
			"name" :             "4SDT",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4SDT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 2 Merrow curved needle with a ball point.  Recommended for use with light knit fabric or lingerie. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "2DF",
			"Shank+Length" :     "Standard",
			"Size" :             "2",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "2DF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 00 Merrow curved needle, recommended for nylon tricot, lingerie, and other delicate fabric.",
			"name" :             "00D",
			"Shank+Length" :     "Standard",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "00D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "60",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 0 Merrow curved needle with a tapered blade.  Recommended for nylon tricot, lingerie, and other delicate fabric.  .   Tapered blade makes the needle more durable than the 0D needle.",
			"name" :             "0DT",
			"Shank+Length" :     "Standard",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "0DT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "65",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.  This needle has a short shank which facilitates a clean release from fabric.",
			"Hoisery" :          "Hosiery",
			"name" :             "B1DE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "B",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B1DE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Standard"
		},
		{
			"name" :             "1SM",
			"Shank+Length" :     "Standard",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1SM",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.   This needle has a short shank which facilitates a clean release from fabric.",
			"name" :             "1DE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1DE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"Crochet" :          "Crochet",
			"label" :            "1 STRAIGHT",
			"Emblem+Edging" :    "Standard",
			"Eye+Type" :         "Standard",
			"Tapered+Blade" :    "Standard",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 1 Merrow straight needle.",
			"Hoisery" :          "Standard",
			"name" :             "1 STRAIGHT"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a bulge eye and ball point.  Recommended for use in a two-needle (style 60 or 100) sewing machine on mens medium-heavy weight socks.  The bulge eye is designed for applications where fabric closes around the needle after penetration and affects proper thread release. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"Hoisery" :          "Hosiery",
			"name" :             "A4BDF",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Eye+Type" :         "Bulge Eye",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A4BDF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 5 Merrow curved needle with a short shank.  Recommended for medium-heavy fabric.  The short shank facilitates a clean release from fabric.",
			"name" :             "5DE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "5",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "5DE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "110",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 2 Merrow curved needle with a scarf, for use in a two-needle (style 45) sewing machine.  Often used on women\'s hosiery. The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"Hoisery" :          "Hosiery",
			"name" :             "B2SD",
			"Shank+Length" :     "Standard",
			"Size" :             "B",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B2SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 000, the thinnest Merrow curved needle. Recommended for lingerie and delicate material. Not as durable as the 000DT, but creates a smaller needle hole.",
			"name" :             "000D",
			"Shank+Length" :     "Standard",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "000D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "55",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 00 Merrow curved needle for use in a two-needle sewing machine (style 45).  This needle has a short shank which facilitates a clean release from fabric.  Often used on the most delicate ladies hosiery.",
			"Hoisery" :          "Hosiery",
			"name" :             "B00DE",
			"Shank+Length" :     "Short",
			"Size" :             "B",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B00DE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "60",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 7 Merrow curved needle.  Recommended for heavy knit fabric or for butt seaming medium weight fabric.",
			"name" :             "7D",
			"Shank+Length" :     "Standard",
			"Size" :             "7",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "7D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "130",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.   This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the B1DE and BiSD needles.",
			"Hoisery" :          "Hosiery",
			"name" :             "B1SDT",
			"Shank+Length" :     "Standard",
			"Size" :             "B",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B1SDT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 5 Merrow curved needle with a specially designed groove on the inside of the blade curve.  Recommended for use on wash cloths or loose wovens.  The special groove prevents a terry loop from pulling the needle thread away from the lower looper.",
			"name" :             "5DJ",
			"Shank+Length" :     "Standard",
			"Size" :             "5",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Groove on Needle",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "5DJ",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 5 Merrow curved needle with a scarf above the eye of the needle.  Recommended for use on heavy knit material and for butt seaming light fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition.",
			"name" :             "5SD",
			"Shank+Length" :     "Standard",
			"Size" :             "5",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "5SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 2 Merrow curved needle with a scarf, for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks. The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"Hoisery" :          "Hosiery",
			"name" :             "A2SD",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A2SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "110",
			"label" :            "5D KOOLTORR",
			"Emblem+Edging" :    "Standard",
			"Eye+Type" :         "Standard",
			"Tapered+Blade" :    "Standard",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "5",
			"Type+of+Coating" :  "Koltorr Coating",
			"Description" :      "Size 5 Merrow curved needle.  Recommended for medium to heavy material.  The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"Hoisery" :          "Standard",
			"name" :             "5D KOOLTORR",
			"Buttseaming" :      "End to End Seaming"
		},
		{
			"Description" :      "Size 0 Merrow curved needle.  Recommended for nylon tricot, lingerie, and other delicate fabric.",
			"name" :             "0D",
			"Shank+Length" :     "Standard",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "0D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "65",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 5 Merrow straight needle",
			"name" :             "5S",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "5",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "5S",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 3 Merrow straight needle.",
			"name" :             "3 STRAIGHT",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "3",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "3 STRAIGHT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "90",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on ladies hosiery. This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.  Tapered blade makes it more durable than the BODE needle.",
			"Hoisery" :          "Hosiery",
			"name" :             "B0SDT",
			"Shank+Length" :     "Standard",
			"Size" :             "B",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B0SDT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "65",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 2 Merrow curved needle with a scarf.  Recommended for use with light knit fabric or lingerie.  The scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"Hoisery" :          "Standard",
			"name" :             "2SD",
			"Shank+Length" :     "Standard",
			"Size" :             "2",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "2SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 5 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Recommended for use on heavy weight socks. The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"Hoisery" :          "Hosiery",
			"name" :             "A5D KOOLTORR",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A5D KOOLTORR",
			"Type+of+Coating" :  "Koltorr Coating",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 5 Merrow curved needle with a ball point, for use in a two-needle (style 60 or 100) sewing machine.  Recommended for use on heavy weight socks. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"Hoisery" :          "Hosiery",
			"name" :             "A5DF",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A5DF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a scarf, ball point, and tapered blade.  Recommended for use with medium to heavy fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts. Tapered blade makes it more durable than the 4SD needle.",
			"name" :             "4SDTF",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4SDTF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 7 Merrow curved needle with a scarf and a tapered blade.  Recommended for use on heavy knit material and for butt seaming medium weight fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 7SD needle.",
			"name" :             "7SDT",
			"Shank+Length" :     "Standard",
			"Size" :             "7",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "7SDT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "130",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 2 Merrow straight needle.",
			"name" :             "2 STRAIGHT",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "2",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "2 STRAIGHT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "80",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 6 Merrow curved needle with a tapered blade.  Recommended for use on heavy knit material and for butt seaming light fabric.  The tapered blade makes it more durable than the 7D needle.",
			"name" :             "6DT",
			"Shank+Length" :     "Standard",
			"Size" :             "6",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "6DT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "120",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 10 Merrow straight needle.",
			"name" :             "10S",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "10",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "10S",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "200",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 2 Merrow curved needle with a scarf, ball point, and short shank.  Recommended for use with light knit fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts.  This needle has a short shank which helps a clean release from fabric.",
			"name" :             "2SDFE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "2",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "2SDFE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 60 or 100).  Often used on mens socks.",
			"Hoisery" :          "Hosiery",
			"name" :             "A0D",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A0D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "65",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 3 Merrow curved needle.  Recommended for light to medium weight fabric.  The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"Hoisery" :          "Standard",
			"name" :             "3D KOOLTORR",
			"Shank+Length" :     "Standard",
			"Size" :             "3",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "3D KOOLTORR",
			"Type+of+Coating" :  "Koltorr Coating",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "90",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 10 Merrow straight needle.",
			"name" :             "10H",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "10",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "10H",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "200",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 8 Merrow curved needle with a spear point.  Recommended for butt seaming tough fabrics.  The spear point blade is angled instead of rounded which allows it to easily penetrate dense fabrics.",
			"name" :             "8DG",
			"Shank+Length" :     "Standard",
			"Size" :             "8",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Spear Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "8DG",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "150",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 0 Merrow curved needle with a ball point.  Recommended for lingerie and lightweight fabric. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "0DF",
			"Shank+Length" :     "Standard",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "0DF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "65",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 2 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks.",
			"Hoisery" :          "Hosiery",
			"name" :             "A2D",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A2D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "110",
			"label" :            "5SDT",
			"Emblem+Edging" :    "Standard",
			"Eye+Type" :         "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "5",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 5 Merrow curved needle with a scarf above the eye of the needle.  Recommended for use on heavy knit material and for butt seaming light fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 5D and 5SD needles.",
			"Hoisery" :          "Standard",
			"name" :             "5SDT",
			"Buttseaming" :      "End to End Seaming"
		},
		{
			"Description" :      "Size 8 Merrow curved needle.  Recommended for butt seaming woven fabric and heavy knits.",
			"name" :             "8D",
			"Shank+Length" :     "Standard",
			"Size" :             "8",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "8D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "150",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium-heavy weight socks.",
			"Hoisery" :          "Hosiery",
			"name" :             "A4D",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A4D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 8 Merrow straight needle.",
			"name" :             "8S",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "8",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "8S",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "150",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 8 Merrow curved needle with a scarf and tapered blade.  Recommended for butt seaming woven fabrics and heavy knits. The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The tapered blade makes it more durable than the 8D needle.",
			"name" :             "8SD",
			"Shank+Length" :     "Standard",
			"Size" :             "8",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "8SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "150",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.  This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"name" :             "1SD",
			"Shank+Length" :     "Standard",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.   This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"Hoisery" :          "Hosiery",
			"name" :             "B1SD",
			"Shank+Length" :     "Standard",
			"Size" :             "B",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B1SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 0 Merrow curved needle.  Recommended for lingerie and lightweight fabric. This needle has a short shank which facilitates a clean release from sewn material.",
			"name" :             "0DE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "0DE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "65",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 2 Merrow curved needle.  Recommended for use on light to medium weight knits. Tapered blade makes it more durable than the 2SD needle.",
			"name" :             "2SDT",
			"Shank+Length" :     "Standard",
			"Size" :             "2",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "2SDT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 45).  This needle has a short shank which facilitates a clean release from fabric.  Often used on delicate ladies hosiery.",
			"Hoisery" :          "Hosiery",
			"name" :             "B0DE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "B",
			"Eye+Type" :         "Bulge",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B0DE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "65",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 00 Merrow curved needle recommended for lingerie and delicate fabric.  This needle has a short shank which facilitates a clean release from fabric.",
			"name" :             "00DE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "00DE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "60",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a bulge eye and ball point.  This needle is recommended for use on medium weight fabrics and emblems. The bulge eye is designed for applications where fabric closes around the needle after penetration and affects proper thread release. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "4BDF",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Bulge Eye",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4BDF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.",
			"Hoisery" :          "Standard",
			"name" :             "1D",
			"Shank+Length" :     "Standard",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow straight needle.",
			"name" :             "4 STRAIGHT",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "4",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4 STRAIGHT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a ball point, for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium-heavy weight socks.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"Hoisery" :          "Hosiery",
			"name" :             "A4DF",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A4DF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 1 Merrow curved needle with scarf, ball point, and short shank.  Recommended for use on light knits and tightly knit material.  This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.  This needle has a short shank which facilitates a clean release from fabric.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "1SDFE",
			"Shank+Length" :     "Short Shank",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1SDFE",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.   Tapered blade makes it more durable than the 1SD and 1D needles.",
			"name" :             "1SDT",
			"Shank+Length" :     "Standard",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1SDT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 5 Merrow straight needle",
			"name" :             "5A",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "5",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "5A",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a scarf. Recommended for medium weight fabric and emblems.  The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"name" :             "4SD",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a scarf and ball point.  Recommended for use with medium weight fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "4SDF",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4SDF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 60 or 100).  Often used on mens medium weight socks.",
			"Hoisery" :          "Hosiery",
			"name" :             "A1D",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A1D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a bulge eye.  This needle is recommended for use on medium width fabrics and emblems. The bulge eye is designed for applications where fabric closes around the needle after penetration and affects proper thread release.",
			"name" :             "4BD",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Bulge Eye",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4BD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 3 Merrow curved needle with a scarf and ball point.  Recommended for use with light and medium knit fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "3SDF",
			"Shank+Length" :     "Standard",
			"Size" :             "3",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "3SDF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "90",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 7 Merrow curved needle with a scarf above the eye of the needle.  Recommended for use on heavy knit material and for butt seaming medium weight fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition.",
			"name" :             "7SD",
			"Shank+Length" :     "Standard",
			"Size" :             "7",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "7SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "130",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 4 Merrow curved needle with a ball point.  This needle is recommended for use on medium weight fabrics and emblems. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "4DF",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4DF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 3 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks.",
			"Hoisery" :          "Hosiery",
			"name" :             "A3D",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A3D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "90",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 1 Merrow curved needle with a ball point.  Recommended for use on light knits and tightly knit material.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "1DF",
			"Shank+Length" :     "Standard",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1DF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 1 Merrow curved needle with a scarf, tapered blade and ball point.  Recommended for use on light knits and tightly knit material. The scarf, flat spot above the eye, facilitates the lower looper/needle transition  Tapered blade makes it more durable than the 1SD and 1D needles.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "1SDTF",
			"Shank+Length" :     "Standard",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1SDTF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 11 Merrow straight needle.",
			"name" :             "11 STRAIGHT",
			"Shank+Length" :     "Standard",
			"Crochet" :          "Crochet",
			"Size" :             "11",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "11 STRAIGHT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Straight",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 4 Merrow curved needle.  Recommended for use on medium weight fabrics and emblems.",
			"name" :             "4D",
			"Shank+Length" :     "Standard",
			"Size" :             "4",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "4D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "100",
			"Emblem+Edging" :    "Emblem Edging",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 000, the thinnest Merrow curved needle. Recommended for lingerie and delicate material. Tapered blade makes it more durable than the 000D needle.",
			"name" :             "000DT",
			"Shank+Length" :     "Standard",
			"Size" :             "0",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "000DT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "55",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"name" :             "1SMF",
			"Shank+Length" :     "Standard",
			"Size" :             "1",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1SMF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 3 Merrow curved needle with a scarf and tapered blade.  Recommended for use with light and medium knit fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 3SD needle.",
			"Hoisery" :          "Standard",
			"name" :             "3SDT",
			"Shank+Length" :     "Standard",
			"Size" :             "3",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "3SDT",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Linear" :           "Curved",
			"Metric+Size" :      "90",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 3 Merrow curved needle with a scarf. Recommended for light and medium weight fabric.  The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"name" :             "3SD",
			"Shank+Length" :     "Standard",
			"Size" :             "3",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "3SD",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "90",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 5 Merrow curved needle.  Recommended for use on heavy knit material and for butt seaming light fabric.",
			"name" :             "5D",
			"Shank+Length" :     "Standard",
			"Size" :             "5",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Buttseaming" :      "End to End Seaming",
			"label" :            "5D",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"name" :             "3SM",
			"Shank+Length" :     "Standard",
			"Size" :             "3",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "3SM",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "90",
			"Emblem+Edging" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 2 Merrow curved needle with a ball point for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"Hoisery" :          "Hosiery",
			"name" :             "A2DF",
			"Shank+Length" :     "Standard",
			"Size" :             "A",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A2DF",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Linear" :           "Curved",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		}

	]
}