{
	"items" :      [
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (B) designation",
			"ot" :          76794441,
			"label" :       "72",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-B1DE/M/B001BK7E2K.htm",
			"shanklength" : "Short Shank",
			"asin" :        "B001BK7E2K",
			"size" :        "Class B",
			"metric" :      70,
			"point" :       "Standard",
			"picname" :     "B1DE",
			"description" : "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.  This needle has a short shank which facilitates a clean release from fabric.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "B1DE",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-B1DE/M/B001BK7E2K.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791194,
			"label" :         "3",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-00D/M/B001BK5A6M.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK5A6M",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        60,
			"point" :         "Standard",
			"picname" :       "00D",
			"description" :   "Size 00 Merrow curved needle, recommended for nylon tricot, lingerie, and other delicate fabric.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "00D",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-00D/M/B001BK5A6M.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793873,
			"label" :       "61",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A2DF/M/B001E29RQ6.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E29RQ6",
			"size" :        "Class A",
			"metric" :      80,
			"point" :       "Ball Point",
			"picname" :     "A2DF",
			"description" : "Size 2 Merrow curved needle with a ball point for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A2DF",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A2DF/M/B001E29RQ6.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793678,
			"label" :       "56",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-8S/M/B001BK5KY4.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5KY4",
			"size" :        "Class 8",
			"metric" :      150,
			"point" :       "Standard",
			"picname" :     "8SD",
			"description" : "Size 8 Merrow straight needle.",
			"tapered" :     "Standard",
			"linear" :      "Straight",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "8S",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-8S/M/B001BK5KY4.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792537,
			"label" :       "34",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4BD/M/B001BK5E6I.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5E6I",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Standard",
			"picname" :     "4BD",
			"description" : "Size 4 Merrow curved needle with a bulge eye.  This needle is recommended for use on medium width fabrics and emblems. The bulge eye is designed for applications where fabric closes around the needle after penetration and affects proper thread release.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Bulge Eye",
			"name" :        "4BD",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4BD/M/B001BK5E6I.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791381,
			"label" :         "12",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-11/M/B001BK8Q2C.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK8Q2C",
			"size" :          "Class 11",
			"fabric_weight" : "Light",
			"metric" :        250,
			"point" :         "Standard",
			"picname" :       "11S",
			"description" :   "Size 11 Merrow straight needle.",
			"tapered" :       "Standard",
			"linear" :        "Straight",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "11S",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-11/M/B001BK8Q2C.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (B) designation",
			"ot" :          76794443,
			"label" :       "73",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-B1SD/M/B001BK90X6.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK90X6",
			"size" :        "Class B",
			"metric" :      70,
			"point" :       "Standard",
			"picname" :     "B1SD",
			"description" : "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.   This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "B1SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-B1SD/M/B001BK90X6.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792705,
			"label" :       "48",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5SD/M/B001BK8USW.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK8USW",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5D",
			"description" : "Size 5 Merrow curved needle with a scarf above the eye of the needle.  Recommended for use on heavy knit material and for butt seaming light fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "5SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5SD/M/B001BK8USW.htm"
		},
		{
			"shanklength" :   "Standard",
			"shank" :         "Standard",
			"name" :          "1S",
			"scarf" :         "Standard",
			"coating" :       "Standard",
			"metric" :        70,
			"picname" :       "1S",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"linear" :        "Straight",
			"type" :          "Item",
			"label" :         "9",
			"point" :         "Standard",
			"description" :   "Size 1 Merrow straight needle.",
			"tapered" :       "Standard",
			"fabric_weight" : "Light",
			"size" :          "Class 1"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791302,
			"label" :         "11",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-10S/M/B001BVLOOS.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BVLOOS",
			"size" :          "Class 10",
			"fabric_weight" : "Light",
			"metric" :        200,
			"point" :         "Standard",
			"picname" :       "10S",
			"description" :   "Size 10 Merrow straight needle.",
			"tapered" :       "Standard",
			"linear" :        "Straight",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "10S",
			"scarf" :         "Scarf",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-10S/M/B001BVLOOS.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793676,
			"label" :       "55",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-8DG/M/B001BK7DK8.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK7DK8",
			"size" :        "Class 8",
			"metric" :      150,
			"point" :       "Spear Point",
			"picname" :     "8SD",
			"description" : "Size 8 Merrow curved needle with a spear point.  Recommended for butt seaming tough fabrics.  The spear point blade is angled instead of rounded which allows it to easily penetrate dense fabrics.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "8DG",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-8DG/M/B001BK7DK8.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792698,
			"label" :       "43",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5D/M/B001BK1890.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK1890",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5D",
			"description" : "Size 5 Merrow curved needle.  Recommended for use on heavy knit material and for butt seaming light fabric.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "5D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5D/M/B001BK1890.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791809,
			"label" :         "14",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1DE/M/B001E29RMU.htm",
			"shanklength" :   "Short Shank",
			"asin" :          "B001E29RMU",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Standard",
			"picname" :       "1DE",
			"description" :   "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.   This needle has a short shank which facilitates a clean release from fabric.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1DE",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1DE/M/B001E29RMU.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793725,
			"label" :       "58",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A0D/M/B001E225PG.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E225PG",
			"size" :        "Class A",
			"metric" :      65,
			"point" :       "Standard",
			"picname" :     "A0D",
			"description" : "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 60 or 100).  Often used on mens socks.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A0D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A0D/M/B001E225PG.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791815,
			"label" :         "20",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1SMF/M/B001BK5CS8.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK5CS8",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Standard",
			"picname" :       "1SM",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1SM",
			"scarf" :         "Scarf",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1SMF/M/B001BK5CS8.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792439,
			"label" :       "31",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-3SDT/M/B001BK5DPU.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5DPU",
			"size" :        "Class 3",
			"metric" :      90,
			"point" :       "Standard",
			"picname" :     "3SDT",
			"description" : "Size 3 Merrow curved needle with a scarf and tapered blade.  Recommended for use with light and medium knit fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 3SD needle.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "3SDT",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-3SDT/M/B001BK5DPU.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (B) designation",
			"ot" :          76794446,
			"label" :       "75",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-B2SD/M/B001BK90ZO.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK90ZO",
			"size" :        "Class B",
			"metric" :      80,
			"point" :       "Standard",
			"picname" :     "B2SD",
			"description" : "Size 2 Merrow curved needle with a scarf, for use in a two-needle (style 45) sewing machine.  Often used on women\'s hosiery. The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "B2SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-B2SD/M/B001BK90ZO.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76792695,
			"label" :       "42",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5A/M/B001BK8UQE.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK8UQE",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5A",
			"description" : "Size 5 Merrow straight needle",
			"tapered" :     "Standard",
			"linear" :      "Straight",
			"groove" :      "Standard",
			"name" :        "5A",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5A/M/B001BK8UQE.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793547,
			"label" :       "53",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-7SDT/M/B001BK7CPY.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK7CPY",
			"size" :        "Class 7",
			"metric" :      130,
			"point" :       "Standard",
			"picname" :     "7D",
			"description" : "Size 7 Merrow curved needle with a scarf and a tapered blade.  Recommended for use on heavy knit material and for butt seaming medium weight fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 7SD needle.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "7SDT",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-7SDT/M/B001BK7CPY.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793902,
			"label" :       "64",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A4BDF/M/B001E27QPU.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E27QPU",
			"size" :        "Class A",
			"metric" :      100,
			"point" :       "Ball Point",
			"picname" :     "A4BDF",
			"description" : "Size 4 Merrow curved needle with a bulge eye and ball point.  Recommended for use in a two-needle (style 60 or 100) sewing machine on mens medium-heavy weight socks.  The bulge eye is designed for applications where fabric closes around the needle after penetration and affects proper thread release. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Bulge Eye",
			"name" :        "A4BDF",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A4BDF/M/B001E27QPU.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791813,
			"label" :         "18",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1SDT/M/B001BK75SI.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK75SI",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Standard",
			"picname" :       "1SDT",
			"description" :   "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.   Tapered blade makes it more durable than the 1SD and 1D needles.",
			"tapered" :       "Tapered Blade",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1SDT",
			"scarf" :         "Scarf",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1SDT/M/B001BK75SI.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792550,
			"label" :       "41",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5E9U",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Ball Point",
			"picname" :     "4D",
			"description" : "Size 4 Merrow curved needle with a scarf, ball point, and tapered blade.  Recommended for use with medium to heavy fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts. Tapered blade makes it more durable than the 4SD needle.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "4SDTF",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792434,
			"label" :       "27",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-3S/M/B001BK5DPA.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5DPA",
			"size" :        "Class 3",
			"metric" :      90,
			"point" :       "Standard",
			"picname" :     "3 STRAIGHT",
			"description" : "Size 3 Merrow straight needle.",
			"tapered" :     "Standard",
			"linear" :      "Straight",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "3S",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-3S/M/B001BK5DPA.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793874,
			"label" :       "62",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A2SD/M/B001BK9Z36.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK9Z36",
			"size" :        "Class A",
			"metric" :      80,
			"point" :       "Standard",
			"picname" :     "A2SD",
			"description" : "Size 2 Merrow curved needle with a scarf, for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks. The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A2SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A2SD/M/B001BK9Z36.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792550,
			"label" :       "40",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5E9U",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Standard",
			"picname" :     "4D",
			"description" : "Size 4 Merrow curved needle with a scarf and tapered blade.  Recommended for use with medium to heavy fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 4SD needle.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "4SDT",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793547,
			"label" :       "52",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-7SDT/M/B001BK7CPY.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK7CPY",
			"size" :        "Class 7",
			"metric" :      130,
			"point" :       "Standard",
			"picname" :     "7D",
			"description" : "Size 7 Merrow curved needle with a scarf above the eye of the needle.  Recommended for use on heavy knit material and for butt seaming medium weight fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "7SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-7SDT/M/B001BK7CPY.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792550,
			"label" :       "38",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5E9U",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Standard",
			"picname" :     "4D",
			"description" : "Size 4 Merrow curved needle with a scarf. Recommended for medium weight fabric and emblems.  The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "4SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791222,
			"label" :         "5",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-0D/M/B001BK73C6.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK73C6",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        65,
			"point" :         "Standard",
			"picname" :       "0D",
			"description" :   "Size 0 Merrow curved needle.  Recommended for nylon tricot, lingerie, and other delicate fabric.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "0D",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-0D/M/B001BK73C6.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791187,
			"label" :         "1",
			"caturl" :        "Merrow-Sewing-Needle-000D/M/B0018ZS1PM.htm",
			"shanklength" :   "Standard",
			"asin" :          "B0018ZS1PM",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        55,
			"point" :         "Standard",
			"picname" :       "000D",
			"description" :   "Size 000, the thinnest Merrow curved needle. Recommended for lingerie and delicate material. Not as durable as the 000DT, but creates a smaller needle hole.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "000D",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-000D/M/B0018ZS1PM.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791223,
			"label" :         "6",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-0DE/M/B001BK73DA.htm",
			"shanklength" :   "Short Shank",
			"asin" :          "B001BK73DA",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        65,
			"point" :         "Standard",
			"picname" :       "0DE",
			"description" :   "Size 0 Merrow curved needle.  Recommended for lingerie and lightweight fabric. This needle has a short shank which facilitates a clean release from sewn material.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "0DE",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-0DE/M/B001BK73DA.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791195,
			"label" :         "4",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-00DE/M/B001BK5A7G.htm",
			"shanklength" :   "Short Shank",
			"asin" :          "B001BK5A7G",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        60,
			"point" :         "Standard",
			"picname" :       "00DE",
			"description" :   "Size 00 Merrow curved needle recommended for lingerie and delicate fabric.  This needle has a short shank which facilitates a clean release from fabric.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "00DE",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-00DE/M/B001BK5A7G.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (B) designation",
			"ot" :          76794437,
			"label" :       "71",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-B0SDT/M/B001BK9Z68.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK9Z68",
			"size" :        "Class B",
			"metric" :      65,
			"point" :       "Standard",
			"picname" :     "B0SDT",
			"description" : "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on ladies hosiery. This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.  Tapered blade makes it more durable than the BODE needle.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "B0SDT",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-B0SDT/M/B001BK9Z68.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793679,
			"label" :       "57",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-8SD/M/B0019QRA4S.htm",
			"shanklength" : "Standard",
			"asin" :        "B0019QRA4S",
			"size" :        "Class 8",
			"metric" :      150,
			"point" :       "Standard",
			"picname" :     "8SD",
			"description" : "Size 8 Merrow curved needle with a scarf and tapered blade.  Recommended for butt seaming woven fabrics and heavy knits. The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The tapered blade makes it more durable than the 8D needle.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "8SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-8SD/M/B0019QRA4S.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793935,
			"label" :       "68",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A5DF/M/B001E2488I.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E2488I",
			"size" :        "Class A",
			"metric" :      110,
			"point" :       "Ball Point",
			"picname" :     "A5DF",
			"description" : "Size 5 Merrow curved needle with a ball point, for use in a two-needle (style 60 or 100) sewing machine.  Recommended for use on heavy weight socks. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A5DF",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A5DF/M/B001E2488I.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792196,
			"label" :       "24",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-2SD/M/B001BK16Z6.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK16Z6",
			"size" :        "Class 2",
			"metric" :      80,
			"point" :       "Standard",
			"picname" :     "2SD",
			"description" : "Size 2 Merrow curved needle with a scarf.  Recommended for use with light knit fabric or lingerie.  The scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "2SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-2SD/M/B001BK16Z6.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792550,
			"label" :       "39",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5E9U",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Ball Point",
			"picname" :     "4D",
			"description" : "Size 4 Merrow curved needle with a scarf and ball point.  Recommended for use with medium weight fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "4SDF",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791808,
			"label" :         "13",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1D/M/B001BK8SUW.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK8SUW",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Standard",
			"picname" :       "1D",
			"description" :   "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1D",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1D/M/B001BK8SUW.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "KOOLTORR",
			"shank" :       "Standard",
			"ot" :          76792419,
			"label" :       "28",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-3D-KOOLTORR/M/B001E27QMS.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E27QMS",
			"size" :        "Class 3",
			"metric" :      90,
			"point" :       "Standard",
			"picname" :     "3D_KOOLTORR",
			"description" : "Size 3 Merrow curved needle.  Recommended for light to medium weight fabric.  The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "3DK",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-3D-KOOLTORR/M/B001E27QMS.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792194,
			"label" :       "23",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-2DF/M/B001BK76R8.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK76R8",
			"size" :        "Class 2",
			"metric" :      80,
			"point" :       "Ball Point",
			"picname" :     "2DF",
			"description" : "Size 2 Merrow curved needle with a ball point.  Recommended for use with light knit fabric or lingerie. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "2DF",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-2DF/M/B001BK76R8.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792698,
			"label" :       "45",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5D/M/B001BK1890.htm",
			"shanklength" : "Short Shank",
			"asin" :        "B001BK1890",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5DE",
			"description" : "Size 5 Merrow curved needle with a short shank.  Recommended for medium-heavy fabric.  The short shank facilitates a clean release from fabric.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "5DE",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5D/M/B001BK1890.htm"
		},
		{
			"shanklength" : "Standard",
			"shank" :       "flat on both sides (A) designation",
			"name" :        "A5DK",
			"scarf" :       "Standard",
			"coating" :     "KOOLTORR",
			"metric" :      110,
			"picname" :     "A5D_KOOLTORR",
			"groove" :      "Standard",
			"linear" :      "Curved",
			"type" :        "Item",
			"label" :       "67",
			"point" :       "Standard",
			"description" : "Size 5 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Recommended for use on heavy weight socks. The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"tapered" :     "Standard",
			"size" :        "Class A"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791225,
			"label" :         "8",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-0DT/M/B001BK73EO.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK73EO",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        65,
			"point" :         "Standard",
			"picname" :       "0DT",
			"description" :   "Size 0 Merrow curved needle with a tapered blade.  Recommended for nylon tricot, lingerie, and other delicate fabric.  .   Tapered blade makes the needle more durable than the 0D needle.",
			"tapered" :       "Tapered Blade",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "0DT",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-0DT/M/B001BK73EO.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792557,
			"label" :       "33",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4S/M/B001BK39ZG.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK39ZG",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Standard",
			"picname" :     "4S",
			"description" : "Size 4 Merrow straight needle.",
			"tapered" :     "Standard",
			"linear" :      "Straight",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "4S",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4S/M/B001BK39ZG.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791188,
			"label" :         "2",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-000DT/M/B001BK35Z0.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK35Z0",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        55,
			"point" :         "Standard",
			"picname" :       "000DT",
			"description" :   "Size 000, the thinnest Merrow curved needle. Recommended for lingerie and delicate material. Tapered blade makes it more durable than the 000D needle.",
			"tapered" :       "Tapered Blade",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "000DT",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-000DT/M/B001BK35Z0.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793547,
			"label" :       "51",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-7SDT/M/B001BK7CPY.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK7CPY",
			"size" :        "Class 7",
			"metric" :      130,
			"point" :       "Standard",
			"picname" :     "7D",
			"description" : "Size 7 Merrow curved needle.  Recommended for heavy knit fabric or for butt seaming medium weight fabric.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "7D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-7SDT/M/B001BK7CPY.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793311,
			"label" :       "50",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-6DT/M/B001BK5HCO.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5HCO",
			"size" :        "Class 6",
			"metric" :      120,
			"point" :       "Standard",
			"picname" :     "6D",
			"description" : "Size 6 Merrow curved needle with a tapered blade.  Recommended for use on heavy knit material and for butt seaming light fabric.  The tapered blade makes it more durable than the 7D needle.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "6DT",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-6DT/M/B001BK5HCO.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76800886,
			"label" :       "26",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-2SDT/M/B001BK8TPG.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK8TPG",
			"size" :        "Class 2",
			"metric" :      80,
			"point" :       "Standard",
			"picname" :     "2SDT",
			"description" : "Size 2 Merrow curved needle.  Recommended for use on light to medium weight knits. Tapered blade makes it more durable than the 2SD needle.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "2SDT",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-2SDT/M/B001BK8TPG.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791814,
			"label" :         "19",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1SDTF/M/B001BK38KM.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK38KM",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Ball Point",
			"picname" :       "1SDTF",
			"description" :   "Size 1 Merrow curved needle with a scarf, tapered blade and ball point.  Recommended for use on light knits and tightly knit material. The scarf, flat spot above the eye, facilitates the lower looper/needle transition  Tapered blade makes it more durable than the 1SD and 1D needles.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :       "Tapered Blade",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1SDTF",
			"scarf" :         "Scarf",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1SDTF/M/B001BK38KM.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792540,
			"label" :       "36",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4D/M/B001BK77D6.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK77D6",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Standard",
			"picname" :     "4D",
			"description" : "Size 4 Merrow curved needle.  Recommended for use on medium weight fabrics and emblems.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "4D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4D/M/B001BK77D6.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791815,
			"label" :         "21",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1SMF/M/B001BK5CS8.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK5CS8",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Ball Point",
			"picname" :       "1SMF",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1SMF",
			"scarf" :         "Scarf",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1SMF/M/B001BK5CS8.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793903,
			"label" :       "65",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A4D/M/B001BK7DYE.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK7DYE",
			"size" :        "Class A",
			"metric" :      100,
			"point" :       "Standard",
			"picname" :     "A4D",
			"description" : "Size 4 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium-heavy weight socks.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A4D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A4D/M/B001BK7DYE.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76794435,
			"label" :       "70",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-B0DE/M/B001E25QM0.htm",
			"shanklength" : "Short Shank",
			"asin" :        "B001E25QM0",
			"size" :        "Class B",
			"metric" :      65,
			"point" :       "Standard",
			"picname" :     "B0DE",
			"description" : "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 45).  This needle has a short shank which facilitates a clean release from fabric.  Often used on delicate ladies hosiery.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Bulge",
			"name" :        "B0DE",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-B0DE/M/B001E25QM0.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791224,
			"label" :         "7",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-0DF/M/B001BK1426.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK1426",
			"size" :          "Class 0",
			"fabric_weight" : "Light",
			"metric" :        65,
			"point" :         "Ball Point",
			"picname" :       "0DE",
			"description" :   "Size 0 Merrow curved needle with a ball point.  Recommended for lingerie and lightweight fabric. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "0DF",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-0DF/M/B001BK1426.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792435,
			"label" :       "29",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-3SD/M/B001BK76WS.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK76WS",
			"size" :        "Class 3",
			"metric" :      90,
			"point" :       "Standard",
			"picname" :     "3SD",
			"description" : "Size 3 Merrow curved needle with a scarf. Recommended for light and medium weight fabric.  The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "3SD",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-3SD/M/B001BK76WS.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792548,
			"label" :       "37",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4DF/M/B001BK39YC.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK39YC",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Ball Point",
			"picname" :     "4DF",
			"description" : "Size 4 Merrow curved needle with a ball point.  This needle is recommended for use on medium weight fabrics and emblems. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "4DF",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4DF/M/B001BK39YC.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "KOOLTORR",
			"shank" :       "Standard",
			"ot" :          76792699,
			"label" :       "44",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5D_KOOLTORR/M/B001BK5EXQ.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5EXQ",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5D_KOOLTORR",
			"description" : "Size 5 Merrow curved needle.  Recommended for medium to heavy material.  The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "5DK",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5D_KOOLTORR/M/B001BK5EXQ.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792195,
			"label" :       "22",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-2S/M/B001BK76RI.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK76RI",
			"size" :        "Class 2",
			"metric" :      80,
			"point" :       "Standard",
			"picname" :     "2S",
			"description" : "Size 2 Merrow straight needle.",
			"tapered" :     "Standard",
			"linear" :      "Straight",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "2S",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-2S/M/B001BK76RI.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792436,
			"label" :       "30",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-3SDF/M/B001BK39J2.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK39J2",
			"size" :        "Class 3",
			"metric" :      90,
			"point" :       "Ball Point",
			"picname" :     "3SDF",
			"description" : "Size 3 Merrow curved needle with a scarf and ball point.  Recommended for use with light and medium knit fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "3SDF",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-3SDF/M/B001BK39J2.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791810,
			"label" :         "15",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1DF/M/B001BK8SW0.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK8SW0",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Ball Point",
			"picname" :       "1DF",
			"description" :   "Size 1 Merrow curved needle with a ball point.  Recommended for use on light knits and tightly knit material.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1DF",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1DF/M/B001BK8SW0.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791811,
			"label" :         "16",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1SD/M/B001BK38JI.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BK38JI",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Standard",
			"picname" :       "1SD",
			"description" :   "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.  This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1SD",
			"scarf" :         "Scarf",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1SD/M/B001BK38JI.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793902,
			"label" :       "66",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A4BDF/M/B001E27QPU.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E27QPU",
			"size" :        "Class A",
			"metric" :      100,
			"point" :       "Ball Point",
			"picname" :     "A4DF",
			"description" : "Size 4 Merrow curved needle with a ball point, for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium-heavy weight socks.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A4DF",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A4BDF/M/B001E27QPU.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (B) designation",
			"ot" :          76794444,
			"label" :       "74",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-B1SDT/M/B001BK90ZE.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK90ZE",
			"size" :        "Class B",
			"metric" :      70,
			"point" :       "Standard",
			"picname" :     "B1SDT",
			"description" : "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.   This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the B1DE and BiSD needles.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "B1SDT",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-B1SDT/M/B001BK90ZE.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793831,
			"label" :       "59",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A1D/M/B001E29RPC.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E29RPC",
			"size" :        "Class A",
			"metric" :      70,
			"point" :       "Standard",
			"picname" :     "A1D",
			"description" : "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 60 or 100).  Often used on mens medium weight socks.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A1D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A1D/M/B001E29RPC.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          76793900,
			"label" :       "63",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A3D/M/B001BK7DXA.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK7DXA",
			"size" :        "Class A",
			"metric" :      90,
			"point" :       "Standard",
			"picname" :     "A3D",
			"description" : "Size 3 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A3D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A3D/M/B001BK7DXA.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792698,
			"label" :       "49",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5D/M/B001BK1890.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK1890",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5D",
			"description" : "Size 5 Merrow curved needle with a scarf above the eye of the needle.  Recommended for use on heavy knit material and for butt seaming light fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. Tapered blade makes it more durable than the 5D and 5SD needles.",
			"tapered" :     "Tapered Blade",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "5SDT",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5D/M/B001BK1890.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792439,
			"label" :       "32",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-3SDT/M/B001BK5DPU.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5DPU",
			"size" :        "Class 3",
			"metric" :      90,
			"point" :       "Standard",
			"picname" :     "3SM",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "3SM",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-3SDT/M/B001BK5DPU.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791301,
			"label" :         "10",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-10H/M/B001BVRK2S.htm",
			"shanklength" :   "Standard",
			"asin" :          "B001BVRK2S",
			"size" :          "Class 10",
			"fabric_weight" : "Light",
			"metric" :        200,
			"point" :         "Standard",
			"picname" :       "10H",
			"description" :   "Size 10 Merrow straight needle.",
			"tapered" :       "Standard",
			"linear" :        "Straight",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "10H",
			"scarf" :         "Standard",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-10H/M/B001BVRK2S.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76793673,
			"label" :       "54",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-8D/M/B001BK5KVC.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5KVC",
			"size" :        "Class 8",
			"metric" :      150,
			"point" :       "Standard",
			"picname" :     "8SD",
			"description" : "Size 8 Merrow curved needle.  Recommended for butt seaming woven fabric and heavy knits.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "8D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-8D/M/B001BK5KVC.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792197,
			"label" :       "25",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-2SDFE/M/B001E2485G.htm",
			"shanklength" : "Short Shank",
			"asin" :        "B001E2485G",
			"size" :        "Class 2",
			"metric" :      80,
			"point" :       "Ball Point",
			"picname" :     "2SDFE",
			"description" : "Size 2 Merrow curved needle with a scarf, ball point, and short shank.  Recommended for use with light knit fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition. The ball point relieves fabric at the penetration point and prevents needle cuts.  This needle has a short shank which helps a clean release from fabric.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "2SDFE",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-2SDFE/M/B001E2485G.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792704,
			"label" :       "47",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5S/M/B001BK3AN2.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK3AN2",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5S",
			"description" : "Size 5 Merrow straight needle",
			"tapered" :     "Standard",
			"linear" :      "Straight",
			"groove" :      "Standard",
			"eye" :         "Standard",
			"name" :        "5S",
			"scarf" :       "Scarf",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5S/M/B001BK3AN2.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (B) designation",
			"ot" :          76794433,
			"label" :       "69",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-B00DE/M/B001BKC1AA.htm",
			"shanklength" : "Short",
			"asin" :        "B001BKC1AA",
			"size" :        "Class B",
			"metric" :      60,
			"point" :       "Standard",
			"picname" :     "B00DE",
			"description" : "Size 00 Merrow curved needle for use in a two-needle sewing machine (style 45).  This needle has a short shank which facilitates a clean release from fabric.  Often used on the most delicate ladies hosiery.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "B00DE",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-B00DE/M/B001BKC1AA.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "flat on both sides (A) designation",
			"ot" :          79793831,
			"label" :       "60",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-A2D/M/B001E334ZK.htm",
			"shanklength" : "Standard",
			"asin" :        "B001E334ZK",
			"size" :        "Class A",
			"metric" :      80,
			"point" :       "Standard",
			"picname" :     "A2D",
			"description" : "Size 2 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"name" :        "A2D",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-A2D/M/B001E334ZK.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792538,
			"label" :       "35",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-4BDF/M/B001BK5E7C.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK5E7C",
			"size" :        "Class 4",
			"metric" :      100,
			"point" :       "Ball Point",
			"picname" :     "4BDF",
			"description" : "Size 4 Merrow curved needle with a bulge eye and ball point.  This needle is recommended for use on medium weight fabrics and emblems. The bulge eye is designed for applications where fabric closes around the needle after penetration and affects proper thread release. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Standard",
			"eye" :         "Bulge Eye",
			"name" :        "4BDF",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-4BDF/M/B001BK5E7C.htm"
		},
		{
			"type" :          "Item",
			"coating" :       "Standard",
			"shank" :         "Standard",
			"ot" :            76791812,
			"label" :         "17",
			"caturl" :        "http://catalog.merrow.com/Merrow-Sewing-Needle-1SDFE/M/B001BK169C.htm",
			"shanklength" :   "Short Shank",
			"asin" :          "B001BK169C",
			"size" :          "Class 1",
			"fabric_weight" : "Light",
			"metric" :        70,
			"point" :         "Ball Point",
			"picname" :       "1SDFE",
			"description" :   "Size 1 Merrow curved needle with scarf, ball point, and short shank.  Recommended for use on light knits and tightly knit material.  This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.  This needle has a short shank which facilitates a clean release from fabric.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"tapered" :       "Standard",
			"linear" :        "Curved",
			"groove" :        "Standard",
			"eye" :           "Standard",
			"name" :          "1SDFE",
			"scarf" :         "Scarf",
			"amznurl" :       "http://store.merrow.com/Merrow-Sewing-Needle-1SDFE/M/B001BK169C.htm"
		},
		{
			"type" :        "Item",
			"coating" :     "Standard",
			"shank" :       "Standard",
			"ot" :          76792701,
			"label" :       "46",
			"caturl" :      "http://catalog.merrow.com/Merrow-Sewing-Needle-5DJ/M/B001BK8US2.htm",
			"shanklength" : "Standard",
			"asin" :        "B001BK8US2",
			"size" :        "Class 5",
			"metric" :      110,
			"point" :       "Standard",
			"picname" :     "5DJ",
			"description" : "Size 5 Merrow curved needle with a specially designed groove on the inside of the blade curve.  Recommended for use on wash cloths or loose wovens.  The special groove prevents a terry loop from pulling the needle thread away from the lower looper.",
			"tapered" :     "Standard",
			"linear" :      "Curved",
			"groove" :      "Groove on Needle",
			"eye" :         "Standard",
			"name" :        "5DJ",
			"scarf" :       "Standard",
			"amznurl" :     "http://store.merrow.com/Merrow-Sewing-Needle-5DJ/M/B001BK8US2.htm"
		}
	],
	"properties" : {
		"metric" : {
			"valueType" : "number"
		},
		"ot" :     {
			"valueType" : "number"
		}
	}
}