{
	"items" : [
		{
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "B0SDT",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-B0SDT/M/B001BK9Z68.htm",
			"ot" :               "76794437",
			"Size" :             "B",
			"asin" :             "B001BK9Z68",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK9Z68",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Metric+Size" :      "65",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "100",
			"ot" :               "76792537",
			"label" :            "B001BK5E6I",
			"Eye+Type" :         "Bulge Eye",
			"asin" :             "B001BK5E6I",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-4BD/M/B001BK5E6I.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "4",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 4 Merrow curved needle with a bulge eye.  This needle is recommended for use on medium width fabrics and emblems. The bulge eye is designed for applications where fabric closes around the needle after penetration and affects proper thread release.",
			"name" :             "4BD"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "65",
			"ot" :               "76791224",
			"label" :            "B001BK1426",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK1426",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-0DF/M/B001BK1426.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 0 Merrow curved needle with a ball point.  Recommended for lingerie and lightweight fabric. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "0DF"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "150",
			"ot" :               "76793679",
			"label" :            "B0019QRA4S",
			"Eye+Type" :         "Standard",
			"asin" :             "B0019QRA4S",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-8SD/M/B0019QRA4S.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "8",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "8SD"
		},
		{
			"Description" :      "1",
			"name" :             "Straight",
			"Shank+Length" :     "Standard",
			"ot" :               "Size 1 Merrow straight needle.",
			"Size" :             "Standard",
			"asin" :             "1 STRAIGHT",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "1 STRAIGHT",
			"Linear" :           "70",
			"Type+of+Coating" :  "Standard",
			"Metric+Size" :      "Standard",
			"Shank+Roundness" :  "Standard"
		},
		{
			"Description" :      "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 60 or 100).  Often used on mens socks.",
			"name" :             "A0D",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A0D/M/B001E225PG.htm",
			"ot" :               "76793725",
			"Size" :             "A",
			"asin" :             "B001E225PG",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001E225PG",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "65",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"ot" :               "76791811",
			"label" :            "B001BK38JI",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK38JI",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1SD/M/B001BK38JI.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.  This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"name" :             "1SD"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "200",
			"ot" :               "76791301",
			"label" :            "B001BVRK2S",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BVRK2S",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-10H/M/B001BVRK2S.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "10",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 10 Merrow straight needle.",
			"name" :             "10H"
		},
		{
			"Description" :      "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 60 or 100).  Often used on mens medium weight socks.",
			"name" :             "A1D",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A1D/M/B001E29RPC.htm",
			"ot" :               "76793831",
			"Size" :             "A",
			"asin" :             "B001E29RPC",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001E29RPC",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Metric+Size" :      "100",
			"ot" :               "76793902",
			"label" :            "B001E27QPU",
			"Eye+Type" :         "Bulge Eye",
			"asin" :             "B001E27QPU",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A4BDF/M/B001E27QPU.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "A",
			"Type+of+Coating" :  "Standard",
			"Description" :      "\"Size 4 Merrow curved needle with a ball point, for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium-heavy weight socks.  The ball point relieves fabric at the penetration point and prevents needle cuts.\"",
			"name" :             "A4DF"
		},
		{
			"Description" :      "\"Size 2 Merrow curved needle with a scarf, for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks. The scarf (flat spot) above the eye helps the lower looper/needle thread transition. \"",
			"name" :             "A2SD",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A2SD/M/B001BK9Z36.htm",
			"ot" :               "76793874",
			"Size" :             "A",
			"asin" :             "B001BK9Z36",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK9Z36",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Groove+on+Needle" : "Groove on Needle",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "110",
			"ot" :               "76792701",
			"label" :            "B001BK8US2",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK8US2",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-5DJ/M/B001BK8US2.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "5",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 5 Merrow curved needle with a specially designed groove on the inside of the blade curve.  Recommended for use on wash cloths or loose wovens.  The special groove prevents a terry loop from pulling the needle thread away from the lower looper.",
			"name" :             "5DJ"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "150",
			"ot" :               "76793676",
			"label" :            "B001BK7DK8",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK7DK8",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-8DG/M/B001BK7DK8.htm",
			"Point+Type" :       "Spear Point",
			"Linear" :           "Curved",
			"Size" :             "8",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 8 Merrow curved needle with a spear point.  Recommended for butt seaming tough fabrics.  The spear point blade is angled instead of rounded which allows it to easily penetrate dense fabrics.",
			"name" :             "8DG"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Short Shank",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"ot" :               "76791809",
			"label" :            "B001E29RMU",
			"Eye+Type" :         "Standard",
			"asin" :             "B001E29RMU",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1DE/M/B001E29RMU.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.   This needle has a short shank which facilitates a clean release from fabric.",
			"name" :             "1DE"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "90",
			"ot" :               "76792434",
			"label" :            "B001BK5DPA",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5DPA",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-3S/M/B001BK5DPA.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "3",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 3 Merrow straight needle.",
			"name" :             "3 STRAIGHT"
		},
		{
			"Description" :      "Size 5 Merrow straight needle",
			"name" :             "5A",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-5A/M/B001BK8UQE.htm",
			"ot" :               "76792695",
			"Size" :             "5",
			"asin" :             "B001BK8UQE",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK8UQE",
			"Linear" :           "Straight",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "60",
			"ot" :               "76791194",
			"label" :            "B001BK5A6M",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5A6M",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-00D/M/B001BK5A6M.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "\"Size 00 Merrow curved needle, recommended for nylon tricot, lingerie, and other delicate fabric.  \"",
			"name" :             "00D"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "90",
			"ot" :               "76792435",
			"label" :            "B001BK76WS",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK76WS",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-3SD/M/B001BK76WS.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "3",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 3 Merrow curved needle with a scarf. Recommended for light and medium weight fabric.  The scarf (flat spot) above the eye helps the lower looper/needle thread transition.",
			"name" :             "3SD"
		},
		{
			"Description" :      "A",
			"name" :             "Curved",
			"Shank+Length" :     "Standard",
			"ot" :               "###############################################################################################################################################################################################################################################################",
			"Size" :             "KOOLTORR Coating",
			"asin" :             "A5D KOOLTORR",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "A5D KOOLTORR",
			"Linear" :           "110",
			"Metric+Size" :      "flat on both sides (A) designation",
			"Shank+Roundness" :  "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "90",
			"ot" :               "76792436",
			"label" :            "B001BK39J2",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK39J2",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-3SDF/M/B001BK39J2.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "3",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "3SDF"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "65",
			"ot" :               "76791222",
			"label" :            "B001BK73C6",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK73C6",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-0D/M/B001BK73C6.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "\"Size 0 Merrow curved needle.  Recommended for nylon tricot, lingerie, and other delicate fabric.  \"",
			"name" :             "0D"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Short Shank",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "65",
			"ot" :               "76791223",
			"label" :            "B001BK73DA",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK73DA",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-0DE/M/B001BK73DA.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 0 Merrow curved needle.  Recommended for lingerie and lightweight fabric. This needle has a short shank which facilitates a clean release from sewn material.",
			"name" :             "0DE"
		},
		{
			"Description" :      "Size 00 Merrow curved needle for use in a two-needle sewing machine (style 45).  This needle has a short shank which facilitates a clean release from fabric.  Often used on the most delicate ladies hosiery.",
			"name" :             "B00DE",
			"Shank+Length" :     "Short",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-B00DE/M/B001BKC1AA.htm",
			"ot" :               "76794433",
			"Size" :             "B",
			"asin" :             "B001BKC1AA",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BKC1AA",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "60",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 2 Merrow curved needle with a ball point for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "A2DF",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A2DF/M/B001E29RQ6.htm",
			"ot" :               "76793873",
			"Size" :             "A",
			"asin" :             "B001E29RQ6",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001E29RQ6",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "110",
			"ot" :               "76792699",
			"label" :            "B001BK5EXQ",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5EXQ",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-5D_KOOLTORR/M/B001BK5EXQ.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "5",
			"Type+of+Coating" :  "KOOLTORR Coating",
			"Description" :      "Size 5 Merrow curved needle.  Recommended for medium to heavy material.  The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"name" :             "5D KOOLTORR"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "150",
			"ot" :               "76793678",
			"label" :            "B001BK5KY4",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5KY4",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-8S/M/B001BK5KY4.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "8",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 8 Merrow straight needle.",
			"name" :             "8S"
		},
		{
			"Description" :      "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.   This needle has a scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"name" :             "B1SD",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-B1SD/M/B001BK90X6.htm",
			"ot" :               "76794443",
			"Size" :             "B",
			"asin" :             "B001BK90X6",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK90X6",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 2 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks.",
			"name" :             "A2D",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A2D/M/B001E334ZK.htm",
			"ot" :               "79793831",
			"Size" :             "A",
			"asin" :             "B001E334ZK",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001E334ZK",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"ot" :               "76791808",
			"label" :            "B001BK8SUW",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK8SUW",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1D/M/B001BK8SUW.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.",
			"name" :             "1D"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "100",
			"ot" :               "76792540",
			"label" :            "B001BK77D6",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK77D6",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-4D/M/B001BK77D6.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "4",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 4 Merrow curved needle.  Recommended for use on medium weight fabrics and emblems.",
			"name" :             "4D"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "80",
			"ot" :               "76792196",
			"label" :            "B001BK16Z6",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK16Z6",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-2SD/M/B001BK16Z6.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "2",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 2 Merrow curved needle with a scarf.  Recommended for use with light knit fabric or lingerie.  The scarf (flat spot) above the eye to facilitate the lower looper/needle transition.",
			"name" :             "2SD"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "100",
			"ot" :               "76792548",
			"label" :            "B001BK39YC",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK39YC",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-4DF/M/B001BK39YC.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "4",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 4 Merrow curved needle with a ball point.  This needle is recommended for use on medium weight fabrics and emblems. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "4DF"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "100",
			"ot" :               "76792550",
			"label" :            "B001BK5E9U",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5E9U",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-4DT/M/B001BK5E9U.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "4",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "4SDTF"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "80",
			"ot" :               "76792195",
			"label" :            "B001BK76RI",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK76RI",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-2S/M/B001BK76RI.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "2",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 2 Merrow straight needle.",
			"name" :             "2 STRAIGHT"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "100",
			"ot" :               "76792538",
			"label" :            "B001BK5E7C",
			"Eye+Type" :         "Bulge Eye",
			"asin" :             "B001BK5E7C",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-4BDF/M/B001BK5E7C.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "4",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "4BDF"
		},
		{
			"Description" :      "Size 4 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium-heavy weight socks.",
			"name" :             "A4D",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A4D/M/B001BK7DYE.htm",
			"ot" :               "76793903",
			"Size" :             "A",
			"asin" :             "B001BK7DYE",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK7DYE",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "100",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Description" :      "Size 3 Merrow curved needle for use in a two-needle (style 60 or 100) sewing machine.  Often used on mens medium weight socks.",
			"name" :             "A3D",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A3D/M/B001BK7DXA.htm",
			"ot" :               "76793900",
			"Size" :             "A",
			"asin" :             "B001BK7DXA",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK7DXA",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "90",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"ot" :               "76791810",
			"label" :            "B001BK8SW0",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK8SW0",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1DF/M/B001BK8SW0.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 1 Merrow curved needle with a ball point.  Recommended for use on light knits and tightly knit material.  The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "1DF"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Short Shank",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"ot" :               "76791812",
			"label" :            "B001BK169C",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK169C",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1SDFE/M/B001BK169C.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "1SDFE"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "150",
			"ot" :               "76793673",
			"label" :            "B001BK5KVC",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5KVC",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-8D/M/B001BK5KVC.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "8",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 8 Merrow curved needle.  Recommended for butt seaming woven fabric and heavy knits.",
			"name" :             "8D"
		},
		{
			"name" :             "1SMF",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1SMF/M/B001BK5CS8.htm",
			"ot" :               "76791815",
			"Size" :             "1",
			"asin" :             "B001BK5CS8",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK5CS8",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Scarf"
		},
		{
			"Description" :      "Size 11 Merrow straight needle.",
			"name" :             "11 STRAIGHT",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-11/M/B001BK8Q2C.htm",
			"ot" :               "76791381",
			"Size" :             "11",
			"asin" :             "B001BK8Q2C",
			"Eye+Type" :         "Standard",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK8Q2C",
			"Linear" :           "Straight",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Shank+Roundness" :  "Standard",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"ot" :               "76791813",
			"label" :            "B001BK75SI",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK75SI",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1SDT/M/B001BK75SI.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 1 Merrow curved needle.  Recommended for use on light knits and tightly knit material.   Tapered blade makes it more durable than the 1SD and 1D needles.",
			"name" :             "1SDT"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Short Shank",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "80",
			"ot" :               "76792197",
			"label" :            "B001E2485G",
			"Eye+Type" :         "Standard",
			"asin" :             "B001E2485G",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-2SDFE/M/B001E2485G.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "2",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "2SDFE"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "200",
			"ot" :               "76791302",
			"label" :            "B001BVLOOS",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BVLOOS",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-10S/M/B001BVLOOS.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "10",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 10 Merrow straight needle.",
			"name" :             "10S"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Short Shank",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "60",
			"ot" :               "76791195",
			"label" :            "B001BK5A7G",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5A7G",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-00DE/M/B001BK5A7G.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 00 Merrow curved needle recommended for lingerie and delicate fabric.  This needle has a short shank which facilitates a clean release from fabric.",
			"name" :             "00DE"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "130",
			"ot" :               "76793547",
			"label" :            "B001BK7CPY",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK7CPY",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-7SDT/M/B001BK7CPY.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "7",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "7SDT"
		},
		{
			"Description" :      "\"Size 5 Merrow curved needle with a ball point, for use in a two-needle (style 60 or 100) sewing machine.  Recommended for use on heavy weight socks. The ball point relieves fabric at the penetration point and prevents needle cuts. \"",
			"name" :             "A5DF",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-A5DF/M/B001E2488I.htm",
			"ot" :               "76793935",
			"Size" :             "A",
			"asin" :             "B001E2488I",
			"Point+Type" :       "Ball Point",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001E2488I",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "110",
			"Shank+Roundness" :  "flat on both sides (A) designation",
			"Scarf" :            "Standard"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "90",
			"ot" :               "76792419",
			"label" :            "B001E27QMS",
			"Eye+Type" :         "Standard",
			"asin" :             "B001E27QMS",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-3D-KOOLTORR/M/B001E27QMS.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "3",
			"Type+of+Coating" :  "KOOLTORR Coating",
			"Description" :      "Size 3 Merrow curved needle.  Recommended for light to medium weight fabric.  The Kooltoor needle is designed reduce heat generated from needle penetration.  It causes less friction than a traditional needle.",
			"name" :             "3D KOOLTORR"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Short Shank",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "65",
			"ot" :               "76794435",
			"label" :            "B001E25QM0",
			"Eye+Type" :         "Bulge",
			"asin" :             "B001E25QM0",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-B0DE/M/B001E25QM0.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "B",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 0 Merrow curved needle for use in a two-needle sewing machine (style 45).  This needle has a short shank which facilitates a clean release from fabric.  Often used on delicate ladies hosiery.",
			"name" :             "B0DE"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "80",
			"ot" :               "76800886",
			"label" :            "B001BK8TPG",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK8TPG",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-2SDT/M/B001BK8TPG.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "2",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 2 Merrow curved needle.  Recommended for use on light to medium weight knits. Tapered blade makes it more durable than the 2SD needle.",
			"name" :             "2SDT"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "55",
			"ot" :               "76791187",
			"label" :            "B0018ZS1PM",
			"Eye+Type" :         "Standard",
			"asin" :             "B0018ZS1PM",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-000D/M/B0018ZS1PM.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "\"Size 000, the thinnest Merrow curved needle. Recommended for lingerie and delicate material. Not as durable as the 000DT, but creates a smaller needle hole.   \"",
			"name" :             "000D"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "120",
			"ot" :               "76793311",
			"label" :            "B001BK5HCO",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5HCO",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-6DT/M/B001BK5HCO.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "6",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 6 Merrow curved needle with a tapered blade.  Recommended for use on heavy knit material and for butt seaming light fabric.  The tapered blade makes it more durable than the 7D needle.",
			"name" :             "6DT"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "70",
			"ot" :               "76791814",
			"label" :            "B001BK38KM",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK38KM",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-1SDTF/M/B001BK38KM.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "1",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "1SDTF"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "80",
			"ot" :               "76792194",
			"label" :            "B001BK76R8",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK76R8",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-2DF/M/B001BK76R8.htm",
			"Point+Type" :       "Ball Point",
			"Linear" :           "Curved",
			"Size" :             "2",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 2 Merrow curved needle with a ball point.  Recommended for use with light knit fabric or lingerie. The ball point relieves fabric at the penetration point and prevents needle cuts.",
			"name" :             "2DF"
		},
		{
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "B1SDT",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-B1SDT/M/B001BK90ZE.htm",
			"ot" :               "76794444",
			"Size" :             "B",
			"asin" :             "B001BK90ZE",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK90ZE",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Tapered Blade",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "110",
			"ot" :               "76792704",
			"label" :            "B001BK3AN2",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK3AN2",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-5S/M/B001BK3AN2.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "5",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 5 Merrow straight needle",
			"name" :             "5S"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "100",
			"ot" :               "76792557",
			"label" :            "B001BK39ZG",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK39ZG",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-4S/M/B001BK39ZG.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Straight",
			"Size" :             "4",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 4 Merrow straight needle.",
			"name" :             "4 STRAIGHT"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "90",
			"ot" :               "76792439",
			"label" :            "B001BK5DPU",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK5DPU",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-3SDT/M/B001BK5DPU.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "3",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "3SM"
		},
		{
			"Description" :      "\"Size 2 Merrow curved needle with a scarf, for use in a two-needle (style 45) sewing machine.  Often used on women\'s hosiery. The scarf (flat spot) above the eye helps the lower looper/needle thread transition. \"",
			"name" :             "B2SD",
			"Shank+Length" :     "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-B2SD/M/B001BK90ZO.htm",
			"ot" :               "76794446",
			"Size" :             "B",
			"asin" :             "B001BK90ZO",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK90ZO",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "80",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Scarf"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "110",
			"ot" :               "76792698",
			"label" :            "B001BK1890",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK1890",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-5D/M/B001BK1890.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "5",
			"Type+of+Coating" :  "Standard",
			"Description" :      "###############################################################################################################################################################################################################################################################",
			"name" :             "5SDT"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "65",
			"ot" :               "76791225",
			"label" :            "B001BK73EO",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK73EO",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-0DT/M/B001BK73EO.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "\"Size 0 Merrow curved needle with a tapered blade.  Recommended for nylon tricot, lingerie, and other delicate fabric.  .   Tapered blade makes the needle more durable than the 0D needle.\"",
			"name" :             "0DT"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Scarf",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "110",
			"ot" :               "76792705",
			"label" :            "B001BK8USW",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK8USW",
			"Tapered+Blade" :    "Standard",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-5SD/M/B001BK8USW.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "5",
			"Type+of+Coating" :  "Standard",
			"Description" :      "Size 5 Merrow curved needle with a scarf above the eye of the needle.  Recommended for use on heavy knit material and for butt seaming light fabric.  The scarf (flat spot) above the eye is designed to facilitate the lower looper/needle transition.",
			"name" :             "5SD"
		},
		{
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"Shank+Length" :     "Standard",
			"Scarf" :            "Standard",
			"Shank+Roundness" :  "Standard",
			"Metric+Size" :      "55",
			"ot" :               "76791188",
			"label" :            "B001BK35Z0",
			"Eye+Type" :         "Standard",
			"asin" :             "B001BK35Z0",
			"Tapered+Blade" :    "Tapered Blade",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-000DT/M/B001BK35Z0.htm",
			"Point+Type" :       "Standard",
			"Linear" :           "Curved",
			"Size" :             "0",
			"Type+of+Coating" :  "Standard",
			"Description" :      "\"Size 000, the thinnest Merrow curved needle. Recommended for lingerie and delicate material. Tapered blade makes it more durable than the 000D needle.\"",
			"name" :             "000DT"
		},
		{
			"Description" :      "Size 1 Merrow curved needle for use in a two-needle sewing machine (style 45).  Often used on women\'s hosiery.  This needle has a short shank which facilitates a clean release from fabric.",
			"name" :             "B1DE",
			"Shank+Length" :     "Short Shank",
			"AMZNURL" :          "http://02576.merrow.com/Merrow-Sewing-Needle-B1DE/M/B001BK7E2K.htm",
			"ot" :               "76794441",
			"Size" :             "B",
			"asin" :             "B001BK7E2K",
			"Point+Type" :       "Standard",
			"Groove+on+Needle" : "Standard",
			"type" :             "Item",
			"label" :            "B001BK7E2K",
			"Linear" :           "Curved",
			"Type+of+Coating" :  "Standard",
			"Tapered+Blade" :    "Standard",
			"Metric+Size" :      "70",
			"Shank+Roundness" :  "flat on both sides (B) designation",
			"Scarf" :            "Standard"
		}
	]
}