<?php
/***************************************************************************
								search_language.inc
							---------------------------
			created				: 13.02.2003
			edited				: -
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of search module

// start of main mavigation
$search_language['SEARCH_MENU']		= 'Search Menu';
$search_language['SEARCH_TICKETS'] 	= 'Search Tickets';
$search_language['SEARCH_USERS'] 	= 'Search User';
// end of main mavigation

// start of functions

// start of seach_tickets.php
$search_language['SEARCH_REDIRECT'] = 'Your search is in progress.';
$search_language['WRONG_SEARCH_REDIRECT'] = 'Your need to add a search term.';
$search_language['SEARCH_TICKETS_RESULTS'] = 'Hits in Tickets:';
$search_language['SEARCH_NOTES_RESULTS'] = 'Hits in Notes:';
// end of seach_tickets.php

// start of seach_users.php
$search_language['SEARCH_USERS_RESULTS'] = 'Hits in Users:';
// end of seach_users.php

// end of functions

// *************************************************************** \\

// start of templates

// start of templates - pages
// start of search_tickets.tpl
$search_language['SEARCH_TICKETS_TITLE'] = 'Support Logic - Search Tickets';
// end of slogic_tickets.tpl

// start of search_users.tpl
$search_language['SEARCH_USERS_TITLE'] = 'Support Logic - Search Users';
// end of slogic_users.tpl

// end of templates - pages

// start of templates - functions
// start of search_tickets.tpl
$search_language['SEARCH_FOR'] 			= 'Search for:';
$search_language['SEARCH_IN'] 			= 'Search in:';
$search_language['SEARCH_IN_TICKETS'] 	= 'Search Tickets';
$search_language['SEARCH_IN_NOTES'] 	= 'Search Notes';
$search_language['SEARCH_SUBMIT'] 		= 'Search!';
// end of search_tickets.tpl
// end of templates - functions

// end of templates
?>