<?php
/***************************************************************************
								stats_language.inc
							----------------------------
			created				: 11.04.2003
			edited				: 11.07.2003
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of stats module

// start of main mavigation
$stats_language['STATS_MENU'] = 'Stats Menu';
$stats_language['STATS_TOP10'] = 'TOP 10';
$stats_language['STATS_RAW'] = 'Raw Stats';
// end of main mavigation

// start of order titles
// end of order titles

// start of functions

// start of tickets_list_attachments.php
// end of tickets_list_attachments.php

// end of functions

// start of templates - pages
// start of stats_top10.tpl
$stats_language['STATS_TOP10_TITLE'] = 'Support Logic - TOP 10 Stats';
// end of stats_top10.tpl

// start of stats_raw.tpl
$stats_language['STATS_RAW_TITLE'] = 'Support Logic - Raw Stats';
// end of stats_raw.tpl

// start of stats_user_stats.tpl
$stats_language['STATS_USER_STATS_TITLE'] = 'Support Logic - User Stats';
// end of stats_user_stats.tpl

// start of stats_staff_stats.tpl
$stats_language['STATS_STAFF_STATS_TITLE'] = 'Support Logic - Staff Stats';
// end of stats_staff_stats.tpl

// end of templates - pages

// start of templates - functions
$stats_language['STATS_TOP10_USERS_TITLE'] = 'Top 10 - No. of Tickets by users';
$stats_language['STATS_TOP10_STAFF_TITLE'] = 'Top 10 - No. of Tickets by staff';
$stats_language['STATS_TOP10_USER_NOTES_TITLE'] = 'Top 10 - No. of Notes by users';
$stats_language['STATS_TOP10_STAFF_NOTES_TITLE'] = 'Top 10 - No. of Notes by staff';
$stats_language['STATS_TOP10_PRIORITY_TITLE'] = 'Top 10 - Ticket Priorities';
$stats_language['STATS_TOP10_CATEGORY_TITLE'] = 'Top 10 - Ticket Categories';
$stats_language['STATS_TOP10_NO_TICKETS'] = 'No. Tickets';
$stats_language['STATS_TOP10_NO_NOTES'] = 'No. Notes';

$stats_language['STATS_TOTAL_TICKETS'] = 'Total Tickets';
$stats_language['STATS_TOTAL_NOTES'] = 'Total Notes';
$stats_language['STATS_TOTAL_ANNOUNCEMENTS'] = 'Total Announcements';
$stats_language['STATS_TOTAL_ATTACHMENTS'] = 'Total Attachments';
$stats_language['STATS_TOTAL_CATEGORIES'] = 'Total Categories';
$stats_language['STATS_TOTAL_PRIORITIES'] = 'Total Priorities';
$stats_language['STATS_TOTAL_USERS'] = 'Total Users';
$stats_language['STATS_TOTAL_STAFF'] = 'Total Staff';

$stats_language['STATS_TOP_HOUR'] = 'Busiest Hour';
$stats_language['STATS_TOP_MONTH'] = 'Busiest Month';
$stats_language['STATS_TOP_YEAR'] = 'Busiest Year';

$stats_language['STATS_USER_STATS'] = 'User Stats of:';
$stats_language['STATS_STAFF_STATS'] = 'Staff Stats of:';

$stats_language['STATS_RAW_HOURS'] = 'Tickets sorted by hour of the day';
$stats_language['STATS_RAW_HOUR'] = 'Hour (00-23)';
$stats_language['STATS_PERCENT'] = 'Percent %';
$stats_language['STATS_RAW_DATE_TITLE'] = 'Tickets sorted by Month/Year';
$stats_language['STATS_RAW_DATE'] = 'Month . Year';
$stats_language['STATS_RAW_STAFF'] = 'Tickets sorted by staff';
// end of templates - functions
?>