<?php
/***************************************************************************
								tickets_language.inc
							----------------------------
			created				: 09.01.2003
			edited				: 11.07.2003
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of tickets module

// start of main mavigation
$tickets_language['TICKETS_MENU'] = 'Ticket Menu';
$tickets_language['TICKETS_LIST_TICKETS'] = 'Tickets';
$tickets_language['TICKETS_LIST_NOTES'] = 'Notes';
$tickets_language['TICKETS_LIST_CATEGORIES'] = 'Categories';
$tickets_language['TICKETS_LIST_PRIORITIES'] = 'Priorities';
$tickets_language['TICKETS_LIST_ATTACHMENTS'] = 'Attachments';
$tickets_language['TICKETS_LIST_PLACEHOLDERS'] = 'Placeholders';
// end of main mavigation

// start of order titles
$tickets_language['TICKETS_TICKET_ID'] = 'Ticket ID';
$tickets_language['TICKETS_FILENAME'] = 'Filename';
$tickets_language['TICKETS_FILETYPE'] = 'Filetype';
$tickets_language['TICKETS_FILESIZE'] = 'Filesize';
$tickets_language['TICKETS_SENT_DATE'] = 'Sent';
$tickets_language['TICKETS_WHO_UPDATED'] = 'Updated by';
$tickets_language['TICKETS_CLOSE_VERIFIED'] = 'Close?';
$tickets_language['TICKETS_ID'] = 'ID';
$tickets_language['TICKETS_NOTES_ID'] = 'Note ID';
$tickets_language['TICKETS_SENDER'] = 'Sender';
$tickets_language['TICKETS_SHOW_TO'] = 'Show to';
$tickets_language['TICKETS_WHO_IS'] = 'Staff / User';
$tickets_language['TICKETS_NAME'] = 'Name';
$tickets_language['TICKETS_INFO'] = 'Info';
$tickets_language['TICKETS_SUBSCRIBERS'] = 'Subscribers';
$tickets_language['TICKETS_EMAIL_PIPE'] = 'Email pipe';
$tickets_language['TICKETS_URGENCY_LEVEL'] = 'Urgency Level';
$tickets_language['TICKETS_SEND_ALERT'] = 'Email all staff';
$tickets_language['TICKETS_FIND_MATCH'] = 'Placeholder';
$tickets_language['TICKETS_REPLACE_WITH'] = 'Replacement String';
// end of order titles

// start of functions

// start of tickets_list_attachments.php
$tickets_language['TICKETS_SHOW_ATTACHMENT'] = 'View Attachment';
$tickets_language['TICKETS_LIST_ATTACHMENTS_NO_ATTACHMENTS'] = '<i>No files available.</i>';
// end of tickets_list_attachments.php

// start of tickets_delete_attachment.php
$tickets_language['TICKETS_LIST_ATTACHMENTS_DELETED'] = 'Attachment deleted.';
// end of tickets_delete_attachment.php

// start of tickets_list_tickets.php
$tickets_language['TICKETS_LIST_TICKETS_NO_TICKETS'] = '<i>No tickets available.</i>';
// end of tickets_list_tickets.php

// start of tickets_delete_ticket.php
$tickets_language['TICKETS_LIST_TICKETS_DELETED'] = 'Ticket(s) deleted.';
// end of tickets_delete_ticket.php

// start of tickets_list_notes.php
$tickets_language['TICKETS_LIST_NOTES_NO_NOTES'] = '<i>No notes available.</i>';
// end of tickets_list_notes.php

// start of tickets_delete_note.php
$tickets_language['TICKETS_LIST_NOTES_DELETED'] = 'Note(s) deleted.';
// end of tickets_delete_note.php

// start of tickets_list_categories.php
$tickets_language['TICKETS_LIST_CATEGORIES_NO_CATEGORIES'] = '<i>No categories available.</i>';
// end of tickets_list_categories.php

// start of tickets_delete_category.php
$tickets_language['TICKETS_LIST_CATEGORIES_DELETED'] = 'Category(s) deleted.';
// end of tickets_delete_category.php

// start of tickets_add_category.php
$tickets_language['TICKETS_CATEGORY_ADDED'] = 'Category added.';
$tickets_language['TICKETS_CATEGORY_ADDED_INVALID'] = 'Category couldn\'t be saved.<br>Please make sure the data is valid.';
// end of tickets_add_category.php

// start of tickets_edit_category.php
$tickets_language['TICKETS_CATEGORY_EDITED'] = 'Category edited.';
$tickets_language['TICKETS_CATEGORY_EDITED_INVALID'] = 'Category couldn\'t be saved.<br>Please make sure the data is valid.';
// end of tickets_edit_category.php

// start of tickets_list_priorities.php
$tickets_language['TICKETS_LIST_PRIORITIES_NO_PRIORITIES'] = '<i>No priorities available.</i>';
// end of tickets_list_priorities.php

// start of tickets_delete_priority.php
$tickets_language['TICKETS_LIST_PRIORITIES_DELETED'] = 'Priority deleted.';
// end of tickets_delete_priority.php

// start of tickets_add_priority.php
$tickets_language['TICKETS_ADD_PRIORITY'] = 'Add new priority';
$tickets_language['TICKETS_PRIORITY_ADDED'] = 'Priority added.';
$tickets_language['TICKETS_PRIORITY_ADDED_INVALID'] = 'Priority couldn\'t be saved.<br>Please make sure the data is valid.';
// end of tickets_add_priority.php

// start of tickets_edit_priority.php
$tickets_language['TICKETS_EDIT_PRIORITY'] = 'Edit priority';
$tickets_language['TICKETS_PRIORITY_EDITED'] = 'Priority edited.';
$tickets_language['TICKETS_PRIORITY_EDITED_INVALID'] = 'Priority couldn\'t be saved.<br>Please make sure the data is valid.';
// end of tickets_edit_priority.php

// start of tickets_list_placeholders.php
$tickets_language['TICKETS_LIST_PLACEHOLDERS_NO_PLACEHOLDERS'] = '<i>No placeholders available.</i>';
// end of tickets_list_placeholders.php

// start of tickets_add_category.php
$tickets_language['TICKETS_ADD_PLACEHOLDER'] = 'Add Placeholder';
$tickets_language['TICKETS_PLACEHOLDER_ADDED'] = 'Placeholder added.';
$tickets_language['TICKETS_PLACEHOLDER_ADDED_INVALID'] = 'Unable to add placeholder! Please try again.';
// end of tickets_add_category.php

// start of tickets_edit_placeholder.php
$tickets_language['TICKETS_EDIT_PLACEHOLDER'] = 'Edit Placeholder';
$tickets_language['TICKETS_PLACEHOLDER_EDITED'] = 'Changes saved.';
$tickets_language['TICKETS_PLACEHOLDER_EDITED_INVALID'] = 'Unable to save changes! Please try again.';
// end of tickets_edit_placeholder.php

// start of tickets_delete_placeholder.php
$tickets_language['TICKETS_LIST_PLACEHOLDERS_DELETED'] = 'Placeholder(s) deleted.';
// end of tickets_delete_placeholder.php

// start of tickets_edit_ticket.php
$tickets_language['TICKETS_EDIT_TICKET'] = 'Edit Ticket';
$tickets_language['TICKETS_TICKET_EDITED'] = 'Ticket edited.';
$tickets_language['TICKETS_TICKET_EDITED_INVALID'] = 'Ticket couldn\'t be saved.<br>Please make sure the data is valid.';
// end of tickets_edit_ticket.php

// start of tickets_edit_note.php
$tickets_language['TICKETS_EDIT_NOTE'] = 'Edit Note';
$tickets_language['TICKETS_NOTE_EDITED'] = 'Note edited.';
$tickets_language['TICKETS_NOTE_EDITED_INVALID'] = 'Note couldn\'t be saved.<br>Please make sure the data is valid.';
// end of tickets_edit_note.php

// start of tickets_list_assigned.php
$tickets_language['TICKETS_ASSIGNED_TICKETS'] = 'Open Tickets';
$tickets_language['TICKETS_SENTDATE'] = 'Sent Date';
$tickets_language['TICKETS_STAFF'] = 'Staff';
$tickets_language['TICKETS_USER'] = 'User';
$tickets_language['TICKETS_PRIORITY'] = 'Priority';
$tickets_language['TICKETS_CATEGORY'] = 'Category';
$tickets_language['TICKETS_SUBJECT'] = 'Subject';
$tickets_language['TICKETS_LAST_UPDATE'] = 'Last update';
$tickets_language['TICKETS_NO_TICKETS'] = '<i>No Tickets available.</i>';
$tickets_language['TICKETS_ARROW_UP'] = '<img src="'.SCRIPT_URL.'modules/staff/tickets/languages/en/arrow_up.gif" border="0">';
$tickets_language['TICKETS_ARROW_DOWN'] = '<img src="'.SCRIPT_URL.'modules/staff/tickets/languages/en/arrow_down.gif" border="0">';
// end of tickets_list_assigned.php

// start of tickets_list_open.php
$tickets_language['TICKETS_OPEN_TICKETS'] = 'New Tickets';
// end of tickets_list_open.php

// start of tickets_list_closed.php
$tickets_language['TICKETS_CLOSED_TICKETS'] = 'Closed Tickets';
// end of tickets_list_closed.php

// start of tickets_list_close.php
$tickets_language['TICKETS_CLOSE_TICKETS'] = 'Awaiting closure';
// end of tickets_list_close.php

// start of tickets_list_user_updated.php
$tickets_language['TICKETS_USER_UPDATED_TICKETS'] = 'Awaiting Staff Response';
// end of tickets_list_user_updated.php

// start of tickets_list_staff_updated.php
$tickets_language['TICKETS_STAFF_UPDATED_TICKETS'] = 'Awaiting User Response';
// end of tickets_list_staff_updated.php

// start of tickets_new_ticket.php
$tickets_language['TICKETS_SELECT_PRIORITY'] = 'Select Priority';
$tickets_language['TICKETS_SELECT_CATEGORY'] = 'Select Category';
$tickets_language['TICKETS_ENTER_SUBJECT']   = 'Enter Subject';
$tickets_language['TICKETS_ENTER_CONTENT']   = 'Enter Content';
$tickets_language['TICKETS_NO_PRIORITIES']   = 'No priorities exist!';
$tickets_language['TICKETS_NO_CATEGORIES'] 	 = 'No categories exist!';
$tickets_language['TICKETS_DATA_SAVED'] 	 = 'Your ticket was sent successfully.<br>A staff member will take care of your problem shortly.';
$tickets_language['TICKETS_SUBMIT'] 		 = 'Submit';
$tickets_language['TICKETS_RESET'] 			 = 'Reset';
$tickets_language['TICKETS_SUBJECT_DEFAULT'] = 'Please enter the subject of your problem/question.';
$tickets_language['TICKETS_CONTENT_DEFAULT'] = 'Please enter your problem/question.';
$tickets_language['TICKETS_UPLOAD_ERROR'] 	 = '<i>No Files uploaded.</i>';
// end of tickets_new_ticket.php

// start of tickets_show_ticket.php
$tickets_language['TICKETS_NO'] = 'ID';
$tickets_language['TICKETS_PRIORITY'] = 'Priority';
$tickets_language['TICKETS_CATEGORY'] = 'Category';
$tickets_language['TICKETS_SUBJECT'] = 'Subject';
$tickets_language['TICKETS_CONTENT'] = 'Content';
$tickets_language['TICKETS_STATUS'] = 'Status';
$tickets_language['TICKETS_PIPE_ID'] = 'Tracking ID';
$tickets_language['TICKETS_ATTACHMENT_ICON'] = '<IMG src="'.SCRIPT_URL.'modules/staff/tickets/languages/en/attachment.gif" border="0">';
$tickets_language['TICKETS_TRASH_ICON'] = '<IMG src="'.SCRIPT_URL.'modules/staff/tickets/languages/en/trash.gif" border="0">';
$tickets_language['TICKETS_SHOW_USER_HISTORY'] = 'Ticket History';
// end of tickets_show_ticket.php

// start of tickets_list_notes.php
$tickets_language['TICKETS_NOTES'] = '&laquo;&raquo; Notes';
// end of tickets_list_notes.php

// start of tickets_add_note_form.php
$tickets_language['TICKETS_ADD_NOTE'] = 'Add Note';
// end of tickets_add_note_form.php

// start of tickets_add_note.php
$tickets_language['TICKETS_ADD_NOTE_PERMISSION'] 	= 'You are not allowed to add notes to a ticket which doesn\'t belong to you.';
$tickets_language['TICKETS_ADD_NOTE_CLOSED'] 		= 'You cannot add a note to a closed ticket.<br>In order to add a note to a closed ticket, you will have to re-open it first.';
$tickets_language['TICKETS_ADD_NOTE_CONTENT'] 		= 'You forgot to enter the content of your note.';
$tickets_language['TICKETS_ADD_NOTE_UPLOAD'] 		= 'File successfully uploaded.';
$tickets_language['TICKETS_ADD_NOTE_ADDED'] 		= 'Note added.<br>You will now be redirected to the ticket.';
$tickets_language['TICKETS_ADD_NOTE_INVALID'] 		= 'You tried to add data to an invalid ticket.';
// end of tickets_add_note.php

// start of tickets_show_grab.php
$tickets_language['TICKETS_CLAIM'] = 'Claim Ticket';
$tickets_language['TICKETS_GRAB'] = 'Grab Ticket';
$tickets_language['TICKETS_MOVE'] = 'Move Ticket';
$tickets_language['TICKETS_REOPEN'] = 'Reopen Ticket';
// end of tickets_show_grab.php

// start of tickets_edit_note_form.php
$tickets_language['TICKETS_EDIT_NOTE'] = 'Edit Note';
$tickets_language['TICKETS_BACK_TO_ADD'] = '<i>Click here to go back to the "Add Note" page.</i>';
$tickets_language['TICKETS_EDIT_NOTE_FORM_INVALID'] = 'You tried to edit data from an invalid note.';
// end of tickets_edit_note_form.php

// start of tickets_edit_note.php
$tickets_language['TICKETS_EDIT_NOTE_PERMISSION'] 	= 'You are not allowed to edit a note which doesn\'t belong to you.';
$tickets_language['TICKETS_EDIT_NOTE_CONTENT'] 		= 'You forgot to enter the content of your note.';
$tickets_language['TICKETS_EDIT_NOTE_EDITED'] 		= 'Note edited.<br>You will now be redirected to the ticket.';
$tickets_language['TICKETS_EDIT_NOTE_INVALID'] 		= 'You tried to edit data on an invalid ticket.';
// end of tickets_edit_note.php

// start of tickets_delete_note.php
$tickets_language['TICKETS_DELETE_NOTE_PERMISSION'] = 'You are not allowed to delete a note which doesn\'t belong to you.';
$tickets_language['TICKETS_DELETE_NOTE_DELETED'] 	= 'Note deleted.<br>You will now be redirected to the ticket.';
$tickets_language['TICKETS_DELETE_NOTE_INVALID'] 	= 'You tried to delete data from an invalid ticket.';
// end of tickets_delete_note.php

// start of tickets_delete_attachment.php
$tickets_language['TICKETS_DELETE_ATTACHMENT_DELETED'] 	= 'Attachment deleted.<br>You will now be redirected to the ticket.';
$tickets_language['TICKETS_DELETE_ATTACHMENT_INVALID'] 	= 'Invalid function.';
// end of tickets_delete_attachment.php

// start of tickets_confirm_delete_attachment.php
$tickets_language['TICKETS_CONFIRM_ATTACHMENT_DELETION'] = 'Delete attachment?';
// start of tickets_confirm_delete_attachment.php

// start of tickets_confirm_delete_note.php
$tickets_language['TICKETS_CONFIRM_DELETION'] = 'Are you sure you want to delete this note?';
$tickets_language['TICKETS_CONFIRM_OK'] = '<img src="'.SCRIPT_URL.'modules/staff/tickets/languages/en/ok.gif" border="0"><br>&nbsp;&nbsp;Yes';
$tickets_language['TICKETS_CONFIRM_NO'] = '<img src="'.SCRIPT_URL.'modules/staff/tickets/languages/en/no.gif" border="0">&nbsp;&nbsp;<br>No&nbsp;&nbsp;';
// end of tickets_confirm_delete_note.php

// start of tickets_list_notes.php
$tickets_language['TICKETS_NOTE_EDIT'] 		= 'Edit';
$tickets_language['TICKETS_NOTE_DELETE'] 	= 'Delete';
// end of tickets_list_notes.php

// start of tickets_show_ticket.php
$tickets_language['TICKETS_SHOW_TICKET_PERMISSION'] = 'You are not allowed to view this ticket!';
// end of tickets_show_ticket.php

// start of tickets_grab_ticket.php
$tickets_language['TICKETS_GRAB_GRABBED']  = 'You grabbed this ticket from';
$tickets_language['TICKETS_GRAB_CLAIMED']  = 'You claimed this ticket.<br>Please wait, you are being redirected to the ticket content page.';
$tickets_language['TICKETS_GRAB_REOPENED'] = 'You re-opened the ticket.';
$tickets_language['TICKETS_GRAB_INVALID']  = 'Invalid action!';
// end of tickets_grab_ticket.php

// start of tickets_move_ticket.php
$tickets_language['TICKETS_MOVE_MOVED']  	= 'Ticket moved to:';
$tickets_language['TICKETS_MOVE_OPEN']  	= 'You cannot move new tickets.';
$tickets_language['TICKETS_MOVE_CLOSED'] 	= 'You cannot move closed tickets.';
$tickets_language['TICKETS_MOVE_INVALID']  	= 'Invalid action!';
// end of tickets_move_ticket.php

// end of functions

// start of templates - pages
// start of tickets_list_attachments.tpl
$tickets_language['TICKETS_LIST_ATTACHMENTS_TITLE'] = 'Support Logic - Manage Uploaded Files';
// end of tickets_list_attachments.tpl

// start of tickets_list_notes.tpl
$tickets_language['TICKETS_LIST_NOTES_TITLE'] = 'Support Logic - Manage notes';
// end of tickets_list_notes.tpl

// start of tickets_list_tickets.tpl
$tickets_language['TICKETS_LIST_TICKETS_TITLE'] = 'Support Logic - Manage Tickets';
// end of tickets_list_tickets.tpl

// start of tickets_list_categories.tpl
$tickets_language['TICKETS_LIST_CATEGORIES_TITLE'] = 'Support Logic - Manage Categories';
// end of tickets_list_categories.tpl

// start of tickets_add_category.tpl
$tickets_language['TICKETS_ADD_CATEGORY_TITLE'] = 'Support Logic - Add Category';
// end of tickets_add_category.tpl

// start of tickets_edit_category.tpl
$tickets_language['TICKETS_EDIT_CATEGORY_TITLE'] = 'Support Logic - Edit Category';
// end of tickets_edit_category.tpl

// start of tickets_list_priorities.tpl
$tickets_language['TICKETS_LIST_PRIORITIES_TITLE'] = 'Support Logic - Manage Priorities';
// end of tickets_list_priorities.tpl

// start of tickets_add_priority.tpl
$tickets_language['TICKETS_ADD_PRIORITY_TITLE'] = 'Support Logic - Add Priority';
// end of tickets_add_priority.tpl

// start of tickets_edit_priority.tpl
$tickets_language['TICKETS_EDIT_PRIORITY_TITLE'] = 'Support Logic - Edit Priority';
// end of tickets_edit_priority.tpl

// start of tickets_edit_ticket.tpl
$tickets_language['TICKETS_EDIT_TICKET_TITLE'] = 'Support Logic - Edit Ticket';
// end of tickets_edit_ticket.tpl

// start of tickets_confirm_delete_note.tpl
$tickets_language['TICKETS_CONFIRM_DELETE_TITLE'] = 'Support Logic - Confirm Deletion';
// end of tickets_confirm_delete_note.tpl

// start of tickets_list_assigned.tpl
$tickets_language['TICKETS_LIST_ASSIGNED_TITLE'] = 'Support Logic - Open Tickets';
// end of tickets_list_assigned.tpl

// start of tickets_list_close.tpl
$tickets_language['TICKETS_LIST_CLOSE_TITLE'] = 'Support Logic - Tickets awaiting closure';
// end of tickets_list_close.tpl

// start of tickets_list_closed.tpl
$tickets_language['TICKETS_LIST_CLOSED_TITLE'] = 'Support Logic - Closed Tickets';
// end of tickets_list_closed.tpl

// start of tickets_list_open.tpl
$tickets_language['TICKETS_LIST_OPEN_TITLE'] = 'Support Logic - New Tickets';
// end of tickets_list_open.tpl

// start of tickets_list_staff_updated.tpl
$tickets_language['TICKETS_LIST_STAFF_UPDATED_TITLE'] = 'Support Logic - Tickets awaiting user response';
// end of tickets_list_staff_updated.tpl

// start of tickets_show_ticket.tpl
$tickets_language['TICKETS_SHOW_TICKET_TITLE'] = 'Support Logic - Ticket Content';
// end of tickets_show_ticket.tpl

// start of tickets_list_user_updated.tpl
$tickets_language['TICKETS_LIST_USER_UPDATED_TITLE'] = 'Support Logic - Tickets awaiting staff response';
// end of tickets_list_user_updated.tpl

// start of tickets_show_ticket_edit.tpl
$tickets_language['TICKETS_EDIT_NOTE_TITLE'] = 'Support Logic - Edit Note';
// end of tickets_show_ticket_edit.tpl

// start of tickets_show_history.tpl
$tickets_language['TICKETS_SHOW_HISTORY_TITLE'] = 'Support Logic - Ticket History';
// end of tickets_show_history.tpl

// start of tickets_list_placeholders.tpl
$tickets_language['TICKETS_LIST_PLACEHOLDERS_TITLE'] = 'Support Logic - Placeholders';
// end of tickets_list_placeholders.tpl

// start of tickets_add_placeholder.tpl
$tickets_language['TICKETS_ADD_PLACEHOLDER_TITLE'] = 'Support Logic - Add Placeholder';
// end of tickets_add_placeholder.tpl

// start of tickets_edit_placeholder.tpl
$tickets_language['TICKETS_EDIT_PLACEHOLDER_TITLE'] = 'Support Logic - Edit Placeholder';
// end of tickets_edit_placeholder.tpl
// end of templates - pages

// start of templates - functions
// start of tickets_add_note_form.tpl & tickets_new_ticket.tpl & tickets_show_ticket.tpl & tickets_list_notes.tpl
$tickets_language['TICKETS_GO'] = 'Go!';
$tickets_language['TICKETS_JUMPER_TEXT'] = 'Go to ticket no.:';
$tickets_language['TICKETS_STAFF_TO_STAFF'] = 'Staff-2-Staff note?';
$tickets_language['TICKETS_PREVIOUS'] = 'Previous';
$tickets_language['TICKETS_NEXT'] = 'Next';
$tickets_language['TICKETS_ATTACHMENTS'] = 'Attachment(s)';
$tickets_language['TICKETS_ADD_ATTACHMENT'] = 'Add an attachment:';
$tickets_language['TICKETS_CURRENT_ATTACHMENTS'] = 'Current attachments:';
$tickets_language['TICKETS_CLOSE_TICKET_VERIFY'] = 'Can the ticket be closed?';
$tickets_language['TICKETS_YES'] = 'Yes';
$tickets_language['TICKETS_NO_NOTES'] = 'No Notes available.';
$tickets_language['TICKETS_SHOW_HISTORY'] = 'Ticket history for user:';
$tickets_language['TICKETS_ADD_CATEGORY'] = 'Add new category:';
$tickets_language['TICKETS_EDIT_CATEGORY'] = 'Edit category:';
// end of tickets_add_note_form.tpl & tickets_new_ticket.tpl & tickets_show_ticket.tpl & tickets_list_notes.tpl
// end of templates - functions
?>