<?php
/***************************************************************************
								stats_language.inc
							----------------------------
			created				: 11.04.2003
			edited				: -
			copyright			: (C) 2002 Support-Logic
			email				: hendrik@support-logic.com

			based on coding standards: codingstandards.htm, v1.0 27.12.2002 
		
***************************************************************************/

// language file of stats module

// start of main mavigation
$stats_language['STATS_MENU'] = 'Stats Menu';
$stats_language['STATS_TOP10'] = 'TOP 10';
$stats_language['STATS_RAW'] = 'Roh-Daten';
// end of main mavigation

// start of order titles
// end of order titles

// start of functions

// start of tickets_list_attachments.php
// end of tickets_list_attachments.php

// end of functions

// start of templates - pages
// start of stats_top10.tpl
$stats_language['STATS_TOP10_TITLE'] = 'Support Logic - TOP 10 Stats';
// end of stats_top10.tpl

// start of stats_raw.tpl
$stats_language['STATS_RAW_TITLE'] = 'Support Logic - Roh-Daten';
// end of stats_raw.tpl

// start of stats_user_stats.tpl
$stats_language['STATS_USER_STATS_TITLE'] = 'Support Logic - Benutzer Daten';
// end of stats_user_stats.tpl

// start of stats_staff_stats.tpl
$stats_language['STATS_STAFF_STATS_TITLE'] = 'Support Logic - Mitarbeiter Daten';
// end of stats_staff_stats.tpl

// end of templates - pages

// start of templates - functions
$stats_language['STATS_TOP10_USERS_TITLE'] = 'Top 10 - Tickets von Benutzer';
$stats_language['STATS_TOP10_STAFF_TITLE'] = 'Top 10 - Tickets von Mitarbeitern';
$stats_language['STATS_TOP10_USER_NOTES_TITLE'] = 'Top 10 - Notes von Benutzer';
$stats_language['STATS_TOP10_STAFF_NOTES_TITLE'] = 'Top 10 - Notes von Mitarbeitern';
$stats_language['STATS_TOP10_PRIORITY_TITLE'] = 'Top 10 - Ticket-Priorit&auml;ten';
$stats_language['STATS_TOP10_CATEGORY_TITLE'] = 'Top 10 - Ticket-Kategorien';
$stats_language['STATS_TOP10_NO_TICKETS'] = 'No. Tickets';
$stats_language['STATS_TOP10_NO_NOTES'] = 'No. Notes';

$stats_language['STATS_TOTAL_TICKETS'] = 'Summe aller Tickets';
$stats_language['STATS_TOTAL_NOTES'] = 'Summe aller Notizen';
$stats_language['STATS_TOTAL_ANNOUNCEMENTS'] = 'Summe aller Ank&uuml;ndigungen';
$stats_language['STATS_TOTAL_ATTACHMENTS'] = 'Summe aller Dateianh&auml;nge';
$stats_language['STATS_TOTAL_CATEGORIES'] = 'Summe aller Kategorien';
$stats_language['STATS_TOTAL_PRIORITIES'] = 'Summe aller Priorit&auml;ten';
$stats_language['STATS_TOTAL_USERS'] = 'Summe aller Benutzer';
$stats_language['STATS_TOTAL_STAFF'] = 'Summe aller Mitarbeiter';

$stats_language['STATS_TOP_HOUR'] = 'Uhrzeit (Stunde) mit meisten Tickets';
$stats_language['STATS_TOP_MONTH'] = 'Monat mit meisten Tickets';
$stats_language['STATS_TOP_YEAR'] = 'Jahr mit meisten Tickets';

$stats_language['STATS_USER_STATS'] = 'Benutzer Daten von:';
$stats_language['STATS_STAFF_STATS'] = 'Mitarbeiter Daten von:';

$stats_language['STATS_RAW_HOURS'] = 'Tickets sortiert nach Stunde (vom Tag)';
$stats_language['STATS_RAW_HOUR'] = 'Stunde (00-23)';
$stats_language['STATS_PERCENT'] = 'Prozent %';
$stats_language['STATS_RAW_DATE_TITLE'] = 'Tickets sortiert nach Monat.Jahr';
$stats_language['STATS_RAW_DATE'] = 'Monat . Jahr';
$stats_language['STATS_RAW_STAFF'] = 'Tickets sortiert nach Mitarbeiter';
// end of templates - functions
?>