<?php
/***************************************************************************
 *                          lang_faq.php [Breton]
 *                            -------------------
 *   begin                : Mon Sep 13 2004
 *   copyright            : (C) 2001 The phpBB Group
 *   email                : support@phpbb.com
 *
 *   $Id: lang_faq.php,v 1.4.2.3 2002/12/21 22:26:02 psotfx Exp $
 *
 *
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
/* CONTRIBUTORS:
	Translation produced by Malo-net
	http://malomorvan.free.fr/
*/


$faq[] = array("--","Kennaskañ hag enrollañ");  
$faq[] = array("Perak ne c'hellan ket kennaskañ ?", "Hag enrollet oc'h? Ret eo bezañ enrollet evit gallout kennaskañ. Ha skarzhet oc'h bet deus ar forum (ur gemennadenn a zo war-wel neuze) ? Ma 'z eo ya ar respont eo ret deoc'h mont e-darempred gant merour ar forum pe krouer al lec'hienn evit gouzout perak. Ma 'z oc'h enrollet ha ma n' hoc'h ket bet skarzhet, gwiriit eo reizh ho anv-implijad hag ho ger-tremen. Alies e teu ar gudenn deus aze. Ma n'ez a ket en-dro, kit e-darempred gant merour ar forum, posupl eo e vefe bet stummet fall ar forum.");
$faq[] = array("Perak n'am eus ket ezhomm d' en em enrollañ ?", "Ar merour eo a zibab ma zo ezhomm bezañ enrollet evit kas kemennadennoù war forumoù 'zo. Gwelloc'h e chom enrollañ koulskoude, evel-se e c'hallit ober traoù ouzhpenn : diskouez ur skeudenn avatar, bezañ lakaet e-barzh ur strollad-implijerien, kas ha degemer kemennadennoù prevez, kemm pe diverkañ kemennadennoù, hag all... Nebeud amzer e kemer d'ober, hag aliet oc'h d'hen ober.");
$faq[] = array("Perak e vezan digennasket ingal ?", "Ma ne dibabit ket an dilenn <i>Kennaskañ en un doare emgefreek da bep gweladenn</i> pa gennaskit, e voc'h kennasket evit ur prantad resis. Servijout a ra da virout ouzh unan all da implijout ho kont hep ho aotre. Evit chom kennasket, dibabit an dilenn pa gennaskit. N'eo ket aliet ma implijet un urzhiataerezh foran (levraoueg, skol-veur, cyberkafe, hag all...).");
$faq[] = array("Penaos e c'hellan ober evit ma ne vefe ket gwelet va anv e roll an implijerien kennasket ?", "En ho aelad e  kavoc'h un dilenn <i>kuzhat ho pezañs</i>, ma tibabit <i>Ya</i>, ne vo den all eget ar merourien ha c'hwi o-unan a c'hello gwelet oc'h kennasket.");
$faq[] = array("Kollet am eus va c'her-tremen!", "Na bennfollit ket ! Ne c'halloc'h ket kavout anezhañ en-dro, met gallot a rit kaout unan nevez. Evit hen ober, kit war ar bajenn-kennaskañ, ha klikit war <u>Ankouat am eus va c'her-tremen</u>, hag heuilhit an urzhioù, hag e vo tu deoc'h kennaskañ en-dro buan-kenañ.");
$faq[] = array("Enrollet on, met ne c'hellan ket kennaskañ !", "Da gentañ, gwiriit ho peus skrivet un anv-implijer hag ur ger-tremen reizh. Ma 'z int reizh, ez eus daou dra posupl. M' emañ ar skor COPPA  war-enaou ha m'ho peus dibabet <u>Nebeutoc'h eget 13 bloaz on</u> da vare an enrollañ, e rankoc'h heuliañ an urzhioù a zo bet roet deoc'h. Ma n\ eo ket an degouezh-se, marteze eo ret deoc'h enaouiñ ho kont. War forumoù 'zo eo ret enaouiñ pep enrolladenn, pe hoc'h-unan, pe o tremen dre ar merour. P 'oc'h bet enrollet he defe ranket ur gemennadennig lavar deoc'h ma oa ezhomm enaouiñ an enrolladenn pe get. M' ho peus bet ur bostel, diwallit ne vefe ket bet kemeret evit ur spam, hag heuilhit an urzhioù a zo warnañ.Ma n'ho peus bet hini ebet, gwiriit ho peus roet ur chomlec'h mail reizh da vare an enrollañ. Diwall na vefe ket graet un droukimplij deus ar forum gant tud dizanv a zo unan deus abegoù an enaouiñ. Ma 'z eo reizh ar chomlec'h ho peus roet, kit e darempred gant merour ar forum.");
$faq[] = array("Enrollet on bet pell 'zo, met ne c'hellan ket kennaskañ ken ?!", "Daou abeg pennañ a gaver da seurt degouezh : un anv-implijer hag ur ger-tremen faos (gwiriit ar bostel a oa bet kaset deoc'h da vare ho enrollañ), pe neuze eo bet diverket ho kont gant merour ar forum, evit abeg-mañ-abeg. Ma 'n em gavit en eil degouezh, marteze n'ho poa kaset kemennadenn ebet ? Boaz e vez ar merourien da ziverkañ kontoù an implijerien n'o deus kaset netra, a-benn dieubiñ egor war an diaz-titouroù. Klaskit enrollañ un eil gwech, ha kemer perzh er c'haozeadennoù.");

$faq[] = array("--","Gwellvezioù hag arventerioù an implijerien");
$faq[] = array("Penaos e c'hellan kemm ma wellvezioù ?", "Ma'z oc'h enrollet emañ miret ho holl gwellvezioù en diaz-titouroù. Evit kemm anezho, klikit war al liamm <u>Aelad</u> (e krec'h ar bajenn peurliesañ). Gallout a reoc'h neuze kemm ho gwellvezioù.");
$faq[] = array("N'eo ket reizh an eurioù !", "Sur a-walc'h eo reizh an eurioù, met diskouezet int en ur gwerzhid-eur disheñvel deus ho hini.Neuze eo ret kemm ar gwerzhid-eur en ho gwellvezioù.Evel just, ne c'hellit ket hen ober ma n'oc'h ket enrollet.");
$faq[] = array("Kemmet am eus ar gwerzhid-eur, ha direizh eo c'hoazh an eur !", "Ma 'z oc'h sur eo reizh ho gwerzhid-eur, marteze eo dre-fazi ar c'hemm etre eur an hañv hag eur ar goañv. Ar forum n'eo ket gouest da verañ an tremen deus an eil eur d'egile, neuze e vo un diforc'h etre eur ar forum hag an eur gwirion e-pad an hañv.");
$faq[] = array("N'emañ ket ma yezh el listenn !", "Chañsoù 'zo ne vefe ket bet staliet ar yezh ho peus c'hoant gant merour ar forum, pe ne vefe ket bet troet phpBB er yezh-se c'hoazh. Kit e darempred gant merour ar forum. M'ho peus c'hoant da dreiñ ar forum e kavoc'h titouroù war al liamm <i>phpBB</i> e-traoñ ar bajenn.");
$faq[] = array("Penaos e c'hellan diskouez ur skeudenn dindan va anv-implijer ?", "Div skeudenn a c'hell bezañ dindan anv un implijer pa gas ur gemennadenn. An hini gentañ a zo liammet ouzh ho renk (hervez an niver a gemennadennoù bet kaset ganeoc'h, pa ho statud war ar forum). Dindan honnezh e c'hell bezañ ur skeudenn vrasoc'h, anvet avatar, hag a zo alies dibar hag hervez an implijer. Da verour ar forum eo da enaouiñ pe get an avatarioù ha da zibab e peseurt doare e vo tu lakaat anezho. Ma ne c'hellit ket implijout un avatar, eo peogwir eo bet dibabet gant ar merour. Goulennit neuze perak gantañ.");
$faq[] = array("Penaos e c'hellan kemm ma renk ?", "Peurliesañ ne c'hellit ket kemm titl ho renk war-eeun. (titl ur renk a vez gwelet dindan ho anv-implijer). Darn vrasañ deus ar forumoù a implj renkoù evit diskouez an niver a gemennadennoù bet kaset ganeoc'h, pe evit krouiñ rummadoù implijerien gant gwirioù resis (kasourien, merourien, ..;). Ma gasit kemennadennoù didalvoud e-leizh a-benn uhelaat ho renk, e vo diskennet an niver a gemennadennoù kaset ganeoc'h gant ur merour pe ur c'hasour.");
$faq[] = array("Pa glikan war liamm <i>postel</i> un implijer e vez goulennet ganin kennaskañ !", "Ne c'hellit ket kas un e-mail ma n'hoc'h ket enrollet. Dibabet eo bet mont en-dro evel-se evit mirout ouzh ar posteloù dizanv (evz: n'eo ket enaouet an dilenn <i>mail</i> war an holl forumoù).");

$faq[] = array("--","Embann");
$faq[] = array("Penaos e c'hellan kas ur sujed en ur forum ?", "Klikit war an nozelenn a zere (nouveau, nevez, répondre, respont). War forumoù 'zo eo ret bezañ enrollet evit gallout postañ ur gemennadenn. Gwelit ho kwirioù e-traoñ ar bajenn (ar roll <i>Gallout a rit kas ur gemennadenn, gallout a rit mouezhiañ, hag all...</i>)");
$faq[] = array("Penaos e c'hellan kemm pe diverkañ ur gemennadenn ?", "Nemet ma vefec'h merour pe kasour, ne c'hellit ket diverkañ kemennadennoù all eget ho hini. Gallout a rit kemm ur gemennadenn o klikañ war an nozelenn <i>Kemm</i> a-us da honnezh (a-wechoù eo ret gortoz ur pennadig goude bezañ kaset anezhi a-raok gallout he c'hemm). Ma 'z eus bet respontet d'ho kemennadenn a-raok ma gemmfec'h anezhi e weloc'h un destennig dindan honnezh o lavar pet gwech eo bet kemmet, ha peur. Ne vo ket ouzh an destennig-se ma n' eus bet respont ebet d'ho kemennadenn, pe ma 'z eo bet kemmet gant ur merour pe ur c'hasour (rankout a rafent displegañ ar pezh o deus graet). Ne c'hellit ket diverkañ ur gemennadenn m'az eus bet respontet outi.");
$faq[] = array("penaos e c'hellan ouzhpennañ va sinadur d'ur gemennadenn ?", "A-raok ouzhpennañ ur sinadur en ho kemennadenn eo ret krouiñ unan en ho Aelad. Ur wech krouet, e c'hellit dibab an dilenn <i>Stagañ ar sinadur</i> pa skrivit ur gemennadenn. Gallout a rit ivez ouzhpennañ ho sinadur d'ho holl kemennadennoù dre ober an dibab a zere en ho Aelad (posupl e vo deoc'h chom hep stagañ anezhi war bep kemennadenn oc'h ober an dibab a zere da vare ar skrivañ).");
$faq[] = array("penaos e c'helan sevel ur sontadeg ?", "Aezet eo krouiñ ur sontadeg pa grouit ur sujed nevez pe pa embannit sujed kentañ ur pennad-kaoz. Rankout a rafec'h gwelet ul lodenn <i>Ouzhpennañ ur sontadeg </i> er furmskrid <i>Kas ur sujed nevez</i>.Ma ne welit ket al lodenn-se eo peogwir n'hoc'h ket bet aotreet da aozañ ur sontadeg. Rankout a rit reiñ un titl d'ar sontadeg, ha daou zibab d'an nebeutañ (evit krouiñ un dibab, lakait he anv en dachenn graet evit se, ha klikit war <i>Ouzhpennañ an dibab</i>. Gallout a rit ivez dibab ur padelezh resis evit au sontadeg, 0 a dalvez evit ur sontadeg peurbadus. Ur vevenn a zo evit an niver a zibaboù a c'hellit kinnig, honnezh a zo dibabet gant merour ar forum.).");
$faq[] = array("Penaos e c'hellan kemm pe diverkañ ur sontadeg ??", "Evel evit ar c'hemennadennoù, n'eus den all eget ar merour(ien), ar c'hasour(ien), ha krouer ar sontadeg a c'hell kemm pe diverkañ anezho.. Evit kemm ur sontadeg, klikit war an nozelenn <i>kemm</i> er gemennadenn (bepred emañ stag ar sontadeg outi). Ma n'eus bet den c'hoazh o vouezhiañ e c'hellit diverkañ ar sontadeg pe kemm forzh peseurt dibab, met ma 'z eus bet tud o vouezhiañ, e c'hello ar merourien hag ar c'hasourien kemm pe diverkañ anezhañ, met ket krouer ar sontadeg. An diviz-se a servij da virout ouzh an dud da druchañ dre gemm an dibaboù e-kreiz ar padelezh-mouezhiañ");
$faq[] = array("Perak ne c'hellan ket tizhout ur forum ?", "War forumoù 'zo e c'hell ar mont e-barzh bezañ bevennet d'ur rummad ispisial a dud. Ret eo neuze kejañ gant ur merour pe ur c'hasour evit goulenn un aotre digantañ.");
$faq[] = array("Perak ne c'hellan ket mouezhiañ en ur sontadeg ?", "Ma n'hoc'h ket enrollet, ne c'hellit ket mouezhiañ (evit herzel ouzh an trucherezh). Ma 'z oc'h enrollet met ne c'hellit ket mouezhiañ, eo peogwir n'hoc'h ket aotreet d'hen ober.");

$faq[] = array("--","Stumm ha doare-sujedoù");
$faq[] = array("Petra eo ar BBCode ?", "Ur c'heflouerañ ispisial deus an HTML eo ar BBCode, ar merour a zibab e enaouiñ pe get (gallout a rit ivez e zizenaouiñ pa skrivit ur gemennadenn). Damheñvel eo ar BBCode ouzh an HTML, etre krogoù [ ha ] emañ ar balizennoù kentoc'h eget re &lt; ha &gt;, ha merañ a ra gwelloc'h an doare ma rank un destenn bezañ diskouezet. Kit da welet ar sturiell evit kaout muioc'h a ditouroù diwar-benn ar BBCode (mont war ar furmskrid-embann) .");
$faq[] = array("Ha gallout a ran implijout an HTML ?", "Hervez ar pezh a zo bet dibabet gant merour ar forum eo. Ma 'z oc'h aotreet d'e implijout e verzhoc'h n'ez a ket an holl valizennoù en-dro. Un afer a <i>surentez</i> eo, evit herzel ouzh an dud d'ober forzh petra war ar forum. Ma vez aotreet an HTML e c'hellit disaotreañ anezhañ war ur gemennadenn resis pa gasit anezhi.");
$faq[] = array("Petra eo ar Smilies ?", "Ar Smilies, pe Emoticons, a zo skeudennigoù a servij da ziskouez trivliadoù hervez ur c'hod resis, da skouer e talvez :) evit laouen, ha :( evit trist. Gallout a rit gwelet listenn ar Smilies pa skrivit ur gemennadenn. Klaskit chom hep ober re gant ar re-se, peogwir e lakaont buan ur gemennadenn da vezañ dilennadus.");
$faq[] = array("Ha gallout a ran kas skeudennoù ?", "Gallout a rit diskouez skeudennoù e-barzh ho kemennadenn, met n'eo ket posubl kas anezho diouzhtu war ar forum. Rankout a rit krouiñ ul liamm davet ar skeudenn-se, m'emañ war ar rouedad, da skouer: http://www.amañ-pe-aze.net/ma-skeudenn.gif. Ne c'hellit ket krouiñ ul liamm davet ur skeudenn a zo war gantenn galet ho urzhiataer (nemet ma vefe hennezh ur servijer web foran), ni war ur servijer o c'houlenn un wiriadenn (da skouer: boestoù-mail Hotmail pe Yahoo, lec'hiennoù gwarezet gant ur ger-tremen, hag all. Evit diskouez ur skeudenn e c'helit implijout ar valizenn BBCode [img] pe an hini HTML a zere (ma 'z oc'h aotreet d'hen ober).");
$faq[] = array("Petra eo ar c'hemennoù ?", "Peurliesañ e vez eleier a-bouez er c'hemennoù; dre se eo ret deoc'h lenn anezho ar buanañ ar gwellañ. Gwelet 'vezont e-krec'h pep pajenn war ar forumoù int bet lakaet enne. Gant ar merour e vez dibabet piv a c'hell kas ur c'hemenn ha piv ne c'hell ket hen ober.");
$faq[] = array("Petra eo ur post-it ?", "Dindan ar c'hemennadennoù, war bajenn gentañ ar forum, e kaver ar postoù-it. Peuliesañ e vezont a-bouez a-walc'h, neuze lennit anezho ar buanañ ar gwellañ. Evel evit ar c'hemennadennoù eo ar merour an hini eo a zibab reiñ pe get an aotreoù evit embann postoù-it e-barzh pep forum.");
$faq[] = array("Petra eo ar sujedoù prennet ?", "Ar sujedoù-se a zo bet prennet gant ar merourien pe ar c'hasourien. N'eus ket tu da respont dezhe na da vouezhiañ ken. Evit abegoù lies e c'hell sujedoù bezañ prennet.");

$faq[] = array("--","Liveoù an implijerien ha Rummadoù");
$faq[] = array("Piv eo ar merourien ?", "Ar merourien a ra war-dro ar forum, gallout a reont dibab pep tra (aotreoù, sevel rummadoù, kemm kemennadennoù, skarzhañ tud, prennañ sujedoù, krouiñ forumoù, hag all...).");
$faq[] = array("Piv eo ar c'hasourien ?", "Tud pe strolladoù tud o tiwall ouzh mont-en-dro ar forum hag ouzh doujañs d'ar reolennoù eo ar c'hasourien. Gallout a reont kemm, diverkañ kemennadenoù, prennañ, dibrennañ, diverkañ, rannañ ar sujedoù er forumoù ma labouront. Peurliesañ e vezont amañ evit diwall ne vefe den  <i>er maez deus ar gaoz</i> pe o chom hep doujañ ouzh ar reolennoù.");
$faq[] = array("Petra eo ar rummadoù-implijerien ?", "Un doare evit ar merour eo da strollañ an implijerien. Pep implijer a c'hell bezañ e-barzh meur a strollad, ha pep strollad a c'hell kaout gwirioù ispisial. Evel-se e c'hell ar merour krouiñ forumoù prevez evit un nebeud tud, pe merañ ar c'hasourien, hag all...");
$faq[] = array("Penaos e c'hellan mont en ur rummad implijerien ?", "Evit mont e-barzh ur rummad-implijerien, klikit war <i>Rummadoù-implijerien</i> e-krec'h ar bajenn peurliesañ, gallout a reoc'h neuze gwelet ar strolladoù-implijidi. An holl rummadoù n'int ket <i>digor</i>, lod a zo <i>serret</i> ha lod all a c'hell bezañ kuzh an dud enne. Ma 'z eo digor ar rummad e c'hellit mont ennañ dre glikañ war an nozelenn a zere. Kasour ar rummad a ranko degemer ho koulenn, gallout a rafe goulenn perak ho peus c'hoant da vont er strollad diganeoc'h. Klaskit chom hep atahinañ ar c'hasour ma n'en deus ket c'hoant ez afec'h en ur rummad bennak, e abegoù 'zo gantañ.");
$faq[] = array("Penaos e c'hellan dont da vezañ kasour ur rummad-implijerien?", "Gant ar merour a vez savet ar rummadoù-implijerien ha roet ur c'hasour dezho. Kasit ur gemennadenn prevez d'ar merour ma 'z oc'h dedennet gant ur rummad-implijerien.");

$faq[] = array("--","Kemennadennoù prevez");
$faq[] = array("Ne c'hellan ket kas kemennadennoù prevez !", "tri abeg a zo da se: n'hoc'h ket enrollet pe kennasket, harzet eo bet ar c'hemennadennoù prevez war hollad ar forum gant ar merour pe evidoc'h hepken. M'emaoc'h en degouezh diwezhañ e vo ret deoc'h mont e-darempred gant ar merour evit gouzout perak (ket gant ur gemennadenn prevez !).");
$faq[] = array("Kenderc'hel a ran da zegemer kemennadennoù prevez n'am eus ket c'hoant oute !", "En dazont e vo ouzhpennet ul <i>listenn zu</i> d'ar c'hemennadennoù prevez. Evit ar mare eo ret deoc'h mont e-darempred gant ar merour. Hennezh a c'hell herzel ouzh un implijer da gas kemennadennoù prevez.");
$faq[] = array("Degemeret 'm eus ur bostel spam pe a-zroukimplij war ar forum !", "Trist omp o teskiñ se. Dre ma vez enrollet an holl bosteloù bet kaset eo posupl klask peseurt implijerien a gas seurt posteloù. Rankout a rafec'h kas ur bostel d'ar merour, ennañ ur skouerenn a-bezh deus ar postel a zo bet kaset deoc'h (gant an talbennoù ennañ, dreist-holl) Neuze e c'hello hennezh kemer an divizoù a zere");

//
// These entries should remain in all languages and for all modifications
//
$faq[] = array("--","phpBB 2");
$faq[] = array("Piv en deus skrivet ar forum-mañ ?", "Ar poellad-se (en e stumm hep kemmoù) a zo bet savet ha skignet , hag a zo dindan gwirioùar <a href=\"http://www.phpbb.com/\" target=\"_blank\">stollad phpBB</a>. Da gaout emañ dindan aotre boutin GNU ha gallout a ra bezañ skignet forzh pegement en un doare dieub.Klikit war al liamm evit muioc'h a ditouroù.");
$faq[] = array("Perak ne c'hellan ket ober tra-mañ-tra ?", "Ar poellad-se a zo bet skrivet gant ar strollad phpBB, ha dindan e aotre emañ. ma soñjit e vank un dra-bennak dezhañ, kit da welet al lec'hienn phpbb.com evit gwelet ar pezh a soñj ar strollad phpBB. Na gasit goulenn-kemm ebet war forum phpbb.com, sourceforge an hini eo a vez implijet evit ober war-dro an nevezinti.");
$faq[] = array("Gant piv e rankan mont e-darempred evit kudennoù droukimplij pe lezennel liammet ouzh ar forum-se ?", "Rankout a rafec'h mont e-darempred gant merour ar forum. Ma ne deuit ket a-benn da gejañ outañ, goulennit gant unan eus ar c'hasourien gant piv e rankfec'h gwelet se. Ma n'ho peus respont ebet, gwelit gant perc'henn an domani (klaskit gant whois) pe, m'emañ ar forum war ul lojer digoust (da skouer : yahoo, free.fr, f2s.com, etc.), ar renerezh, pe burev droukimplijoù al lojer. Ne c'hell ar strollad phpBB merañ netra, ha ne c'hell e doare ebet bezañ liammetouzh an doare, al lec'h pe an dud a implij ar forum-se. Ne servij da netra klask mont e-darempred ouzh ar strollad phpBB evit istorioù lezennel (gwallvruderezh, hag all.) ma n'o deus liamm eeun ebet gant al lec'hienn phpbb.com pe ar poelladig eo phpBB e-unan. Ma gasit ur bostel d'ar strollad phpBB diwar-benn un den pe ur gudenn lezennel ez eus chañsoù bras n'ho pefe respont ebet.");

//
// This ends the FAQ entries
//

?>